import os
from datetime import datetime
from datetime import timezone
from jinja2 import Template

PDF_CSS = """
@page { size: A4; margin: 1.5cm; }
body { font-family: "Segoe UI", "DejaVu Sans", Arial, sans-serif; font-size: 10pt; }
.header { text-align: center; border-bottom: 2px solid #1a472a; padding-bottom: 10px; margin-bottom: 20px; }
h1 { font-size: 20pt; color: #1a472a; margin: 0; }
.meta { margin: 15px 0; }
table { width: 100%; border-collapse: collapse; margin-top: 15px; }
th, td { border: 1px solid #999; padding: 8px; text-align: right; }
th { background: #f0f0f0; font-weight: bold; }
.total-row { font-weight: bold; background: #e8f5e9; }
.footer { margin-top: 30px; font-size: 8pt; color: #666; border-top: 1px solid #ccc; padding-top: 10px; }
.badge { display: inline-block; padding: 4px 8px; background: #1a472a; color: white; border-radius: 4px; font-size: 9pt; }
"""


def _get_weasyprint():
    from weasyprint import HTML, CSS

    return HTML, CSS


class PDFService:
    @staticmethod
    def _render(template_str: str, data: dict) -> bytes:
        HTML, CSS = _get_weasyprint()
        tmpl = Template(template_str)
        html = tmpl.render(data=data, now=datetime.utcnow().isoformat())
        return HTML(string=html).write_pdf(stylesheets=[CSS(string=PDF_CSS)])

    @staticmethod
    def generate_invoice(data: dict, output_path: str | None = None) -> bytes:
        template = """
        <!DOCTYPE html>
        <html dir="rtl">
        <head><meta charset="utf-8"></head>
        <body>
            <div class="header">
                <h1>\u0641\u0627\u062a\u0648\u0631\u0629 \u0636\u0631\u064a\u0628\u064a\u0629 \u0645\u0628\u0633\u0637\u0629</h1>
                <p>Simplified Tax Invoice <span class="badge">{{ data.branch }}</span></p>
            </div>
            <div class="meta">
                <p><strong>\u0631\u0642\u0645 \u0627\u0644\u0641\u0627\u062a\u0648\u0631\u0629 / No:</strong> {{ data.invoice_no }}</p>
                <p><strong>\u0627\u0644\u062a\u0627\u0631\u064a\u062e / Date:</strong> {{ data.date }}</p>
                <p><strong>\u0627\u0644\u0639\u0645\u064a\u0644 / Client:</strong> {{ data.client_name }}</p>
                <p><strong>\u0627\u0644\u0631\u0642\u0645 \u0627\u0644\u0636\u0631\u064a\u0628\u064a / VAT:</strong> {{ data.client_vat or '\u2014' }}</p>
            </div>
            <table>
                <thead>
                    <tr><th>\u0627\u0644\u0628\u064a\u0627\u0646 / Description</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>
                </thead>
                <tbody>
                    {% for item in data["items"] %}
                    <tr>
                        <td>{{ item.description }}</td>
                        <td>{{ item.qty }}</td>
                        <td>{{ "%.2f"|format(item.unit_price) }}</td>
                        <td>{{ "%.2f"|format(item.total) }}</td>
                    </tr>
                    {% endfor %}
                    <tr class="total-row"><td colspan="3">Subtotal / \u0627\u0644\u0625\u062c\u0645\u0627\u0644\u064a \u0627\u0644\u0641\u0631\u0639\u064a</td><td>{{ "%.2f"|format(data.subtotal) }}</td></tr>
                    <tr class="total-row"><td colspan="3">VAT ({{ data.vat_rate }}%) / \u0636\u0631\u064a\u0628\u0629 \u0627\u0644\u0642\u064a\u0645\u0629 \u0627\u0644\u0645\u0636\u0627\u0641\u0629</td><td>{{ "%.2f"|format(data.vat_amount) }}</td></tr>
                    <tr class="total-row"><td colspan="3">Grand Total / \u0627\u0644\u0625\u062c\u0645\u0627\u0644\u064a \u0627\u0644\u0643\u0644\u064a {{ data.currency }}</td><td>{{ "%.2f"|format(data.total) }}</td></tr>
                </tbody>
            </table>
            <div class="footer">
                <p>Generated by BIO-ERP | {{ now }}</p>
            </div>
        </body>
        </html>
        """
        pdf = PDFService._render(template, data)
        if output_path:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            with open(output_path, "wb") as f:
                f.write(pdf)
        return pdf

    @staticmethod
    def generate_purchase_order(data: dict, output_path: str | None = None) -> bytes:
        template = """
        <!DOCTYPE html>
        <html dir="rtl">
        <head><meta charset="utf-8"></head>
        <body>
            <div class="header">
                <h1>\u0623\u0645\u0631 \u0634\u0631\u0627\u0621</h1>
                <p>Purchase Order <span class="badge">{{ data.branch }}</span></p>
            </div>
            <div class="meta">
                <p><strong>\u0631\u0642\u0645 PO / No:</strong> {{ data.po_no }}</p>
                <p><strong>\u0627\u0644\u0645\u0648\u0631\u062f / Supplier:</strong> {{ data.supplier_name }}</p>
                <p><strong>\u062a\u0627\u0631\u064a\u062e \u0627\u0644\u062a\u0633\u0644\u064a\u0645 / Delivery:</strong> {{ data.delivery_date or '\u2014' }}</p>
            </div>
            <table>
                <thead>
                    <tr><th>Item</th><th>Qty</th><th>Unit</th><th>Total</th></tr>
                </thead>
                <tbody>
                    {% for item in data["items"] %}
                    <tr>
                        <td>{{ item.description }}</td>
                        <td>{{ item.qty }}</td>
                        <td>{{ "%.2f"|format(item.unit_price) }}</td>
                        <td>{{ "%.2f"|format(item.total) }}</td>
                    </tr>
                    {% endfor %}
                    <tr class="total-row"><td colspan="3">Total / \u0627\u0644\u0625\u062c\u0645\u0627\u0644\u064a {{ data.currency }}</td><td>{{ "%.2f"|format(data.total) }}</td></tr>
                </tbody>
            </table>
            <div class="footer"><p>BIO-ERP | {{ now }}</p></div>
        </body>
        </html>
        """
        pdf = PDFService._render(template, data)
        if output_path:
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            with open(output_path, "wb") as f:
                f.write(pdf)
        return pdf
