"""
Sales Module — FastAPI Router
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.066790
Mounted at /api/v1/sal
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status, Query, Body
from sqlalchemy.orm import Session

from app.core.database_mssql import get_db
from .sales_schemas import *
from .sales_services import *

router = APIRouter(prefix="/sal", tags=["Sales"])

@router.get("/sales_order_liness", response_model=SalesOrderLinesListResponse)
def list_sales_order_liness(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all SalesOrderLines records."""
    service = SalesOrderLinesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/sales_order_liness/{id}", response_model=SalesOrderLinesResponse)
def get_sales_order_lines(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get SalesOrderLines by ID."""
    service = SalesOrderLinesService(db)
    return service.get(id)

@router.post("/sales_order_liness", response_model=SalesOrderLinesResponse, status_code=status.HTTP_201_CREATED)
def create_sales_order_lines(
    data: SalesOrderLinesCreate,
    db: Session = Depends(get_db)
):
    """Create a new SalesOrderLines."""
    service = SalesOrderLinesService(db)
    return service.create(data)

@router.put("/sales_order_liness/{id}", response_model=SalesOrderLinesResponse)
def update_sales_order_lines(
    id: UUID,
    data: SalesOrderLinesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing SalesOrderLines."""
    service = SalesOrderLinesService(db)
    return service.update(id, data)

@router.delete("/sales_order_liness/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_sales_order_lines(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a SalesOrderLines (soft delete by default)."""
    service = SalesOrderLinesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/sales_order_liness/search", response_model=List[SalesOrderLinesResponse])
def search_sales_order_liness(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search SalesOrderLines by name/code/description."""
    service = SalesOrderLinesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/sales_orderss", response_model=SalesOrdersListResponse)
def list_sales_orderss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all SalesOrders records."""
    service = SalesOrdersService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/sales_orderss/{id}", response_model=SalesOrdersResponse)
def get_sales_orders(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get SalesOrders by ID."""
    service = SalesOrdersService(db)
    return service.get(id)

@router.post("/sales_orderss", response_model=SalesOrdersResponse, status_code=status.HTTP_201_CREATED)
def create_sales_orders(
    data: SalesOrdersCreate,
    db: Session = Depends(get_db)
):
    """Create a new SalesOrders."""
    service = SalesOrdersService(db)
    return service.create(data)

@router.put("/sales_orderss/{id}", response_model=SalesOrdersResponse)
def update_sales_orders(
    id: UUID,
    data: SalesOrdersUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing SalesOrders."""
    service = SalesOrdersService(db)
    return service.update(id, data)

@router.delete("/sales_orderss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_sales_orders(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a SalesOrders (soft delete by default)."""
    service = SalesOrdersService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/sales_orderss/search", response_model=List[SalesOrdersResponse])
def search_sales_orderss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search SalesOrders by name/code/description."""
    service = SalesOrdersService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/shipmentss", response_model=ShipmentsListResponse)
def list_shipmentss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all Shipments records."""
    service = ShipmentsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/shipmentss/{id}", response_model=ShipmentsResponse)
def get_shipments(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get Shipments by ID."""
    service = ShipmentsService(db)
    return service.get(id)

@router.post("/shipmentss", response_model=ShipmentsResponse, status_code=status.HTTP_201_CREATED)
def create_shipments(
    data: ShipmentsCreate,
    db: Session = Depends(get_db)
):
    """Create a new Shipments."""
    service = ShipmentsService(db)
    return service.create(data)

@router.put("/shipmentss/{id}", response_model=ShipmentsResponse)
def update_shipments(
    id: UUID,
    data: ShipmentsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing Shipments."""
    service = ShipmentsService(db)
    return service.update(id, data)

@router.delete("/shipmentss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_shipments(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a Shipments (soft delete by default)."""
    service = ShipmentsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/shipmentss/search", response_model=List[ShipmentsResponse])
def search_shipmentss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search Shipments by name/code/description."""
    service = ShipmentsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/dashboard/summary")
def get_sales_dashboard(
    company_id: UUID,
    db: Session = Depends(get_db)
):
    """Get Sales dashboard summary."""
    return {
        "module": "sales",
        "company_id": str(company_id),
        "tables": 3,
        "metrics": {}
    }
