"""
Sales Module — Pydantic v2 Schemas
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.060114
Provides Create, Update, Response, and ListResponse schemas per table.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional, Any, Dict
from uuid import UUID

from pydantic import BaseModel, Field, ConfigDict, model_validator, constr, condecimal

# Common response fields mixin
class AuditFields(BaseModel):
    """Audit trail fields included in all responses."""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    created_by: Optional[UUID] = None
    updated_by: Optional[UUID] = None
    is_active: Optional[bool] = True
    company_id: Optional[UUID] = None

class SalesOrderLinesCreate(BaseModel):
    """Schema for creating new SalesOrderLines."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    so_id: UUID
    item_id: UUID
    description: Optional[str] = None
    quantity: Decimal
    delivered_qty: Decimal
    invoiced_qty: Decimal
    uom_id: Optional[UUID] = None
    unit_price: Decimal
    discount_pct: Optional[Decimal] = None
    tax_code_id: Optional[UUID] = None
    line_total: Decimal

class SalesOrderLinesUpdate(BaseModel):
    """Schema for updating existing SalesOrderLines."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    so_id: Optional[UUID] = None
    item_id: Optional[UUID] = None
    description: Optional[str] = None
    quantity: Optional[Decimal] = None
    delivered_qty: Optional[Decimal] = None
    invoiced_qty: Optional[Decimal] = None
    uom_id: Optional[UUID] = None
    unit_price: Optional[Decimal] = None
    discount_pct: Optional[Decimal] = None
    tax_code_id: Optional[UUID] = None
    line_total: Optional[Decimal] = None

class SalesOrderLinesResponse(AuditFields):
    """Response schema for SalesOrderLines (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    so_id: UUID
    item_id: UUID
    description: Optional[str] = None
    quantity: Decimal
    delivered_qty: Decimal
    invoiced_qty: Decimal
    uom_id: Optional[UUID] = None
    unit_price: Decimal
    discount_pct: Optional[Decimal] = None
    tax_code_id: Optional[UUID] = None
    line_total: Decimal

class SalesOrderLinesListResponse(BaseModel):
    """Paginated list response for SalesOrderLines."""
    items: List[SalesOrderLinesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class SalesOrdersCreate(BaseModel):
    """Schema for creating new SalesOrders."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    number: str
    customer_id: UUID
    order_date: date
    delivery_date: Optional[date] = None
    price_list_id: Optional[UUID] = None
    currency: str
    fx_rate: Optional[Decimal] = None
    subtotal: Optional[Decimal] = None
    discount_amount: Optional[Decimal] = None
    tax_amount: Optional[Decimal] = None
    total_amount: Optional[Decimal] = None
    shipping_address_id: Optional[UUID] = None
    salesperson_id: Optional[UUID] = None
    notes: Optional[str] = None
    status: str
    metadata: Optional[str] = None

class SalesOrdersUpdate(BaseModel):
    """Schema for updating existing SalesOrders."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    number: Optional[str] = None
    customer_id: Optional[UUID] = None
    order_date: Optional[date] = None
    delivery_date: Optional[date] = None
    price_list_id: Optional[UUID] = None
    currency: Optional[str] = None
    fx_rate: Optional[Decimal] = None
    subtotal: Optional[Decimal] = None
    discount_amount: Optional[Decimal] = None
    tax_amount: Optional[Decimal] = None
    total_amount: Optional[Decimal] = None
    shipping_address_id: Optional[UUID] = None
    salesperson_id: Optional[UUID] = None
    notes: Optional[str] = None
    status: Optional[str] = None
    metadata: Optional[str] = None

class SalesOrdersResponse(AuditFields):
    """Response schema for SalesOrders (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    number: str
    customer_id: UUID
    order_date: date
    delivery_date: Optional[date] = None
    price_list_id: Optional[UUID] = None
    currency: str
    fx_rate: Optional[Decimal] = None
    subtotal: Optional[Decimal] = None
    discount_amount: Optional[Decimal] = None
    tax_amount: Optional[Decimal] = None
    total_amount: Optional[Decimal] = None
    shipping_address_id: Optional[UUID] = None
    salesperson_id: Optional[UUID] = None
    notes: Optional[str] = None
    status: str
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None

class SalesOrdersListResponse(BaseModel):
    """Paginated list response for SalesOrders."""
    items: List[SalesOrdersResponse]
    total: int
    skip: int = 0
    limit: int = 100

class ShipmentsCreate(BaseModel):
    """Schema for creating new Shipments."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    shipment_number: str
    transport_mode: str
    carrier_name: Optional[str] = None
    carrier_reference: Optional[str] = None
    vessel_name: Optional[str] = None
    voyage_number: Optional[str] = None
    port_of_loading: Optional[str] = None
    port_of_discharge: Optional[str] = None
    final_destination: Optional[str] = None
    etd: Optional[date] = None
    atd: Optional[date] = None
    eta: Optional[date] = None
    ata: Optional[date] = None
    container_type: Optional[str] = None
    container_count: Optional[int] = None
    gross_weight_kg: Optional[Decimal] = None
    volume_cbm: Optional[Decimal] = None
    bill_of_lading_number: Optional[str] = None
    status: Optional[str] = None
    metadata: Optional[str] = None

class ShipmentsUpdate(BaseModel):
    """Schema for updating existing Shipments."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    shipment_number: Optional[str] = None
    transport_mode: Optional[str] = None
    carrier_name: Optional[str] = None
    carrier_reference: Optional[str] = None
    vessel_name: Optional[str] = None
    voyage_number: Optional[str] = None
    port_of_loading: Optional[str] = None
    port_of_discharge: Optional[str] = None
    final_destination: Optional[str] = None
    etd: Optional[date] = None
    atd: Optional[date] = None
    eta: Optional[date] = None
    ata: Optional[date] = None
    container_type: Optional[str] = None
    container_count: Optional[int] = None
    gross_weight_kg: Optional[Decimal] = None
    volume_cbm: Optional[Decimal] = None
    bill_of_lading_number: Optional[str] = None
    status: Optional[str] = None
    metadata: Optional[str] = None

class ShipmentsResponse(AuditFields):
    """Response schema for Shipments (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    shipment_number: str
    transport_mode: str
    carrier_name: Optional[str] = None
    carrier_reference: Optional[str] = None
    vessel_name: Optional[str] = None
    voyage_number: Optional[str] = None
    port_of_loading: Optional[str] = None
    port_of_discharge: Optional[str] = None
    final_destination: Optional[str] = None
    etd: Optional[date] = None
    atd: Optional[date] = None
    eta: Optional[date] = None
    ata: Optional[date] = None
    container_type: Optional[str] = None
    container_count: Optional[int] = None
    gross_weight_kg: Optional[Decimal] = None
    volume_cbm: Optional[Decimal] = None
    bill_of_lading_number: Optional[str] = None
    status: Optional[str] = None
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class ShipmentsListResponse(BaseModel):
    """Paginated list response for Shipments."""
    items: List[ShipmentsResponse]
    total: int
    skip: int = 0
    limit: int = 100
