server {
    listen 80 default_server;
    server_name _;
    client_max_body_size 100M;

    access_log /var/log/nginx/ih_access.log;
    error_log  /var/log/nginx/ih_error.log;

    location / {
        proxy_pass         http://erp:9001;
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";

        proxy_connect_timeout  60s;
        proxy_send_timeout     600s;
        proxy_read_timeout     600s;
        proxy_buffering        off;
    }

    location /health {
        proxy_pass http://erp:9001/health;
        access_log off;
    }
}
