"""
Partners Module — FastAPI Router
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.977086
Mounted at /api/v1/par
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status, Query, Body
from sqlalchemy.orm import Session

from app.core.database_mssql import get_db
from .partners_schemas import *
from .partners_services import *

router = APIRouter(prefix="/par", tags=["Partners"])

@router.get("/business_partnerss", response_model=BusinessPartnersListResponse)
def list_business_partnerss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all BusinessPartners records."""
    service = BusinessPartnersService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/business_partnerss/{id}", response_model=BusinessPartnersResponse)
def get_business_partners(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get BusinessPartners by ID."""
    service = BusinessPartnersService(db)
    return service.get(id)

@router.post("/business_partnerss", response_model=BusinessPartnersResponse, status_code=status.HTTP_201_CREATED)
def create_business_partners(
    data: BusinessPartnersCreate,
    db: Session = Depends(get_db)
):
    """Create a new BusinessPartners."""
    service = BusinessPartnersService(db)
    return service.create(data)

@router.put("/business_partnerss/{id}", response_model=BusinessPartnersResponse)
def update_business_partners(
    id: UUID,
    data: BusinessPartnersUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing BusinessPartners."""
    service = BusinessPartnersService(db)
    return service.update(id, data)

@router.delete("/business_partnerss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_business_partners(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a BusinessPartners (soft delete by default)."""
    service = BusinessPartnersService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/business_partnerss/search", response_model=List[BusinessPartnersResponse])
def search_business_partnerss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search BusinessPartners by name/code/description."""
    service = BusinessPartnersService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/partner_addressess", response_model=PartnerAddressesListResponse)
def list_partner_addressess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all PartnerAddresses records."""
    service = PartnerAddressesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/partner_addressess/{id}", response_model=PartnerAddressesResponse)
def get_partner_addresses(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get PartnerAddresses by ID."""
    service = PartnerAddressesService(db)
    return service.get(id)

@router.post("/partner_addressess", response_model=PartnerAddressesResponse, status_code=status.HTTP_201_CREATED)
def create_partner_addresses(
    data: PartnerAddressesCreate,
    db: Session = Depends(get_db)
):
    """Create a new PartnerAddresses."""
    service = PartnerAddressesService(db)
    return service.create(data)

@router.put("/partner_addressess/{id}", response_model=PartnerAddressesResponse)
def update_partner_addresses(
    id: UUID,
    data: PartnerAddressesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing PartnerAddresses."""
    service = PartnerAddressesService(db)
    return service.update(id, data)

@router.delete("/partner_addressess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_partner_addresses(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a PartnerAddresses (soft delete by default)."""
    service = PartnerAddressesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/partner_addressess/search", response_model=List[PartnerAddressesResponse])
def search_partner_addressess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search PartnerAddresses by name/code/description."""
    service = PartnerAddressesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/partner_bank_accountss", response_model=PartnerBankAccountsListResponse)
def list_partner_bank_accountss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all PartnerBankAccounts records."""
    service = PartnerBankAccountsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/partner_bank_accountss/{id}", response_model=PartnerBankAccountsResponse)
def get_partner_bank_accounts(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get PartnerBankAccounts by ID."""
    service = PartnerBankAccountsService(db)
    return service.get(id)

@router.post("/partner_bank_accountss", response_model=PartnerBankAccountsResponse, status_code=status.HTTP_201_CREATED)
def create_partner_bank_accounts(
    data: PartnerBankAccountsCreate,
    db: Session = Depends(get_db)
):
    """Create a new PartnerBankAccounts."""
    service = PartnerBankAccountsService(db)
    return service.create(data)

@router.put("/partner_bank_accountss/{id}", response_model=PartnerBankAccountsResponse)
def update_partner_bank_accounts(
    id: UUID,
    data: PartnerBankAccountsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing PartnerBankAccounts."""
    service = PartnerBankAccountsService(db)
    return service.update(id, data)

@router.delete("/partner_bank_accountss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_partner_bank_accounts(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a PartnerBankAccounts (soft delete by default)."""
    service = PartnerBankAccountsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/partner_bank_accountss/search", response_model=List[PartnerBankAccountsResponse])
def search_partner_bank_accountss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search PartnerBankAccounts by name/code/description."""
    service = PartnerBankAccountsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/partner_contactss", response_model=PartnerContactsListResponse)
def list_partner_contactss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all PartnerContacts records."""
    service = PartnerContactsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/partner_contactss/{id}", response_model=PartnerContactsResponse)
def get_partner_contacts(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get PartnerContacts by ID."""
    service = PartnerContactsService(db)
    return service.get(id)

@router.post("/partner_contactss", response_model=PartnerContactsResponse, status_code=status.HTTP_201_CREATED)
def create_partner_contacts(
    data: PartnerContactsCreate,
    db: Session = Depends(get_db)
):
    """Create a new PartnerContacts."""
    service = PartnerContactsService(db)
    return service.create(data)

@router.put("/partner_contactss/{id}", response_model=PartnerContactsResponse)
def update_partner_contacts(
    id: UUID,
    data: PartnerContactsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing PartnerContacts."""
    service = PartnerContactsService(db)
    return service.update(id, data)

@router.delete("/partner_contactss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_partner_contacts(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a PartnerContacts (soft delete by default)."""
    service = PartnerContactsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/partner_contactss/search", response_model=List[PartnerContactsResponse])
def search_partner_contactss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search PartnerContacts by name/code/description."""
    service = PartnerContactsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/dashboard/summary")
def get_partners_dashboard(
    company_id: UUID,
    db: Session = Depends(get_db)
):
    """Get Partners dashboard summary."""
    return {
        "module": "partners",
        "company_id": str(company_id),
        "tables": 4,
        "metrics": {}
    }
