"""
Partners Module — FastAPI Sub-App
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.977716
Mounted at /api/v1/par in Bio-ERP main.py
"""
from __future__ import annotations

from fastapi import FastAPI

from .partners_router import router as partners_router

def create_partners_app() -> FastAPI:
    """Factory function to create the partners sub-application."""
    app = FastAPI(
        title="Partners Module",
        description="ERP Partners module — 4 tables",
        version="3.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json"
    )
    app.include_router(partners_router)

    @app.get("/health")
    async def health_check():
        return {
            "status": "healthy",
            "module": "partners",
            "version": "3.0.0",
            "tables": 4,
            "database": "SQL Server 2022"
        }

    @app.get("/")
    async def root():
        return {
            "module": "partners",
            "version": "3.0.0",
            "endpoints": "/docs"
        }

    return app
