"""
Manufacturing Module — Pydantic v2 Schemas
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.654082
Provides Create, Update, Response, and ListResponse schemas per table.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional, Any, Dict
from uuid import UUID

from pydantic import BaseModel, Field, ConfigDict, model_validator, constr, condecimal

# Common response fields mixin
class AuditFields(BaseModel):
    """Audit trail fields included in all responses."""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    created_by: Optional[UUID] = None
    updated_by: Optional[UUID] = None
    is_active: Optional[bool] = True
    company_id: Optional[UUID] = None

class BomLinesCreate(BaseModel):
    """Schema for creating new BomLines."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    bom_id: UUID
    component_id: UUID
    quantity: Decimal
    uom_id: Optional[UUID] = None
    is_phantom: Optional[bool] = None
    scrap_pct: Optional[Decimal] = None
    sequence: Optional[int] = None
    notes: Optional[str] = None

class BomLinesUpdate(BaseModel):
    """Schema for updating existing BomLines."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    bom_id: Optional[UUID] = None
    component_id: Optional[UUID] = None
    quantity: Optional[Decimal] = None
    uom_id: Optional[UUID] = None
    is_phantom: Optional[bool] = None
    scrap_pct: Optional[Decimal] = None
    sequence: Optional[int] = None
    notes: Optional[str] = None

class BomLinesResponse(AuditFields):
    """Response schema for BomLines (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    bom_id: UUID
    component_id: UUID
    quantity: Decimal
    uom_id: Optional[UUID] = None
    is_phantom: Optional[bool] = None
    scrap_pct: Optional[Decimal] = None
    sequence: Optional[int] = None
    notes: Optional[str] = None

class BomLinesListResponse(BaseModel):
    """Paginated list response for BomLines."""
    items: List[BomLinesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class BomsCreate(BaseModel):
    """Schema for creating new Boms."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    item_id: UUID
    version: str
    quantity: Decimal
    uom_id: Optional[UUID] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None

class BomsUpdate(BaseModel):
    """Schema for updating existing Boms."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    item_id: Optional[UUID] = None
    version: Optional[str] = None
    quantity: Optional[Decimal] = None
    uom_id: Optional[UUID] = None
    is_active: Optional[bool] = None
    metadata: Optional[str] = None

class BomsResponse(AuditFields):
    """Response schema for Boms (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    item_id: UUID
    version: str
    quantity: Decimal
    uom_id: Optional[UUID] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None

class BomsListResponse(BaseModel):
    """Paginated list response for Boms."""
    items: List[BomsResponse]
    total: int
    skip: int = 0
    limit: int = 100

class RoutingOperationsCreate(BaseModel):
    """Schema for creating new RoutingOperations."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    routing_id: UUID
    sequence: int
    name: str
    work_centre_id: Optional[UUID] = None
    setup_time_min: Optional[Decimal] = None
    run_time_min: Decimal
    teardown_time_min: Optional[Decimal] = None

class RoutingOperationsUpdate(BaseModel):
    """Schema for updating existing RoutingOperations."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    routing_id: Optional[UUID] = None
    sequence: Optional[int] = None
    name: Optional[str] = None
    work_centre_id: Optional[UUID] = None
    setup_time_min: Optional[Decimal] = None
    run_time_min: Optional[Decimal] = None
    teardown_time_min: Optional[Decimal] = None

class RoutingOperationsResponse(AuditFields):
    """Response schema for RoutingOperations (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    routing_id: UUID
    sequence: int
    name: str
    work_centre_id: Optional[UUID] = None
    setup_time_min: Optional[Decimal] = None
    run_time_min: Decimal
    teardown_time_min: Optional[Decimal] = None

class RoutingOperationsListResponse(BaseModel):
    """Paginated list response for RoutingOperations."""
    items: List[RoutingOperationsResponse]
    total: int
    skip: int = 0
    limit: int = 100

class RoutingsCreate(BaseModel):
    """Schema for creating new Routings."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    item_id: UUID
    name: str
    is_active: Optional[bool] = True

class RoutingsUpdate(BaseModel):
    """Schema for updating existing Routings."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    item_id: Optional[UUID] = None
    name: Optional[str] = None
    is_active: Optional[bool] = None

class RoutingsResponse(AuditFields):
    """Response schema for Routings (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    item_id: UUID
    name: str
    is_active: Optional[bool] = True
    created_at: Optional[datetime] = None

class RoutingsListResponse(BaseModel):
    """Paginated list response for Routings."""
    items: List[RoutingsResponse]
    total: int
    skip: int = 0
    limit: int = 100

class WorkCentresCreate(BaseModel):
    """Schema for creating new WorkCentres."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    code: str
    name: str
    capacity_per_hour: Optional[Decimal] = None
    cost_per_hour: Optional[Decimal] = None
    overhead_pct: Optional[Decimal] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None

class WorkCentresUpdate(BaseModel):
    """Schema for updating existing WorkCentres."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    code: Optional[str] = None
    name: Optional[str] = None
    capacity_per_hour: Optional[Decimal] = None
    cost_per_hour: Optional[Decimal] = None
    overhead_pct: Optional[Decimal] = None
    is_active: Optional[bool] = None
    metadata: Optional[str] = None

class WorkCentresResponse(AuditFields):
    """Response schema for WorkCentres (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    code: str
    name: str
    capacity_per_hour: Optional[Decimal] = None
    cost_per_hour: Optional[Decimal] = None
    overhead_pct: Optional[Decimal] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None

class WorkCentresListResponse(BaseModel):
    """Paginated list response for WorkCentres."""
    items: List[WorkCentresResponse]
    total: int
    skip: int = 0
    limit: int = 100

class WorkOrdersCreate(BaseModel):
    """Schema for creating new WorkOrders."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    number: str
    bom_id: Optional[UUID] = None
    item_id: UUID
    planned_qty: Decimal
    produced_qty: Decimal
    scrapped_qty: Decimal
    planned_start: Optional[date] = None
    planned_end: Optional[date] = None
    actual_start: Optional[datetime] = None
    actual_end: Optional[datetime] = None
    routing_id: Optional[UUID] = None
    warehouse_id: Optional[UUID] = None
    notes: Optional[str] = None
    status: str
    metadata: Optional[str] = None

class WorkOrdersUpdate(BaseModel):
    """Schema for updating existing WorkOrders."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    number: Optional[str] = None
    bom_id: Optional[UUID] = None
    item_id: Optional[UUID] = None
    planned_qty: Optional[Decimal] = None
    produced_qty: Optional[Decimal] = None
    scrapped_qty: Optional[Decimal] = None
    planned_start: Optional[date] = None
    planned_end: Optional[date] = None
    actual_start: Optional[datetime] = None
    actual_end: Optional[datetime] = None
    routing_id: Optional[UUID] = None
    warehouse_id: Optional[UUID] = None
    notes: Optional[str] = None
    status: Optional[str] = None
    metadata: Optional[str] = None

class WorkOrdersResponse(AuditFields):
    """Response schema for WorkOrders (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    number: str
    bom_id: Optional[UUID] = None
    item_id: UUID
    planned_qty: Decimal
    produced_qty: Decimal
    scrapped_qty: Decimal
    planned_start: Optional[date] = None
    planned_end: Optional[date] = None
    actual_start: Optional[datetime] = None
    actual_end: Optional[datetime] = None
    routing_id: Optional[UUID] = None
    warehouse_id: Optional[UUID] = None
    notes: Optional[str] = None
    status: str
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None

class WorkOrdersListResponse(BaseModel):
    """Paginated list response for WorkOrders."""
    items: List[WorkOrdersResponse]
    total: int
    skip: int = 0
    limit: int = 100
