"""
Hr Payroll Module — FastAPI Router
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.553664
Mounted at /api/v1/hrp
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status, Query, Body
from sqlalchemy.orm import Session

from app.core.database_mssql import get_db
from .hr_payroll_schemas import *
from .hr_payroll_services import *

router = APIRouter(prefix="/hrp", tags=["Hr Payroll"])

@router.get("/attendances", response_model=AttendanceListResponse)
def list_attendances(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all Attendance records."""
    service = AttendanceService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/attendances/{id}", response_model=AttendanceResponse)
def get_attendance(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get Attendance by ID."""
    service = AttendanceService(db)
    return service.get(id)

@router.post("/attendances", response_model=AttendanceResponse, status_code=status.HTTP_201_CREATED)
def create_attendance(
    data: AttendanceCreate,
    db: Session = Depends(get_db)
):
    """Create a new Attendance."""
    service = AttendanceService(db)
    return service.create(data)

@router.put("/attendances/{id}", response_model=AttendanceResponse)
def update_attendance(
    id: UUID,
    data: AttendanceUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing Attendance."""
    service = AttendanceService(db)
    return service.update(id, data)

@router.delete("/attendances/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_attendance(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a Attendance (soft delete by default)."""
    service = AttendanceService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/attendances/search", response_model=List[AttendanceResponse])
def search_attendances(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search Attendance by name/code/description."""
    service = AttendanceService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/employee_contractss", response_model=EmployeeContractsListResponse)
def list_employee_contractss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all EmployeeContracts records."""
    service = EmployeeContractsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/employee_contractss/{id}", response_model=EmployeeContractsResponse)
def get_employee_contracts(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get EmployeeContracts by ID."""
    service = EmployeeContractsService(db)
    return service.get(id)

@router.post("/employee_contractss", response_model=EmployeeContractsResponse, status_code=status.HTTP_201_CREATED)
def create_employee_contracts(
    data: EmployeeContractsCreate,
    db: Session = Depends(get_db)
):
    """Create a new EmployeeContracts."""
    service = EmployeeContractsService(db)
    return service.create(data)

@router.put("/employee_contractss/{id}", response_model=EmployeeContractsResponse)
def update_employee_contracts(
    id: UUID,
    data: EmployeeContractsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing EmployeeContracts."""
    service = EmployeeContractsService(db)
    return service.update(id, data)

@router.delete("/employee_contractss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_employee_contracts(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a EmployeeContracts (soft delete by default)."""
    service = EmployeeContractsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/employee_contractss/search", response_model=List[EmployeeContractsResponse])
def search_employee_contractss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search EmployeeContracts by name/code/description."""
    service = EmployeeContractsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/employeess", response_model=EmployeesListResponse)
def list_employeess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all Employees records."""
    service = EmployeesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/employeess/{id}", response_model=EmployeesResponse)
def get_employees(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get Employees by ID."""
    service = EmployeesService(db)
    return service.get(id)

@router.post("/employeess", response_model=EmployeesResponse, status_code=status.HTTP_201_CREATED)
def create_employees(
    data: EmployeesCreate,
    db: Session = Depends(get_db)
):
    """Create a new Employees."""
    service = EmployeesService(db)
    return service.create(data)

@router.put("/employeess/{id}", response_model=EmployeesResponse)
def update_employees(
    id: UUID,
    data: EmployeesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing Employees."""
    service = EmployeesService(db)
    return service.update(id, data)

@router.delete("/employeess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_employees(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a Employees (soft delete by default)."""
    service = EmployeesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/employeess/search", response_model=List[EmployeesResponse])
def search_employeess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search Employees by name/code/description."""
    service = EmployeesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/leave_requestss", response_model=LeaveRequestsListResponse)
def list_leave_requestss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all LeaveRequests records."""
    service = LeaveRequestsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/leave_requestss/{id}", response_model=LeaveRequestsResponse)
def get_leave_requests(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get LeaveRequests by ID."""
    service = LeaveRequestsService(db)
    return service.get(id)

@router.post("/leave_requestss", response_model=LeaveRequestsResponse, status_code=status.HTTP_201_CREATED)
def create_leave_requests(
    data: LeaveRequestsCreate,
    db: Session = Depends(get_db)
):
    """Create a new LeaveRequests."""
    service = LeaveRequestsService(db)
    return service.create(data)

@router.put("/leave_requestss/{id}", response_model=LeaveRequestsResponse)
def update_leave_requests(
    id: UUID,
    data: LeaveRequestsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing LeaveRequests."""
    service = LeaveRequestsService(db)
    return service.update(id, data)

@router.delete("/leave_requestss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_leave_requests(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a LeaveRequests (soft delete by default)."""
    service = LeaveRequestsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/leave_requestss/search", response_model=List[LeaveRequestsResponse])
def search_leave_requestss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search LeaveRequests by name/code/description."""
    service = LeaveRequestsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/leave_typess", response_model=LeaveTypesListResponse)
def list_leave_typess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all LeaveTypes records."""
    service = LeaveTypesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/leave_typess/{id}", response_model=LeaveTypesResponse)
def get_leave_types(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get LeaveTypes by ID."""
    service = LeaveTypesService(db)
    return service.get(id)

@router.post("/leave_typess", response_model=LeaveTypesResponse, status_code=status.HTTP_201_CREATED)
def create_leave_types(
    data: LeaveTypesCreate,
    db: Session = Depends(get_db)
):
    """Create a new LeaveTypes."""
    service = LeaveTypesService(db)
    return service.create(data)

@router.put("/leave_typess/{id}", response_model=LeaveTypesResponse)
def update_leave_types(
    id: UUID,
    data: LeaveTypesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing LeaveTypes."""
    service = LeaveTypesService(db)
    return service.update(id, data)

@router.delete("/leave_typess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_leave_types(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a LeaveTypes (soft delete by default)."""
    service = LeaveTypesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/leave_typess/search", response_model=List[LeaveTypesResponse])
def search_leave_typess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search LeaveTypes by name/code/description."""
    service = LeaveTypesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/payroll_runss", response_model=PayrollRunsListResponse)
def list_payroll_runss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all PayrollRuns records."""
    service = PayrollRunsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/payroll_runss/{id}", response_model=PayrollRunsResponse)
def get_payroll_runs(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get PayrollRuns by ID."""
    service = PayrollRunsService(db)
    return service.get(id)

@router.post("/payroll_runss", response_model=PayrollRunsResponse, status_code=status.HTTP_201_CREATED)
def create_payroll_runs(
    data: PayrollRunsCreate,
    db: Session = Depends(get_db)
):
    """Create a new PayrollRuns."""
    service = PayrollRunsService(db)
    return service.create(data)

@router.put("/payroll_runss/{id}", response_model=PayrollRunsResponse)
def update_payroll_runs(
    id: UUID,
    data: PayrollRunsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing PayrollRuns."""
    service = PayrollRunsService(db)
    return service.update(id, data)

@router.delete("/payroll_runss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_payroll_runs(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a PayrollRuns (soft delete by default)."""
    service = PayrollRunsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/payroll_runss/search", response_model=List[PayrollRunsResponse])
def search_payroll_runss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search PayrollRuns by name/code/description."""
    service = PayrollRunsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/payslipss", response_model=PayslipsListResponse)
def list_payslipss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all Payslips records."""
    service = PayslipsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/payslipss/{id}", response_model=PayslipsResponse)
def get_payslips(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get Payslips by ID."""
    service = PayslipsService(db)
    return service.get(id)

@router.post("/payslipss", response_model=PayslipsResponse, status_code=status.HTTP_201_CREATED)
def create_payslips(
    data: PayslipsCreate,
    db: Session = Depends(get_db)
):
    """Create a new Payslips."""
    service = PayslipsService(db)
    return service.create(data)

@router.put("/payslipss/{id}", response_model=PayslipsResponse)
def update_payslips(
    id: UUID,
    data: PayslipsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing Payslips."""
    service = PayslipsService(db)
    return service.update(id, data)

@router.delete("/payslipss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_payslips(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a Payslips (soft delete by default)."""
    service = PayslipsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/payslipss/search", response_model=List[PayslipsResponse])
def search_payslipss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search Payslips by name/code/description."""
    service = PayslipsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/salary_structuress", response_model=SalaryStructuresListResponse)
def list_salary_structuress(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all SalaryStructures records."""
    service = SalaryStructuresService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/salary_structuress/{id}", response_model=SalaryStructuresResponse)
def get_salary_structures(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get SalaryStructures by ID."""
    service = SalaryStructuresService(db)
    return service.get(id)

@router.post("/salary_structuress", response_model=SalaryStructuresResponse, status_code=status.HTTP_201_CREATED)
def create_salary_structures(
    data: SalaryStructuresCreate,
    db: Session = Depends(get_db)
):
    """Create a new SalaryStructures."""
    service = SalaryStructuresService(db)
    return service.create(data)

@router.put("/salary_structuress/{id}", response_model=SalaryStructuresResponse)
def update_salary_structures(
    id: UUID,
    data: SalaryStructuresUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing SalaryStructures."""
    service = SalaryStructuresService(db)
    return service.update(id, data)

@router.delete("/salary_structuress/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_salary_structures(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a SalaryStructures (soft delete by default)."""
    service = SalaryStructuresService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/salary_structuress/search", response_model=List[SalaryStructuresResponse])
def search_salary_structuress(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search SalaryStructures by name/code/description."""
    service = SalaryStructuresService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/timesheetss", response_model=TimesheetsListResponse)
def list_timesheetss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all Timesheets records."""
    service = TimesheetsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/timesheetss/{id}", response_model=TimesheetsResponse)
def get_timesheets(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get Timesheets by ID."""
    service = TimesheetsService(db)
    return service.get(id)

@router.post("/timesheetss", response_model=TimesheetsResponse, status_code=status.HTTP_201_CREATED)
def create_timesheets(
    data: TimesheetsCreate,
    db: Session = Depends(get_db)
):
    """Create a new Timesheets."""
    service = TimesheetsService(db)
    return service.create(data)

@router.put("/timesheetss/{id}", response_model=TimesheetsResponse)
def update_timesheets(
    id: UUID,
    data: TimesheetsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing Timesheets."""
    service = TimesheetsService(db)
    return service.update(id, data)

@router.delete("/timesheetss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_timesheets(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a Timesheets (soft delete by default)."""
    service = TimesheetsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/timesheetss/search", response_model=List[TimesheetsResponse])
def search_timesheetss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search Timesheets by name/code/description."""
    service = TimesheetsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/dashboard/summary")
def get_hr_payroll_dashboard(
    company_id: UUID,
    db: Session = Depends(get_db)
):
    """Get Hr Payroll dashboard summary."""
    return {
        "module": "hr_payroll",
        "company_id": str(company_id),
        "tables": 9,
        "metrics": {}
    }
