"""
Procurement Module — CRUD Services
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.003803
Full CRUD with audit trail, soft delete, and business validations.
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID
from datetime import datetime
from decimal import Decimal

from sqlalchemy.orm import Session, joinedload
from sqlalchemy import and_, or_, desc, func
from fastapi import HTTPException, status
import uuid

from .procurement_models import *
from .procurement_schemas import *

class ApprovalMatricesService:
    """CRUD service for ApprovalMatrices."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: ApprovalMatricesCreate, created_by: Optional[UUID] = None) -> ApprovalMatricesResponse:
        """Create a new ApprovalMatrices record."""
        db_obj = ApprovalMatrices(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return ApprovalMatricesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[ApprovalMatricesResponse]:
        """Get ApprovalMatrices by primary key."""
        db_obj = self.db.query(ApprovalMatrices).filter(ApprovalMatrices.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ApprovalMatrices not found")
        return ApprovalMatricesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> ApprovalMatricesListResponse:
        """List ApprovalMatrices records with pagination and filtering."""
        query = self.db.query(ApprovalMatrices)
        if company_id and hasattr(ApprovalMatrices, "company_id"):
            query = query.filter(ApprovalMatrices.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(ApprovalMatrices, key) and value is not None:
                    query = query.filter(getattr(ApprovalMatrices, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(ApprovalMatrices, order_by, ApprovalMatrices.created_at)))
        else:
            query = query.order_by(getattr(ApprovalMatrices, order_by, ApprovalMatrices.created_at))
        items = query.offset(skip).limit(limit).all()
        return ApprovalMatricesListResponse(
            items=[ApprovalMatricesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: ApprovalMatricesUpdate,
               updated_by: Optional[UUID] = None) -> ApprovalMatricesResponse:
        """Update an existing ApprovalMatrices record."""
        db_obj = self.db.query(ApprovalMatrices).filter(ApprovalMatrices.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ApprovalMatrices not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return ApprovalMatricesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a ApprovalMatrices record. Soft delete by default."""
        db_obj = self.db.query(ApprovalMatrices).filter(ApprovalMatrices.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ApprovalMatrices not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[ApprovalMatricesResponse]:
        """Search ApprovalMatrices by name/code fields."""
        query = self.db.query(ApprovalMatrices)
        if company_id and hasattr(ApprovalMatrices, "company_id"):
            query = query.filter(ApprovalMatrices.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(ApprovalMatrices, f)]
        if search_fields:
            conditions = [getattr(ApprovalMatrices, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [ApprovalMatricesResponse.model_validate(i) for i in items]

class PurchaseOrderLinesService:
    """CRUD service for PurchaseOrderLines."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: PurchaseOrderLinesCreate, created_by: Optional[UUID] = None) -> PurchaseOrderLinesResponse:
        """Create a new PurchaseOrderLines record."""
        db_obj = PurchaseOrderLines(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return PurchaseOrderLinesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[PurchaseOrderLinesResponse]:
        """Get PurchaseOrderLines by primary key."""
        db_obj = self.db.query(PurchaseOrderLines).filter(PurchaseOrderLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseOrderLines not found")
        return PurchaseOrderLinesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> PurchaseOrderLinesListResponse:
        """List PurchaseOrderLines records with pagination and filtering."""
        query = self.db.query(PurchaseOrderLines)
        if company_id and hasattr(PurchaseOrderLines, "company_id"):
            query = query.filter(PurchaseOrderLines.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(PurchaseOrderLines, key) and value is not None:
                    query = query.filter(getattr(PurchaseOrderLines, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(PurchaseOrderLines, order_by, PurchaseOrderLines.created_at)))
        else:
            query = query.order_by(getattr(PurchaseOrderLines, order_by, PurchaseOrderLines.created_at))
        items = query.offset(skip).limit(limit).all()
        return PurchaseOrderLinesListResponse(
            items=[PurchaseOrderLinesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: PurchaseOrderLinesUpdate,
               updated_by: Optional[UUID] = None) -> PurchaseOrderLinesResponse:
        """Update an existing PurchaseOrderLines record."""
        db_obj = self.db.query(PurchaseOrderLines).filter(PurchaseOrderLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseOrderLines not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return PurchaseOrderLinesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a PurchaseOrderLines record. Soft delete by default."""
        db_obj = self.db.query(PurchaseOrderLines).filter(PurchaseOrderLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseOrderLines not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[PurchaseOrderLinesResponse]:
        """Search PurchaseOrderLines by name/code fields."""
        query = self.db.query(PurchaseOrderLines)
        if company_id and hasattr(PurchaseOrderLines, "company_id"):
            query = query.filter(PurchaseOrderLines.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(PurchaseOrderLines, f)]
        if search_fields:
            conditions = [getattr(PurchaseOrderLines, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [PurchaseOrderLinesResponse.model_validate(i) for i in items]

class PurchaseOrdersService:
    """CRUD service for PurchaseOrders."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: PurchaseOrdersCreate, created_by: Optional[UUID] = None) -> PurchaseOrdersResponse:
        """Create a new PurchaseOrders record."""
        db_obj = PurchaseOrders(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return PurchaseOrdersResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[PurchaseOrdersResponse]:
        """Get PurchaseOrders by primary key."""
        db_obj = self.db.query(PurchaseOrders).filter(PurchaseOrders.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseOrders not found")
        return PurchaseOrdersResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> PurchaseOrdersListResponse:
        """List PurchaseOrders records with pagination and filtering."""
        query = self.db.query(PurchaseOrders)
        if company_id and hasattr(PurchaseOrders, "company_id"):
            query = query.filter(PurchaseOrders.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(PurchaseOrders, key) and value is not None:
                    query = query.filter(getattr(PurchaseOrders, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(PurchaseOrders, order_by, PurchaseOrders.created_at)))
        else:
            query = query.order_by(getattr(PurchaseOrders, order_by, PurchaseOrders.created_at))
        items = query.offset(skip).limit(limit).all()
        return PurchaseOrdersListResponse(
            items=[PurchaseOrdersResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: PurchaseOrdersUpdate,
               updated_by: Optional[UUID] = None) -> PurchaseOrdersResponse:
        """Update an existing PurchaseOrders record."""
        db_obj = self.db.query(PurchaseOrders).filter(PurchaseOrders.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseOrders not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return PurchaseOrdersResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a PurchaseOrders record. Soft delete by default."""
        db_obj = self.db.query(PurchaseOrders).filter(PurchaseOrders.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseOrders not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[PurchaseOrdersResponse]:
        """Search PurchaseOrders by name/code fields."""
        query = self.db.query(PurchaseOrders)
        if company_id and hasattr(PurchaseOrders, "company_id"):
            query = query.filter(PurchaseOrders.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(PurchaseOrders, f)]
        if search_fields:
            conditions = [getattr(PurchaseOrders, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [PurchaseOrdersResponse.model_validate(i) for i in items]

class PurchaseRequestLinesService:
    """CRUD service for PurchaseRequestLines."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: PurchaseRequestLinesCreate, created_by: Optional[UUID] = None) -> PurchaseRequestLinesResponse:
        """Create a new PurchaseRequestLines record."""
        db_obj = PurchaseRequestLines(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return PurchaseRequestLinesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[PurchaseRequestLinesResponse]:
        """Get PurchaseRequestLines by primary key."""
        db_obj = self.db.query(PurchaseRequestLines).filter(PurchaseRequestLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseRequestLines not found")
        return PurchaseRequestLinesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> PurchaseRequestLinesListResponse:
        """List PurchaseRequestLines records with pagination and filtering."""
        query = self.db.query(PurchaseRequestLines)
        if company_id and hasattr(PurchaseRequestLines, "company_id"):
            query = query.filter(PurchaseRequestLines.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(PurchaseRequestLines, key) and value is not None:
                    query = query.filter(getattr(PurchaseRequestLines, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(PurchaseRequestLines, order_by, PurchaseRequestLines.created_at)))
        else:
            query = query.order_by(getattr(PurchaseRequestLines, order_by, PurchaseRequestLines.created_at))
        items = query.offset(skip).limit(limit).all()
        return PurchaseRequestLinesListResponse(
            items=[PurchaseRequestLinesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: PurchaseRequestLinesUpdate,
               updated_by: Optional[UUID] = None) -> PurchaseRequestLinesResponse:
        """Update an existing PurchaseRequestLines record."""
        db_obj = self.db.query(PurchaseRequestLines).filter(PurchaseRequestLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseRequestLines not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return PurchaseRequestLinesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a PurchaseRequestLines record. Soft delete by default."""
        db_obj = self.db.query(PurchaseRequestLines).filter(PurchaseRequestLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseRequestLines not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[PurchaseRequestLinesResponse]:
        """Search PurchaseRequestLines by name/code fields."""
        query = self.db.query(PurchaseRequestLines)
        if company_id and hasattr(PurchaseRequestLines, "company_id"):
            query = query.filter(PurchaseRequestLines.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(PurchaseRequestLines, f)]
        if search_fields:
            conditions = [getattr(PurchaseRequestLines, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [PurchaseRequestLinesResponse.model_validate(i) for i in items]

class PurchaseRequestsService:
    """CRUD service for PurchaseRequests."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: PurchaseRequestsCreate, created_by: Optional[UUID] = None) -> PurchaseRequestsResponse:
        """Create a new PurchaseRequests record."""
        db_obj = PurchaseRequests(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return PurchaseRequestsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[PurchaseRequestsResponse]:
        """Get PurchaseRequests by primary key."""
        db_obj = self.db.query(PurchaseRequests).filter(PurchaseRequests.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseRequests not found")
        return PurchaseRequestsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> PurchaseRequestsListResponse:
        """List PurchaseRequests records with pagination and filtering."""
        query = self.db.query(PurchaseRequests)
        if company_id and hasattr(PurchaseRequests, "company_id"):
            query = query.filter(PurchaseRequests.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(PurchaseRequests, key) and value is not None:
                    query = query.filter(getattr(PurchaseRequests, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(PurchaseRequests, order_by, PurchaseRequests.created_at)))
        else:
            query = query.order_by(getattr(PurchaseRequests, order_by, PurchaseRequests.created_at))
        items = query.offset(skip).limit(limit).all()
        return PurchaseRequestsListResponse(
            items=[PurchaseRequestsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: PurchaseRequestsUpdate,
               updated_by: Optional[UUID] = None) -> PurchaseRequestsResponse:
        """Update an existing PurchaseRequests record."""
        db_obj = self.db.query(PurchaseRequests).filter(PurchaseRequests.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseRequests not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return PurchaseRequestsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a PurchaseRequests record. Soft delete by default."""
        db_obj = self.db.query(PurchaseRequests).filter(PurchaseRequests.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PurchaseRequests not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[PurchaseRequestsResponse]:
        """Search PurchaseRequests by name/code fields."""
        query = self.db.query(PurchaseRequests)
        if company_id and hasattr(PurchaseRequests, "company_id"):
            query = query.filter(PurchaseRequests.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(PurchaseRequests, f)]
        if search_fields:
            conditions = [getattr(PurchaseRequests, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [PurchaseRequestsResponse.model_validate(i) for i in items]

class QualityInspectionsService:
    """CRUD service for QualityInspections."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: QualityInspectionsCreate, created_by: Optional[UUID] = None) -> QualityInspectionsResponse:
        """Create a new QualityInspections record."""
        db_obj = QualityInspections(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return QualityInspectionsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[QualityInspectionsResponse]:
        """Get QualityInspections by primary key."""
        db_obj = self.db.query(QualityInspections).filter(QualityInspections.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="QualityInspections not found")
        return QualityInspectionsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> QualityInspectionsListResponse:
        """List QualityInspections records with pagination and filtering."""
        query = self.db.query(QualityInspections)
        if company_id and hasattr(QualityInspections, "company_id"):
            query = query.filter(QualityInspections.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(QualityInspections, key) and value is not None:
                    query = query.filter(getattr(QualityInspections, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(QualityInspections, order_by, QualityInspections.created_at)))
        else:
            query = query.order_by(getattr(QualityInspections, order_by, QualityInspections.created_at))
        items = query.offset(skip).limit(limit).all()
        return QualityInspectionsListResponse(
            items=[QualityInspectionsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: QualityInspectionsUpdate,
               updated_by: Optional[UUID] = None) -> QualityInspectionsResponse:
        """Update an existing QualityInspections record."""
        db_obj = self.db.query(QualityInspections).filter(QualityInspections.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="QualityInspections not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return QualityInspectionsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a QualityInspections record. Soft delete by default."""
        db_obj = self.db.query(QualityInspections).filter(QualityInspections.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="QualityInspections not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[QualityInspectionsResponse]:
        """Search QualityInspections by name/code fields."""
        query = self.db.query(QualityInspections)
        if company_id and hasattr(QualityInspections, "company_id"):
            query = query.filter(QualityInspections.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(QualityInspections, f)]
        if search_fields:
            conditions = [getattr(QualityInspections, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [QualityInspectionsResponse.model_validate(i) for i in items]
