"""
Fixed Assets Module — FastAPI Sub-App
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.513709
Mounted at /api/v1/fxa in Bio-ERP main.py
"""
from __future__ import annotations

from fastapi import FastAPI

from .fixed_assets_router import router as fixed_assets_router

def create_fixed_assets_app() -> FastAPI:
    """Factory function to create the fixed_assets sub-application."""
    app = FastAPI(
        title="Fixed Assets Module",
        description="ERP Fixed Assets module — 5 tables",
        version="3.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json"
    )
    app.include_router(fixed_assets_router)

    @app.get("/health")
    async def health_check():
        return {
            "status": "healthy",
            "module": "fixed_assets",
            "version": "3.0.0",
            "tables": 5,
            "database": "SQL Server 2022"
        }

    @app.get("/")
    async def root():
        return {
            "module": "fixed_assets",
            "version": "3.0.0",
            "endpoints": "/docs"
        }

    return app
