"""
Fixed Assets Module — FastAPI Router
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.513448
Mounted at /api/v1/fxa
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status, Query, Body
from sqlalchemy.orm import Session

from app.core.database_mssql import get_db
from .fixed_assets_schemas import *
from .fixed_assets_services import *

router = APIRouter(prefix="/fxa", tags=["Fixed Assets"])

@router.get("/asset_categoriess", response_model=AssetCategoriesListResponse)
def list_asset_categoriess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all AssetCategories records."""
    service = AssetCategoriesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/asset_categoriess/{id}", response_model=AssetCategoriesResponse)
def get_asset_categories(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get AssetCategories by ID."""
    service = AssetCategoriesService(db)
    return service.get(id)

@router.post("/asset_categoriess", response_model=AssetCategoriesResponse, status_code=status.HTTP_201_CREATED)
def create_asset_categories(
    data: AssetCategoriesCreate,
    db: Session = Depends(get_db)
):
    """Create a new AssetCategories."""
    service = AssetCategoriesService(db)
    return service.create(data)

@router.put("/asset_categoriess/{id}", response_model=AssetCategoriesResponse)
def update_asset_categories(
    id: UUID,
    data: AssetCategoriesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing AssetCategories."""
    service = AssetCategoriesService(db)
    return service.update(id, data)

@router.delete("/asset_categoriess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_asset_categories(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a AssetCategories (soft delete by default)."""
    service = AssetCategoriesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/asset_categoriess/search", response_model=List[AssetCategoriesResponse])
def search_asset_categoriess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search AssetCategories by name/code/description."""
    service = AssetCategoriesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/asset_depreciation_liness", response_model=AssetDepreciationLinesListResponse)
def list_asset_depreciation_liness(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all AssetDepreciationLines records."""
    service = AssetDepreciationLinesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/asset_depreciation_liness/{id}", response_model=AssetDepreciationLinesResponse)
def get_asset_depreciation_lines(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get AssetDepreciationLines by ID."""
    service = AssetDepreciationLinesService(db)
    return service.get(id)

@router.post("/asset_depreciation_liness", response_model=AssetDepreciationLinesResponse, status_code=status.HTTP_201_CREATED)
def create_asset_depreciation_lines(
    data: AssetDepreciationLinesCreate,
    db: Session = Depends(get_db)
):
    """Create a new AssetDepreciationLines."""
    service = AssetDepreciationLinesService(db)
    return service.create(data)

@router.put("/asset_depreciation_liness/{id}", response_model=AssetDepreciationLinesResponse)
def update_asset_depreciation_lines(
    id: UUID,
    data: AssetDepreciationLinesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing AssetDepreciationLines."""
    service = AssetDepreciationLinesService(db)
    return service.update(id, data)

@router.delete("/asset_depreciation_liness/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_asset_depreciation_lines(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a AssetDepreciationLines (soft delete by default)."""
    service = AssetDepreciationLinesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/asset_depreciation_liness/search", response_model=List[AssetDepreciationLinesResponse])
def search_asset_depreciation_liness(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search AssetDepreciationLines by name/code/description."""
    service = AssetDepreciationLinesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/asset_depreciation_runss", response_model=AssetDepreciationRunsListResponse)
def list_asset_depreciation_runss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all AssetDepreciationRuns records."""
    service = AssetDepreciationRunsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/asset_depreciation_runss/{id}", response_model=AssetDepreciationRunsResponse)
def get_asset_depreciation_runs(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get AssetDepreciationRuns by ID."""
    service = AssetDepreciationRunsService(db)
    return service.get(id)

@router.post("/asset_depreciation_runss", response_model=AssetDepreciationRunsResponse, status_code=status.HTTP_201_CREATED)
def create_asset_depreciation_runs(
    data: AssetDepreciationRunsCreate,
    db: Session = Depends(get_db)
):
    """Create a new AssetDepreciationRuns."""
    service = AssetDepreciationRunsService(db)
    return service.create(data)

@router.put("/asset_depreciation_runss/{id}", response_model=AssetDepreciationRunsResponse)
def update_asset_depreciation_runs(
    id: UUID,
    data: AssetDepreciationRunsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing AssetDepreciationRuns."""
    service = AssetDepreciationRunsService(db)
    return service.update(id, data)

@router.delete("/asset_depreciation_runss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_asset_depreciation_runs(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a AssetDepreciationRuns (soft delete by default)."""
    service = AssetDepreciationRunsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/asset_depreciation_runss/search", response_model=List[AssetDepreciationRunsResponse])
def search_asset_depreciation_runss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search AssetDepreciationRuns by name/code/description."""
    service = AssetDepreciationRunsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/asset_maintenances", response_model=AssetMaintenanceListResponse)
def list_asset_maintenances(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all AssetMaintenance records."""
    service = AssetMaintenanceService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/asset_maintenances/{id}", response_model=AssetMaintenanceResponse)
def get_asset_maintenance(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get AssetMaintenance by ID."""
    service = AssetMaintenanceService(db)
    return service.get(id)

@router.post("/asset_maintenances", response_model=AssetMaintenanceResponse, status_code=status.HTTP_201_CREATED)
def create_asset_maintenance(
    data: AssetMaintenanceCreate,
    db: Session = Depends(get_db)
):
    """Create a new AssetMaintenance."""
    service = AssetMaintenanceService(db)
    return service.create(data)

@router.put("/asset_maintenances/{id}", response_model=AssetMaintenanceResponse)
def update_asset_maintenance(
    id: UUID,
    data: AssetMaintenanceUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing AssetMaintenance."""
    service = AssetMaintenanceService(db)
    return service.update(id, data)

@router.delete("/asset_maintenances/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_asset_maintenance(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a AssetMaintenance (soft delete by default)."""
    service = AssetMaintenanceService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/asset_maintenances/search", response_model=List[AssetMaintenanceResponse])
def search_asset_maintenances(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search AssetMaintenance by name/code/description."""
    service = AssetMaintenanceService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/fixed_assetss", response_model=FixedAssetsListResponse)
def list_fixed_assetss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all FixedAssets records."""
    service = FixedAssetsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/fixed_assetss/{id}", response_model=FixedAssetsResponse)
def get_fixed_assets(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get FixedAssets by ID."""
    service = FixedAssetsService(db)
    return service.get(id)

@router.post("/fixed_assetss", response_model=FixedAssetsResponse, status_code=status.HTTP_201_CREATED)
def create_fixed_assets(
    data: FixedAssetsCreate,
    db: Session = Depends(get_db)
):
    """Create a new FixedAssets."""
    service = FixedAssetsService(db)
    return service.create(data)

@router.put("/fixed_assetss/{id}", response_model=FixedAssetsResponse)
def update_fixed_assets(
    id: UUID,
    data: FixedAssetsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing FixedAssets."""
    service = FixedAssetsService(db)
    return service.update(id, data)

@router.delete("/fixed_assetss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_fixed_assets(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a FixedAssets (soft delete by default)."""
    service = FixedAssetsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/fixed_assetss/search", response_model=List[FixedAssetsResponse])
def search_fixed_assetss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search FixedAssets by name/code/description."""
    service = FixedAssetsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/dashboard/summary")
def get_fixed_assets_dashboard(
    company_id: UUID,
    db: Session = Depends(get_db)
):
    """Get Fixed Assets dashboard summary."""
    return {
        "module": "fixed_assets",
        "company_id": str(company_id),
        "tables": 5,
        "metrics": {}
    }
