"""
Fixed Assets Module — Pydantic v2 Schemas
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.511200
Provides Create, Update, Response, and ListResponse schemas per table.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional, Any, Dict
from uuid import UUID

from pydantic import BaseModel, Field, ConfigDict, model_validator, constr, condecimal

# Common response fields mixin
class AuditFields(BaseModel):
    """Audit trail fields included in all responses."""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    created_by: Optional[UUID] = None
    updated_by: Optional[UUID] = None
    is_active: Optional[bool] = True
    company_id: Optional[UUID] = None

class AssetCategoriesCreate(BaseModel):
    """Schema for creating new AssetCategories."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    name: str
    depreciation_method: str
    useful_life_years: Optional[Decimal] = None
    salvage_value_pct: Optional[Decimal] = None
    asset_account_id: Optional[UUID] = None
    accum_dep_account_id: Optional[UUID] = None
    dep_expense_account_id: Optional[UUID] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None

class AssetCategoriesUpdate(BaseModel):
    """Schema for updating existing AssetCategories."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    name: Optional[str] = None
    depreciation_method: Optional[str] = None
    useful_life_years: Optional[Decimal] = None
    salvage_value_pct: Optional[Decimal] = None
    asset_account_id: Optional[UUID] = None
    accum_dep_account_id: Optional[UUID] = None
    dep_expense_account_id: Optional[UUID] = None
    is_active: Optional[bool] = None
    metadata: Optional[str] = None

class AssetCategoriesResponse(AuditFields):
    """Response schema for AssetCategories (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    name: str
    depreciation_method: str
    useful_life_years: Optional[Decimal] = None
    salvage_value_pct: Optional[Decimal] = None
    asset_account_id: Optional[UUID] = None
    accum_dep_account_id: Optional[UUID] = None
    dep_expense_account_id: Optional[UUID] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None

class AssetCategoriesListResponse(BaseModel):
    """Paginated list response for AssetCategories."""
    items: List[AssetCategoriesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class AssetDepreciationLinesCreate(BaseModel):
    """Schema for creating new AssetDepreciationLines."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    run_id: UUID
    asset_id: UUID
    dep_amount: Decimal
    opening_nbv: Optional[Decimal] = None
    closing_nbv: Optional[Decimal] = None
    metadata: Optional[str] = None

class AssetDepreciationLinesUpdate(BaseModel):
    """Schema for updating existing AssetDepreciationLines."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    run_id: Optional[UUID] = None
    asset_id: Optional[UUID] = None
    dep_amount: Optional[Decimal] = None
    opening_nbv: Optional[Decimal] = None
    closing_nbv: Optional[Decimal] = None
    metadata: Optional[str] = None

class AssetDepreciationLinesResponse(AuditFields):
    """Response schema for AssetDepreciationLines (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    run_id: UUID
    asset_id: UUID
    dep_amount: Decimal
    opening_nbv: Optional[Decimal] = None
    closing_nbv: Optional[Decimal] = None
    metadata: Optional[str] = None

class AssetDepreciationLinesListResponse(BaseModel):
    """Paginated list response for AssetDepreciationLines."""
    items: List[AssetDepreciationLinesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class AssetDepreciationRunsCreate(BaseModel):
    """Schema for creating new AssetDepreciationRuns."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    period_id: UUID
    run_date: date
    status: str
    journal_entry_id: Optional[UUID] = None
    total_depreciation: Optional[Decimal] = None

class AssetDepreciationRunsUpdate(BaseModel):
    """Schema for updating existing AssetDepreciationRuns."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    period_id: Optional[UUID] = None
    run_date: Optional[date] = None
    status: Optional[str] = None
    journal_entry_id: Optional[UUID] = None
    total_depreciation: Optional[Decimal] = None

class AssetDepreciationRunsResponse(AuditFields):
    """Response schema for AssetDepreciationRuns (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    period_id: UUID
    run_date: date
    status: str
    journal_entry_id: Optional[UUID] = None
    total_depreciation: Optional[Decimal] = None
    created_at: Optional[datetime] = None

class AssetDepreciationRunsListResponse(BaseModel):
    """Paginated list response for AssetDepreciationRuns."""
    items: List[AssetDepreciationRunsResponse]
    total: int
    skip: int = 0
    limit: int = 100

class AssetMaintenanceCreate(BaseModel):
    """Schema for creating new AssetMaintenance."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    asset_id: UUID
    maintenance_date: date
    maintenance_type: Optional[str] = None
    description: Optional[str] = None
    cost: Optional[Decimal] = None
    vendor_id: Optional[UUID] = None
    next_due_date: Optional[date] = None
    notes: Optional[str] = None

class AssetMaintenanceUpdate(BaseModel):
    """Schema for updating existing AssetMaintenance."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    asset_id: Optional[UUID] = None
    maintenance_date: Optional[date] = None
    maintenance_type: Optional[str] = None
    description: Optional[str] = None
    cost: Optional[Decimal] = None
    vendor_id: Optional[UUID] = None
    next_due_date: Optional[date] = None
    notes: Optional[str] = None

class AssetMaintenanceResponse(AuditFields):
    """Response schema for AssetMaintenance (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    asset_id: UUID
    maintenance_date: date
    maintenance_type: Optional[str] = None
    description: Optional[str] = None
    cost: Optional[Decimal] = None
    vendor_id: Optional[UUID] = None
    next_due_date: Optional[date] = None
    notes: Optional[str] = None
    created_at: Optional[datetime] = None

class AssetMaintenanceListResponse(BaseModel):
    """Paginated list response for AssetMaintenance."""
    items: List[AssetMaintenanceResponse]
    total: int
    skip: int = 0
    limit: int = 100

class FixedAssetsCreate(BaseModel):
    """Schema for creating new FixedAssets."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    asset_number: str
    name: str
    category_id: UUID
    purchase_date: date
    in_service_date: Optional[date] = None
    purchase_cost: Decimal
    salvage_value: Optional[Decimal] = None
    depreciation_method: Optional[str] = None
    useful_life_years: Optional[Decimal] = None
    accumulated_dep: Decimal
    net_book_value: Optional[Decimal] = None
    location: Optional[str] = None
    serial_number: Optional[str] = None
    po_id: Optional[UUID] = None
    insurance_value: Optional[Decimal] = None
    insured_until: Optional[date] = None
    disposal_date: Optional[date] = None
    disposal_amount: Optional[Decimal] = None
    status: str
    metadata: Optional[str] = None

class FixedAssetsUpdate(BaseModel):
    """Schema for updating existing FixedAssets."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    asset_number: Optional[str] = None
    name: Optional[str] = None
    category_id: Optional[UUID] = None
    purchase_date: Optional[date] = None
    in_service_date: Optional[date] = None
    purchase_cost: Optional[Decimal] = None
    salvage_value: Optional[Decimal] = None
    depreciation_method: Optional[str] = None
    useful_life_years: Optional[Decimal] = None
    accumulated_dep: Optional[Decimal] = None
    net_book_value: Optional[Decimal] = None
    location: Optional[str] = None
    serial_number: Optional[str] = None
    po_id: Optional[UUID] = None
    insurance_value: Optional[Decimal] = None
    insured_until: Optional[date] = None
    disposal_date: Optional[date] = None
    disposal_amount: Optional[Decimal] = None
    status: Optional[str] = None
    metadata: Optional[str] = None

class FixedAssetsResponse(AuditFields):
    """Response schema for FixedAssets (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    asset_number: str
    name: str
    category_id: UUID
    purchase_date: date
    in_service_date: Optional[date] = None
    purchase_cost: Decimal
    salvage_value: Optional[Decimal] = None
    depreciation_method: Optional[str] = None
    useful_life_years: Optional[Decimal] = None
    accumulated_dep: Decimal
    net_book_value: Optional[Decimal] = None
    location: Optional[str] = None
    serial_number: Optional[str] = None
    po_id: Optional[UUID] = None
    insurance_value: Optional[Decimal] = None
    insured_until: Optional[date] = None
    disposal_date: Optional[date] = None
    disposal_amount: Optional[Decimal] = None
    status: str
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None

class FixedAssetsListResponse(BaseModel):
    """Paginated list response for FixedAssets."""
    items: List[FixedAssetsResponse]
    total: int
    skip: int = 0
    limit: int = 100
