"""
Fixed Assets Module — CRUD Services
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.513271
Full CRUD with audit trail, soft delete, and business validations.
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID
from datetime import datetime
from decimal import Decimal

from sqlalchemy.orm import Session, joinedload
from sqlalchemy import and_, or_, desc, func
from fastapi import HTTPException, status
import uuid

from .fixed_assets_models import *
from .fixed_assets_schemas import *

class AssetCategoriesService:
    """CRUD service for AssetCategories."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: AssetCategoriesCreate, created_by: Optional[UUID] = None) -> AssetCategoriesResponse:
        """Create a new AssetCategories record."""
        db_obj = AssetCategories(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return AssetCategoriesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[AssetCategoriesResponse]:
        """Get AssetCategories by primary key."""
        db_obj = self.db.query(AssetCategories).filter(AssetCategories.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetCategories not found")
        return AssetCategoriesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> AssetCategoriesListResponse:
        """List AssetCategories records with pagination and filtering."""
        query = self.db.query(AssetCategories)
        if company_id and hasattr(AssetCategories, "company_id"):
            query = query.filter(AssetCategories.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(AssetCategories, key) and value is not None:
                    query = query.filter(getattr(AssetCategories, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(AssetCategories, order_by, AssetCategories.created_at)))
        else:
            query = query.order_by(getattr(AssetCategories, order_by, AssetCategories.created_at))
        items = query.offset(skip).limit(limit).all()
        return AssetCategoriesListResponse(
            items=[AssetCategoriesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: AssetCategoriesUpdate,
               updated_by: Optional[UUID] = None) -> AssetCategoriesResponse:
        """Update an existing AssetCategories record."""
        db_obj = self.db.query(AssetCategories).filter(AssetCategories.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetCategories not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return AssetCategoriesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a AssetCategories record. Soft delete by default."""
        db_obj = self.db.query(AssetCategories).filter(AssetCategories.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetCategories not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[AssetCategoriesResponse]:
        """Search AssetCategories by name/code fields."""
        query = self.db.query(AssetCategories)
        if company_id and hasattr(AssetCategories, "company_id"):
            query = query.filter(AssetCategories.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(AssetCategories, f)]
        if search_fields:
            conditions = [getattr(AssetCategories, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [AssetCategoriesResponse.model_validate(i) for i in items]

class AssetDepreciationLinesService:
    """CRUD service for AssetDepreciationLines."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: AssetDepreciationLinesCreate, created_by: Optional[UUID] = None) -> AssetDepreciationLinesResponse:
        """Create a new AssetDepreciationLines record."""
        db_obj = AssetDepreciationLines(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return AssetDepreciationLinesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[AssetDepreciationLinesResponse]:
        """Get AssetDepreciationLines by primary key."""
        db_obj = self.db.query(AssetDepreciationLines).filter(AssetDepreciationLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetDepreciationLines not found")
        return AssetDepreciationLinesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> AssetDepreciationLinesListResponse:
        """List AssetDepreciationLines records with pagination and filtering."""
        query = self.db.query(AssetDepreciationLines)
        if company_id and hasattr(AssetDepreciationLines, "company_id"):
            query = query.filter(AssetDepreciationLines.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(AssetDepreciationLines, key) and value is not None:
                    query = query.filter(getattr(AssetDepreciationLines, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(AssetDepreciationLines, order_by, AssetDepreciationLines.created_at)))
        else:
            query = query.order_by(getattr(AssetDepreciationLines, order_by, AssetDepreciationLines.created_at))
        items = query.offset(skip).limit(limit).all()
        return AssetDepreciationLinesListResponse(
            items=[AssetDepreciationLinesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: AssetDepreciationLinesUpdate,
               updated_by: Optional[UUID] = None) -> AssetDepreciationLinesResponse:
        """Update an existing AssetDepreciationLines record."""
        db_obj = self.db.query(AssetDepreciationLines).filter(AssetDepreciationLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetDepreciationLines not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return AssetDepreciationLinesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a AssetDepreciationLines record. Soft delete by default."""
        db_obj = self.db.query(AssetDepreciationLines).filter(AssetDepreciationLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetDepreciationLines not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[AssetDepreciationLinesResponse]:
        """Search AssetDepreciationLines by name/code fields."""
        query = self.db.query(AssetDepreciationLines)
        if company_id and hasattr(AssetDepreciationLines, "company_id"):
            query = query.filter(AssetDepreciationLines.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(AssetDepreciationLines, f)]
        if search_fields:
            conditions = [getattr(AssetDepreciationLines, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [AssetDepreciationLinesResponse.model_validate(i) for i in items]

class AssetDepreciationRunsService:
    """CRUD service for AssetDepreciationRuns."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: AssetDepreciationRunsCreate, created_by: Optional[UUID] = None) -> AssetDepreciationRunsResponse:
        """Create a new AssetDepreciationRuns record."""
        db_obj = AssetDepreciationRuns(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return AssetDepreciationRunsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[AssetDepreciationRunsResponse]:
        """Get AssetDepreciationRuns by primary key."""
        db_obj = self.db.query(AssetDepreciationRuns).filter(AssetDepreciationRuns.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetDepreciationRuns not found")
        return AssetDepreciationRunsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> AssetDepreciationRunsListResponse:
        """List AssetDepreciationRuns records with pagination and filtering."""
        query = self.db.query(AssetDepreciationRuns)
        if company_id and hasattr(AssetDepreciationRuns, "company_id"):
            query = query.filter(AssetDepreciationRuns.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(AssetDepreciationRuns, key) and value is not None:
                    query = query.filter(getattr(AssetDepreciationRuns, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(AssetDepreciationRuns, order_by, AssetDepreciationRuns.created_at)))
        else:
            query = query.order_by(getattr(AssetDepreciationRuns, order_by, AssetDepreciationRuns.created_at))
        items = query.offset(skip).limit(limit).all()
        return AssetDepreciationRunsListResponse(
            items=[AssetDepreciationRunsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: AssetDepreciationRunsUpdate,
               updated_by: Optional[UUID] = None) -> AssetDepreciationRunsResponse:
        """Update an existing AssetDepreciationRuns record."""
        db_obj = self.db.query(AssetDepreciationRuns).filter(AssetDepreciationRuns.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetDepreciationRuns not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return AssetDepreciationRunsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a AssetDepreciationRuns record. Soft delete by default."""
        db_obj = self.db.query(AssetDepreciationRuns).filter(AssetDepreciationRuns.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetDepreciationRuns not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[AssetDepreciationRunsResponse]:
        """Search AssetDepreciationRuns by name/code fields."""
        query = self.db.query(AssetDepreciationRuns)
        if company_id and hasattr(AssetDepreciationRuns, "company_id"):
            query = query.filter(AssetDepreciationRuns.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(AssetDepreciationRuns, f)]
        if search_fields:
            conditions = [getattr(AssetDepreciationRuns, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [AssetDepreciationRunsResponse.model_validate(i) for i in items]

class AssetMaintenanceService:
    """CRUD service for AssetMaintenance."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: AssetMaintenanceCreate, created_by: Optional[UUID] = None) -> AssetMaintenanceResponse:
        """Create a new AssetMaintenance record."""
        db_obj = AssetMaintenance(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return AssetMaintenanceResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[AssetMaintenanceResponse]:
        """Get AssetMaintenance by primary key."""
        db_obj = self.db.query(AssetMaintenance).filter(AssetMaintenance.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetMaintenance not found")
        return AssetMaintenanceResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> AssetMaintenanceListResponse:
        """List AssetMaintenance records with pagination and filtering."""
        query = self.db.query(AssetMaintenance)
        if company_id and hasattr(AssetMaintenance, "company_id"):
            query = query.filter(AssetMaintenance.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(AssetMaintenance, key) and value is not None:
                    query = query.filter(getattr(AssetMaintenance, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(AssetMaintenance, order_by, AssetMaintenance.created_at)))
        else:
            query = query.order_by(getattr(AssetMaintenance, order_by, AssetMaintenance.created_at))
        items = query.offset(skip).limit(limit).all()
        return AssetMaintenanceListResponse(
            items=[AssetMaintenanceResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: AssetMaintenanceUpdate,
               updated_by: Optional[UUID] = None) -> AssetMaintenanceResponse:
        """Update an existing AssetMaintenance record."""
        db_obj = self.db.query(AssetMaintenance).filter(AssetMaintenance.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetMaintenance not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return AssetMaintenanceResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a AssetMaintenance record. Soft delete by default."""
        db_obj = self.db.query(AssetMaintenance).filter(AssetMaintenance.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AssetMaintenance not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[AssetMaintenanceResponse]:
        """Search AssetMaintenance by name/code fields."""
        query = self.db.query(AssetMaintenance)
        if company_id and hasattr(AssetMaintenance, "company_id"):
            query = query.filter(AssetMaintenance.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(AssetMaintenance, f)]
        if search_fields:
            conditions = [getattr(AssetMaintenance, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [AssetMaintenanceResponse.model_validate(i) for i in items]

class FixedAssetsService:
    """CRUD service for FixedAssets."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: FixedAssetsCreate, created_by: Optional[UUID] = None) -> FixedAssetsResponse:
        """Create a new FixedAssets record."""
        db_obj = FixedAssets(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return FixedAssetsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[FixedAssetsResponse]:
        """Get FixedAssets by primary key."""
        db_obj = self.db.query(FixedAssets).filter(FixedAssets.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="FixedAssets not found")
        return FixedAssetsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> FixedAssetsListResponse:
        """List FixedAssets records with pagination and filtering."""
        query = self.db.query(FixedAssets)
        if company_id and hasattr(FixedAssets, "company_id"):
            query = query.filter(FixedAssets.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(FixedAssets, key) and value is not None:
                    query = query.filter(getattr(FixedAssets, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(FixedAssets, order_by, FixedAssets.created_at)))
        else:
            query = query.order_by(getattr(FixedAssets, order_by, FixedAssets.created_at))
        items = query.offset(skip).limit(limit).all()
        return FixedAssetsListResponse(
            items=[FixedAssetsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: FixedAssetsUpdate,
               updated_by: Optional[UUID] = None) -> FixedAssetsResponse:
        """Update an existing FixedAssets record."""
        db_obj = self.db.query(FixedAssets).filter(FixedAssets.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="FixedAssets not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return FixedAssetsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a FixedAssets record. Soft delete by default."""
        db_obj = self.db.query(FixedAssets).filter(FixedAssets.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="FixedAssets not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[FixedAssetsResponse]:
        """Search FixedAssets by name/code fields."""
        query = self.db.query(FixedAssets)
        if company_id and hasattr(FixedAssets, "company_id"):
            query = query.filter(FixedAssets.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(FixedAssets, f)]
        if search_fields:
            conditions = [getattr(FixedAssets, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [FixedAssetsResponse.model_validate(i) for i in items]
