"""
Integration Module — CRUD Services
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.604816
Full CRUD with audit trail, soft delete, and business validations.
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID
from datetime import datetime
from decimal import Decimal

from sqlalchemy.orm import Session, joinedload
from sqlalchemy import and_, or_, desc, func
from fastapi import HTTPException, status
import uuid

from .integration_models import *
from .integration_schemas import *

class AuditLogService:
    """CRUD service for AuditLog."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: AuditLogCreate, created_by: Optional[UUID] = None) -> AuditLogResponse:
        """Create a new AuditLog record."""
        db_obj = AuditLog(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return AuditLogResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[AuditLogResponse]:
        """Get AuditLog by primary key."""
        db_obj = self.db.query(AuditLog).filter(AuditLog.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AuditLog not found")
        return AuditLogResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> AuditLogListResponse:
        """List AuditLog records with pagination and filtering."""
        query = self.db.query(AuditLog)
        if company_id and hasattr(AuditLog, "company_id"):
            query = query.filter(AuditLog.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(AuditLog, key) and value is not None:
                    query = query.filter(getattr(AuditLog, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(AuditLog, order_by, AuditLog.created_at)))
        else:
            query = query.order_by(getattr(AuditLog, order_by, AuditLog.created_at))
        items = query.offset(skip).limit(limit).all()
        return AuditLogListResponse(
            items=[AuditLogResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: AuditLogUpdate,
               updated_by: Optional[UUID] = None) -> AuditLogResponse:
        """Update an existing AuditLog record."""
        db_obj = self.db.query(AuditLog).filter(AuditLog.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AuditLog not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return AuditLogResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a AuditLog record. Soft delete by default."""
        db_obj = self.db.query(AuditLog).filter(AuditLog.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="AuditLog not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[AuditLogResponse]:
        """Search AuditLog by name/code fields."""
        query = self.db.query(AuditLog)
        if company_id and hasattr(AuditLog, "company_id"):
            query = query.filter(AuditLog.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(AuditLog, f)]
        if search_fields:
            conditions = [getattr(AuditLog, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [AuditLogResponse.model_validate(i) for i in items]

class IntegrationEndpointsService:
    """CRUD service for IntegrationEndpoints."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: IntegrationEndpointsCreate, created_by: Optional[UUID] = None) -> IntegrationEndpointsResponse:
        """Create a new IntegrationEndpoints record."""
        db_obj = IntegrationEndpoints(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return IntegrationEndpointsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[IntegrationEndpointsResponse]:
        """Get IntegrationEndpoints by primary key."""
        db_obj = self.db.query(IntegrationEndpoints).filter(IntegrationEndpoints.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="IntegrationEndpoints not found")
        return IntegrationEndpointsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> IntegrationEndpointsListResponse:
        """List IntegrationEndpoints records with pagination and filtering."""
        query = self.db.query(IntegrationEndpoints)
        if company_id and hasattr(IntegrationEndpoints, "company_id"):
            query = query.filter(IntegrationEndpoints.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(IntegrationEndpoints, key) and value is not None:
                    query = query.filter(getattr(IntegrationEndpoints, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(IntegrationEndpoints, order_by, IntegrationEndpoints.created_at)))
        else:
            query = query.order_by(getattr(IntegrationEndpoints, order_by, IntegrationEndpoints.created_at))
        items = query.offset(skip).limit(limit).all()
        return IntegrationEndpointsListResponse(
            items=[IntegrationEndpointsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: IntegrationEndpointsUpdate,
               updated_by: Optional[UUID] = None) -> IntegrationEndpointsResponse:
        """Update an existing IntegrationEndpoints record."""
        db_obj = self.db.query(IntegrationEndpoints).filter(IntegrationEndpoints.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="IntegrationEndpoints not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return IntegrationEndpointsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a IntegrationEndpoints record. Soft delete by default."""
        db_obj = self.db.query(IntegrationEndpoints).filter(IntegrationEndpoints.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="IntegrationEndpoints not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[IntegrationEndpointsResponse]:
        """Search IntegrationEndpoints by name/code fields."""
        query = self.db.query(IntegrationEndpoints)
        if company_id and hasattr(IntegrationEndpoints, "company_id"):
            query = query.filter(IntegrationEndpoints.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(IntegrationEndpoints, f)]
        if search_fields:
            conditions = [getattr(IntegrationEndpoints, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [IntegrationEndpointsResponse.model_validate(i) for i in items]

class IntegrationLogsService:
    """CRUD service for IntegrationLogs."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: IntegrationLogsCreate, created_by: Optional[UUID] = None) -> IntegrationLogsResponse:
        """Create a new IntegrationLogs record."""
        db_obj = IntegrationLogs(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return IntegrationLogsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[IntegrationLogsResponse]:
        """Get IntegrationLogs by primary key."""
        db_obj = self.db.query(IntegrationLogs).filter(IntegrationLogs.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="IntegrationLogs not found")
        return IntegrationLogsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> IntegrationLogsListResponse:
        """List IntegrationLogs records with pagination and filtering."""
        query = self.db.query(IntegrationLogs)
        if company_id and hasattr(IntegrationLogs, "company_id"):
            query = query.filter(IntegrationLogs.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(IntegrationLogs, key) and value is not None:
                    query = query.filter(getattr(IntegrationLogs, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(IntegrationLogs, order_by, IntegrationLogs.created_at)))
        else:
            query = query.order_by(getattr(IntegrationLogs, order_by, IntegrationLogs.created_at))
        items = query.offset(skip).limit(limit).all()
        return IntegrationLogsListResponse(
            items=[IntegrationLogsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: IntegrationLogsUpdate,
               updated_by: Optional[UUID] = None) -> IntegrationLogsResponse:
        """Update an existing IntegrationLogs record."""
        db_obj = self.db.query(IntegrationLogs).filter(IntegrationLogs.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="IntegrationLogs not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return IntegrationLogsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a IntegrationLogs record. Soft delete by default."""
        db_obj = self.db.query(IntegrationLogs).filter(IntegrationLogs.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="IntegrationLogs not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[IntegrationLogsResponse]:
        """Search IntegrationLogs by name/code fields."""
        query = self.db.query(IntegrationLogs)
        if company_id and hasattr(IntegrationLogs, "company_id"):
            query = query.filter(IntegrationLogs.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(IntegrationLogs, f)]
        if search_fields:
            conditions = [getattr(IntegrationLogs, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [IntegrationLogsResponse.model_validate(i) for i in items]

class WfAuditService:
    """CRUD service for WfAudit."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: WfAuditCreate, created_by: Optional[UUID] = None) -> WfAuditResponse:
        """Create a new WfAudit record."""
        db_obj = WfAudit(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return WfAuditResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[WfAuditResponse]:
        """Get WfAudit by primary key."""
        db_obj = self.db.query(WfAudit).filter(WfAudit.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfAudit not found")
        return WfAuditResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> WfAuditListResponse:
        """List WfAudit records with pagination and filtering."""
        query = self.db.query(WfAudit)
        if company_id and hasattr(WfAudit, "company_id"):
            query = query.filter(WfAudit.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(WfAudit, key) and value is not None:
                    query = query.filter(getattr(WfAudit, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(WfAudit, order_by, WfAudit.created_at)))
        else:
            query = query.order_by(getattr(WfAudit, order_by, WfAudit.created_at))
        items = query.offset(skip).limit(limit).all()
        return WfAuditListResponse(
            items=[WfAuditResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: WfAuditUpdate,
               updated_by: Optional[UUID] = None) -> WfAuditResponse:
        """Update an existing WfAudit record."""
        db_obj = self.db.query(WfAudit).filter(WfAudit.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfAudit not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return WfAuditResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a WfAudit record. Soft delete by default."""
        db_obj = self.db.query(WfAudit).filter(WfAudit.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfAudit not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[WfAuditResponse]:
        """Search WfAudit by name/code fields."""
        query = self.db.query(WfAudit)
        if company_id and hasattr(WfAudit, "company_id"):
            query = query.filter(WfAudit.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(WfAudit, f)]
        if search_fields:
            conditions = [getattr(WfAudit, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [WfAuditResponse.model_validate(i) for i in items]

class WfDefinitionsService:
    """CRUD service for WfDefinitions."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: WfDefinitionsCreate, created_by: Optional[UUID] = None) -> WfDefinitionsResponse:
        """Create a new WfDefinitions record."""
        db_obj = WfDefinitions(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return WfDefinitionsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[WfDefinitionsResponse]:
        """Get WfDefinitions by primary key."""
        db_obj = self.db.query(WfDefinitions).filter(WfDefinitions.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfDefinitions not found")
        return WfDefinitionsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> WfDefinitionsListResponse:
        """List WfDefinitions records with pagination and filtering."""
        query = self.db.query(WfDefinitions)
        if company_id and hasattr(WfDefinitions, "company_id"):
            query = query.filter(WfDefinitions.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(WfDefinitions, key) and value is not None:
                    query = query.filter(getattr(WfDefinitions, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(WfDefinitions, order_by, WfDefinitions.created_at)))
        else:
            query = query.order_by(getattr(WfDefinitions, order_by, WfDefinitions.created_at))
        items = query.offset(skip).limit(limit).all()
        return WfDefinitionsListResponse(
            items=[WfDefinitionsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: WfDefinitionsUpdate,
               updated_by: Optional[UUID] = None) -> WfDefinitionsResponse:
        """Update an existing WfDefinitions record."""
        db_obj = self.db.query(WfDefinitions).filter(WfDefinitions.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfDefinitions not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return WfDefinitionsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a WfDefinitions record. Soft delete by default."""
        db_obj = self.db.query(WfDefinitions).filter(WfDefinitions.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfDefinitions not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[WfDefinitionsResponse]:
        """Search WfDefinitions by name/code fields."""
        query = self.db.query(WfDefinitions)
        if company_id and hasattr(WfDefinitions, "company_id"):
            query = query.filter(WfDefinitions.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(WfDefinitions, f)]
        if search_fields:
            conditions = [getattr(WfDefinitions, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [WfDefinitionsResponse.model_validate(i) for i in items]

class WfInstancesService:
    """CRUD service for WfInstances."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: WfInstancesCreate, created_by: Optional[UUID] = None) -> WfInstancesResponse:
        """Create a new WfInstances record."""
        db_obj = WfInstances(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return WfInstancesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[WfInstancesResponse]:
        """Get WfInstances by primary key."""
        db_obj = self.db.query(WfInstances).filter(WfInstances.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfInstances not found")
        return WfInstancesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> WfInstancesListResponse:
        """List WfInstances records with pagination and filtering."""
        query = self.db.query(WfInstances)
        if company_id and hasattr(WfInstances, "company_id"):
            query = query.filter(WfInstances.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(WfInstances, key) and value is not None:
                    query = query.filter(getattr(WfInstances, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(WfInstances, order_by, WfInstances.created_at)))
        else:
            query = query.order_by(getattr(WfInstances, order_by, WfInstances.created_at))
        items = query.offset(skip).limit(limit).all()
        return WfInstancesListResponse(
            items=[WfInstancesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: WfInstancesUpdate,
               updated_by: Optional[UUID] = None) -> WfInstancesResponse:
        """Update an existing WfInstances record."""
        db_obj = self.db.query(WfInstances).filter(WfInstances.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfInstances not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return WfInstancesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a WfInstances record. Soft delete by default."""
        db_obj = self.db.query(WfInstances).filter(WfInstances.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfInstances not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[WfInstancesResponse]:
        """Search WfInstances by name/code fields."""
        query = self.db.query(WfInstances)
        if company_id and hasattr(WfInstances, "company_id"):
            query = query.filter(WfInstances.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(WfInstances, f)]
        if search_fields:
            conditions = [getattr(WfInstances, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [WfInstancesResponse.model_validate(i) for i in items]

class WfStatesService:
    """CRUD service for WfStates."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: WfStatesCreate, created_by: Optional[UUID] = None) -> WfStatesResponse:
        """Create a new WfStates record."""
        db_obj = WfStates(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return WfStatesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[WfStatesResponse]:
        """Get WfStates by primary key."""
        db_obj = self.db.query(WfStates).filter(WfStates.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfStates not found")
        return WfStatesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> WfStatesListResponse:
        """List WfStates records with pagination and filtering."""
        query = self.db.query(WfStates)
        if company_id and hasattr(WfStates, "company_id"):
            query = query.filter(WfStates.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(WfStates, key) and value is not None:
                    query = query.filter(getattr(WfStates, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(WfStates, order_by, WfStates.created_at)))
        else:
            query = query.order_by(getattr(WfStates, order_by, WfStates.created_at))
        items = query.offset(skip).limit(limit).all()
        return WfStatesListResponse(
            items=[WfStatesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: WfStatesUpdate,
               updated_by: Optional[UUID] = None) -> WfStatesResponse:
        """Update an existing WfStates record."""
        db_obj = self.db.query(WfStates).filter(WfStates.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfStates not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return WfStatesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a WfStates record. Soft delete by default."""
        db_obj = self.db.query(WfStates).filter(WfStates.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfStates not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[WfStatesResponse]:
        """Search WfStates by name/code fields."""
        query = self.db.query(WfStates)
        if company_id and hasattr(WfStates, "company_id"):
            query = query.filter(WfStates.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(WfStates, f)]
        if search_fields:
            conditions = [getattr(WfStates, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [WfStatesResponse.model_validate(i) for i in items]

class WfTasksService:
    """CRUD service for WfTasks."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: WfTasksCreate, created_by: Optional[UUID] = None) -> WfTasksResponse:
        """Create a new WfTasks record."""
        db_obj = WfTasks(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return WfTasksResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[WfTasksResponse]:
        """Get WfTasks by primary key."""
        db_obj = self.db.query(WfTasks).filter(WfTasks.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfTasks not found")
        return WfTasksResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> WfTasksListResponse:
        """List WfTasks records with pagination and filtering."""
        query = self.db.query(WfTasks)
        if company_id and hasattr(WfTasks, "company_id"):
            query = query.filter(WfTasks.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(WfTasks, key) and value is not None:
                    query = query.filter(getattr(WfTasks, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(WfTasks, order_by, WfTasks.created_at)))
        else:
            query = query.order_by(getattr(WfTasks, order_by, WfTasks.created_at))
        items = query.offset(skip).limit(limit).all()
        return WfTasksListResponse(
            items=[WfTasksResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: WfTasksUpdate,
               updated_by: Optional[UUID] = None) -> WfTasksResponse:
        """Update an existing WfTasks record."""
        db_obj = self.db.query(WfTasks).filter(WfTasks.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfTasks not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return WfTasksResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a WfTasks record. Soft delete by default."""
        db_obj = self.db.query(WfTasks).filter(WfTasks.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfTasks not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[WfTasksResponse]:
        """Search WfTasks by name/code fields."""
        query = self.db.query(WfTasks)
        if company_id and hasattr(WfTasks, "company_id"):
            query = query.filter(WfTasks.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(WfTasks, f)]
        if search_fields:
            conditions = [getattr(WfTasks, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [WfTasksResponse.model_validate(i) for i in items]

class WfTransitionsService:
    """CRUD service for WfTransitions."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: WfTransitionsCreate, created_by: Optional[UUID] = None) -> WfTransitionsResponse:
        """Create a new WfTransitions record."""
        db_obj = WfTransitions(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return WfTransitionsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[WfTransitionsResponse]:
        """Get WfTransitions by primary key."""
        db_obj = self.db.query(WfTransitions).filter(WfTransitions.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfTransitions not found")
        return WfTransitionsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> WfTransitionsListResponse:
        """List WfTransitions records with pagination and filtering."""
        query = self.db.query(WfTransitions)
        if company_id and hasattr(WfTransitions, "company_id"):
            query = query.filter(WfTransitions.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(WfTransitions, key) and value is not None:
                    query = query.filter(getattr(WfTransitions, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(WfTransitions, order_by, WfTransitions.created_at)))
        else:
            query = query.order_by(getattr(WfTransitions, order_by, WfTransitions.created_at))
        items = query.offset(skip).limit(limit).all()
        return WfTransitionsListResponse(
            items=[WfTransitionsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: WfTransitionsUpdate,
               updated_by: Optional[UUID] = None) -> WfTransitionsResponse:
        """Update an existing WfTransitions record."""
        db_obj = self.db.query(WfTransitions).filter(WfTransitions.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfTransitions not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return WfTransitionsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a WfTransitions record. Soft delete by default."""
        db_obj = self.db.query(WfTransitions).filter(WfTransitions.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="WfTransitions not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[WfTransitionsResponse]:
        """Search WfTransitions by name/code fields."""
        query = self.db.query(WfTransitions)
        if company_id and hasattr(WfTransitions, "company_id"):
            query = query.filter(WfTransitions.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(WfTransitions, f)]
        if search_fields:
            conditions = [getattr(WfTransitions, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [WfTransitionsResponse.model_validate(i) for i in items]
