"""
Integration Module — Pydantic v2 Schemas
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.588656
Provides Create, Update, Response, and ListResponse schemas per table.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional, Any, Dict
from uuid import UUID

from pydantic import BaseModel, Field, ConfigDict, model_validator, constr, condecimal

# Common response fields mixin
class AuditFields(BaseModel):
    """Audit trail fields included in all responses."""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    created_by: Optional[UUID] = None
    updated_by: Optional[UUID] = None
    is_active: Optional[bool] = True
    company_id: Optional[UUID] = None

class AuditLogCreate(BaseModel):
    """Schema for creating new AuditLog."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    table_name: str
    record_id: Optional[UUID] = None
    operation: str
    old_data: Optional[str] = None
    new_data: Optional[str] = None
    changed_fields: Optional[str] = None
    performed_by: Optional[UUID] = None
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None
    metadata: Optional[str] = None

class AuditLogUpdate(BaseModel):
    """Schema for updating existing AuditLog."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    table_name: Optional[str] = None
    record_id: Optional[UUID] = None
    operation: Optional[str] = None
    old_data: Optional[str] = None
    new_data: Optional[str] = None
    changed_fields: Optional[str] = None
    performed_by: Optional[UUID] = None
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None
    metadata: Optional[str] = None

class AuditLogResponse(AuditFields):
    """Response schema for AuditLog (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    table_name: str
    record_id: Optional[UUID] = None
    operation: str
    old_data: Optional[str] = None
    new_data: Optional[str] = None
    changed_fields: Optional[str] = None
    performed_by: Optional[UUID] = None
    ip_address: Optional[str] = None
    user_agent: Optional[str] = None
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None

class AuditLogListResponse(BaseModel):
    """Paginated list response for AuditLog."""
    items: List[AuditLogResponse]
    total: int
    skip: int = 0
    limit: int = 100

class IntegrationEndpointsCreate(BaseModel):
    """Schema for creating new IntegrationEndpoints."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    name: str
    endpoint_type: str
    url: Optional[str] = None
    auth_type: Optional[str] = None
    auth_config: Optional[str] = None
    event_triggers: Optional[str] = None
    retry_count: Optional[int] = None
    timeout_seconds: Optional[int] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None

class IntegrationEndpointsUpdate(BaseModel):
    """Schema for updating existing IntegrationEndpoints."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    name: Optional[str] = None
    endpoint_type: Optional[str] = None
    url: Optional[str] = None
    auth_type: Optional[str] = None
    auth_config: Optional[str] = None
    event_triggers: Optional[str] = None
    retry_count: Optional[int] = None
    timeout_seconds: Optional[int] = None
    is_active: Optional[bool] = None
    metadata: Optional[str] = None

class IntegrationEndpointsResponse(AuditFields):
    """Response schema for IntegrationEndpoints (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    name: str
    endpoint_type: str
    url: Optional[str] = None
    auth_type: Optional[str] = None
    auth_config: Optional[str] = None
    event_triggers: Optional[str] = None
    retry_count: Optional[int] = None
    timeout_seconds: Optional[int] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None

class IntegrationEndpointsListResponse(BaseModel):
    """Paginated list response for IntegrationEndpoints."""
    items: List[IntegrationEndpointsResponse]
    total: int
    skip: int = 0
    limit: int = 100

class IntegrationLogsCreate(BaseModel):
    """Schema for creating new IntegrationLogs."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    endpoint_id: UUID
    direction: str
    event_type: Optional[str] = None
    payload_hash: Optional[str] = None
    request_headers: Optional[str] = None
    response_status: Optional[int] = None
    response_body: Optional[str] = None
    status: str
    attempts: int
    last_error: Optional[str] = None
    processed_at: Optional[datetime] = None

class IntegrationLogsUpdate(BaseModel):
    """Schema for updating existing IntegrationLogs."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    endpoint_id: Optional[UUID] = None
    direction: Optional[str] = None
    event_type: Optional[str] = None
    payload_hash: Optional[str] = None
    request_headers: Optional[str] = None
    response_status: Optional[int] = None
    response_body: Optional[str] = None
    status: Optional[str] = None
    attempts: Optional[int] = None
    last_error: Optional[str] = None
    processed_at: Optional[datetime] = None

class IntegrationLogsResponse(AuditFields):
    """Response schema for IntegrationLogs (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    endpoint_id: UUID
    direction: str
    event_type: Optional[str] = None
    payload_hash: Optional[str] = None
    request_headers: Optional[str] = None
    response_status: Optional[int] = None
    response_body: Optional[str] = None
    status: str
    attempts: int
    last_error: Optional[str] = None
    processed_at: Optional[datetime] = None
    created_at: Optional[datetime] = None

class IntegrationLogsListResponse(BaseModel):
    """Paginated list response for IntegrationLogs."""
    items: List[IntegrationLogsResponse]
    total: int
    skip: int = 0
    limit: int = 100

class WfAuditCreate(BaseModel):
    """Schema for creating new WfAudit."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    wf_instance_id: Optional[UUID] = None
    wf_definition_id: Optional[UUID] = None
    event_type: str
    from_state_id: Optional[UUID] = None
    to_state_id: Optional[UUID] = None
    transition_id: Optional[UUID] = None
    task_id: Optional[UUID] = None
    actor_id: Optional[UUID] = None
    action: Optional[str] = None
    details_json: Optional[str] = None
    occurred_at: datetime
    metadata: Optional[str] = None

class WfAuditUpdate(BaseModel):
    """Schema for updating existing WfAudit."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    wf_instance_id: Optional[UUID] = None
    wf_definition_id: Optional[UUID] = None
    event_type: Optional[str] = None
    from_state_id: Optional[UUID] = None
    to_state_id: Optional[UUID] = None
    transition_id: Optional[UUID] = None
    task_id: Optional[UUID] = None
    actor_id: Optional[UUID] = None
    action: Optional[str] = None
    details_json: Optional[str] = None
    occurred_at: Optional[datetime] = None
    metadata: Optional[str] = None

class WfAuditResponse(AuditFields):
    """Response schema for WfAudit (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    wf_instance_id: Optional[UUID] = None
    wf_definition_id: Optional[UUID] = None
    event_type: str
    from_state_id: Optional[UUID] = None
    to_state_id: Optional[UUID] = None
    transition_id: Optional[UUID] = None
    task_id: Optional[UUID] = None
    actor_id: Optional[UUID] = None
    action: Optional[str] = None
    details_json: Optional[str] = None
    occurred_at: datetime
    created_at: Optional[datetime] = None
    metadata: Optional[str] = None

class WfAuditListResponse(BaseModel):
    """Paginated list response for WfAudit."""
    items: List[WfAuditResponse]
    total: int
    skip: int = 0
    limit: int = 100

class WfDefinitionsCreate(BaseModel):
    """Schema for creating new WfDefinitions."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    wf_code: str
    wf_name: str
    description: Optional[str] = None
    bpmn_xml: Optional[str] = None
    wf_version: int
    category: Optional[str] = None
    target_entity: Optional[str] = None
    initiator_roles: Optional[str] = None
    timeout_minutes: Optional[int] = None
    sla_warning_minutes: Optional[int] = None
    is_parrallel_execution: bool
    config_json: Optional[str] = None
    status: str
    metadata: Optional[str] = None

class WfDefinitionsUpdate(BaseModel):
    """Schema for updating existing WfDefinitions."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    wf_code: Optional[str] = None
    wf_name: Optional[str] = None
    description: Optional[str] = None
    bpmn_xml: Optional[str] = None
    wf_version: Optional[int] = None
    category: Optional[str] = None
    target_entity: Optional[str] = None
    initiator_roles: Optional[str] = None
    timeout_minutes: Optional[int] = None
    sla_warning_minutes: Optional[int] = None
    is_parrallel_execution: Optional[bool] = None
    config_json: Optional[str] = None
    status: Optional[str] = None
    metadata: Optional[str] = None

class WfDefinitionsResponse(AuditFields):
    """Response schema for WfDefinitions (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    wf_code: str
    wf_name: str
    description: Optional[str] = None
    bpmn_xml: Optional[str] = None
    wf_version: int
    category: Optional[str] = None
    target_entity: Optional[str] = None
    initiator_roles: Optional[str] = None
    timeout_minutes: Optional[int] = None
    sla_warning_minutes: Optional[int] = None
    is_parrallel_execution: bool
    config_json: Optional[str] = None
    status: str
    created_by: Optional[UUID] = None
    updated_by: Optional[UUID] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    metadata: Optional[str] = None

class WfDefinitionsListResponse(BaseModel):
    """Paginated list response for WfDefinitions."""
    items: List[WfDefinitionsResponse]
    total: int
    skip: int = 0
    limit: int = 100

class WfInstancesCreate(BaseModel):
    """Schema for creating new WfInstances."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    wf_definition_id: UUID
    current_state_id: Optional[UUID] = None
    entity_type: str
    entity_id: UUID
    initiator_id: Optional[UUID] = None
    initiator_notes: Optional[str] = None
    priority: str
    variables_json: Optional[str] = None
    status: str
    sla_deadline: Optional[datetime] = None
    sla_breached_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    metadata: Optional[str] = None

class WfInstancesUpdate(BaseModel):
    """Schema for updating existing WfInstances."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    wf_definition_id: Optional[UUID] = None
    current_state_id: Optional[UUID] = None
    entity_type: Optional[str] = None
    entity_id: Optional[UUID] = None
    initiator_id: Optional[UUID] = None
    initiator_notes: Optional[str] = None
    priority: Optional[str] = None
    variables_json: Optional[str] = None
    status: Optional[str] = None
    sla_deadline: Optional[datetime] = None
    sla_breached_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    metadata: Optional[str] = None

class WfInstancesResponse(AuditFields):
    """Response schema for WfInstances (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    wf_definition_id: UUID
    current_state_id: Optional[UUID] = None
    entity_type: str
    entity_id: UUID
    initiator_id: Optional[UUID] = None
    initiator_notes: Optional[str] = None
    priority: str
    variables_json: Optional[str] = None
    status: str
    sla_deadline: Optional[datetime] = None
    sla_breached_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    metadata: Optional[str] = None

class WfInstancesListResponse(BaseModel):
    """Paginated list response for WfInstances."""
    items: List[WfInstancesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class WfStatesCreate(BaseModel):
    """Schema for creating new WfStates."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    wf_definition_id: UUID
    state_code: str
    state_name: str
    state_type: str
    is_initial: bool
    is_final: bool
    assignee_type: Optional[str] = None
    assignee_value: Optional[str] = None
    timeout_minutes: Optional[int] = None
    escalation_state_id: Optional[UUID] = None
    ui_form_key: Optional[str] = None
    config_json: Optional[str] = None
    sort_order: int
    metadata: Optional[str] = None

class WfStatesUpdate(BaseModel):
    """Schema for updating existing WfStates."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    wf_definition_id: Optional[UUID] = None
    state_code: Optional[str] = None
    state_name: Optional[str] = None
    state_type: Optional[str] = None
    is_initial: Optional[bool] = None
    is_final: Optional[bool] = None
    assignee_type: Optional[str] = None
    assignee_value: Optional[str] = None
    timeout_minutes: Optional[int] = None
    escalation_state_id: Optional[UUID] = None
    ui_form_key: Optional[str] = None
    config_json: Optional[str] = None
    sort_order: Optional[int] = None
    metadata: Optional[str] = None

class WfStatesResponse(AuditFields):
    """Response schema for WfStates (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    wf_definition_id: UUID
    state_code: str
    state_name: str
    state_type: str
    is_initial: bool
    is_final: bool
    assignee_type: Optional[str] = None
    assignee_value: Optional[str] = None
    timeout_minutes: Optional[int] = None
    escalation_state_id: Optional[UUID] = None
    ui_form_key: Optional[str] = None
    config_json: Optional[str] = None
    sort_order: int
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    metadata: Optional[str] = None

class WfStatesListResponse(BaseModel):
    """Paginated list response for WfStates."""
    items: List[WfStatesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class WfTasksCreate(BaseModel):
    """Schema for creating new WfTasks."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    wf_instance_id: UUID
    state_id: UUID
    task_name: str
    description: Optional[str] = None
    assigned_to: Optional[UUID] = None
    assigned_role: Optional[str] = None
    due_date: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    completed_by: Optional[UUID] = None
    decision: Optional[str] = None
    comments: Optional[str] = None
    outcome_json: Optional[str] = None
    status: str
    metadata: Optional[str] = None

class WfTasksUpdate(BaseModel):
    """Schema for updating existing WfTasks."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    wf_instance_id: Optional[UUID] = None
    state_id: Optional[UUID] = None
    task_name: Optional[str] = None
    description: Optional[str] = None
    assigned_to: Optional[UUID] = None
    assigned_role: Optional[str] = None
    due_date: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    completed_by: Optional[UUID] = None
    decision: Optional[str] = None
    comments: Optional[str] = None
    outcome_json: Optional[str] = None
    status: Optional[str] = None
    metadata: Optional[str] = None

class WfTasksResponse(AuditFields):
    """Response schema for WfTasks (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    wf_instance_id: UUID
    state_id: UUID
    task_name: str
    description: Optional[str] = None
    assigned_to: Optional[UUID] = None
    assigned_role: Optional[str] = None
    due_date: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    completed_by: Optional[UUID] = None
    decision: Optional[str] = None
    comments: Optional[str] = None
    outcome_json: Optional[str] = None
    status: str
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    metadata: Optional[str] = None

class WfTasksListResponse(BaseModel):
    """Paginated list response for WfTasks."""
    items: List[WfTasksResponse]
    total: int
    skip: int = 0
    limit: int = 100

class WfTransitionsCreate(BaseModel):
    """Schema for creating new WfTransitions."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    wf_definition_id: UUID
    from_state_id: UUID
    to_state_id: UUID
    transition_code: str
    transition_name: Optional[str] = None
    condition_expression: Optional[str] = None
    condition_type: Optional[str] = None
    required_roles: Optional[str] = None
    is_auto_transition: bool
    sort_order: int
    metadata: Optional[str] = None

class WfTransitionsUpdate(BaseModel):
    """Schema for updating existing WfTransitions."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    wf_definition_id: Optional[UUID] = None
    from_state_id: Optional[UUID] = None
    to_state_id: Optional[UUID] = None
    transition_code: Optional[str] = None
    transition_name: Optional[str] = None
    condition_expression: Optional[str] = None
    condition_type: Optional[str] = None
    required_roles: Optional[str] = None
    is_auto_transition: Optional[bool] = None
    sort_order: Optional[int] = None
    metadata: Optional[str] = None

class WfTransitionsResponse(AuditFields):
    """Response schema for WfTransitions (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    wf_definition_id: UUID
    from_state_id: UUID
    to_state_id: UUID
    transition_code: str
    transition_name: Optional[str] = None
    condition_expression: Optional[str] = None
    condition_type: Optional[str] = None
    required_roles: Optional[str] = None
    is_auto_transition: bool
    sort_order: int
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    metadata: Optional[str] = None

class WfTransitionsListResponse(BaseModel):
    """Paginated list response for WfTransitions."""
    items: List[WfTransitionsResponse]
    total: int
    skip: int = 0
    limit: int = 100
