"""
Integration Module — FastAPI Sub-App
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.606835
Mounted at /api/v1/int in Bio-ERP main.py
"""
from __future__ import annotations

from fastapi import FastAPI

from .integration_router import router as integration_router

def create_integration_app() -> FastAPI:
    """Factory function to create the integration sub-application."""
    app = FastAPI(
        title="Integration Module",
        description="ERP Integration module — 9 tables",
        version="3.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json"
    )
    app.include_router(integration_router)

    @app.get("/health")
    async def health_check():
        return {
            "status": "healthy",
            "module": "integration",
            "version": "3.0.0",
            "tables": 9,
            "database": "SQL Server 2022"
        }

    @app.get("/")
    async def root():
        return {
            "module": "integration",
            "version": "3.0.0",
            "endpoints": "/docs"
        }

    return app
