"""
New P1 Module — FastAPI Sub-App
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.944664
Mounted at /api/v1/p1 in Bio-ERP main.py
"""
from __future__ import annotations

from fastapi import FastAPI

from .new_p1_router import router as new_p1_router

def create_new_p1_app() -> FastAPI:
    """Factory function to create the new_p1 sub-application."""
    app = FastAPI(
        title="New P1 Module",
        description="ERP New P1 module — 74 tables",
        version="3.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json"
    )
    app.include_router(new_p1_router)

    @app.get("/health")
    async def health_check():
        return {
            "status": "healthy",
            "module": "new_p1",
            "version": "3.0.0",
            "tables": 74,
            "database": "SQL Server 2022"
        }

    @app.get("/")
    async def root():
        return {
            "module": "new_p1",
            "version": "3.0.0",
            "endpoints": "/docs"
        }

    return app
