"""
Ap Ar Module — SQLAlchemy ORM Models
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.308782
One model class per table with full relationship support.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional
from uuid import UUID
import uuid

from sqlalchemy import (
    Column, Integer, BigInteger, SmallInteger,
    Numeric, Float, Boolean,
    String, Text, Unicode, UnicodeText,
    DateTime, Date, Time, DateTime, LargeBinary,
    ForeignKey, ForeignKeyConstraint, UniqueConstraint,
    Index, CheckConstraint, PrimaryKeyConstraint,
    TIMESTAMP, JSON, Enum, VARBINARY
)
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER, MONEY, SMALLMONEY, NVARCHAR, NTEXT, IMAGE
from sqlalchemy.orm import relationship, backref, mapped_column, Mapped
from sqlalchemy.sql import func

from app.core.database_mssql import Base

# Module metadata
__module_code__ = "ap_ar-ebuild"
__tables__ = 6

class ExpenseClaimLines(Base):
    """ExpenseClaimLines — 11 columns, 3 FKs."""
    __tablename__ = "expense_claim_lines"

    # FK: account_id -> accounts.id
    # FK: claim_id -> expense_claims.id
    # FK: tax_code_id -> tax_codes.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    claim_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    expense_date: Mapped[date] = mapped_column(Date, nullable=False)
    category: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    description: Mapped[str] = mapped_column(Text)
    amount: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    currency: Mapped[str] = mapped_column(NVARCHAR(3))
    tax_code_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    account_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    receipt_url: Mapped[str] = mapped_column(Text)
    notes: Mapped[str] = mapped_column(Text)

    # account = relationship("Accounts", back_populates="expense_claim_liness")
    # claim = relationship("ExpenseClaims", back_populates="expense_claim_liness")
    # tax_code = relationship("TaxCodes", back_populates="expense_claim_liness")

class ExpenseClaims(Base):
    """ExpenseClaims — 12 columns, 4 FKs."""
    __tablename__ = "expense_claims"

    # FK: approved_by -> users.id
    # FK: company_id -> companies.id
    # FK: employee_id -> employees.id
    # FK: project_id -> projects.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    number: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    employee_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    project_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    claim_date: Mapped[date] = mapped_column(Date, nullable=False)
    total_amount: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    currency: Mapped[str] = mapped_column(NVARCHAR(3), nullable=False)
    status: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    approved_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # approved_by = relationship("Users", back_populates="expense_claimss")
    # company = relationship("Companies", back_populates="expense_claimss")
    # employee = relationship("Employees", back_populates="expense_claimss")
    # project = relationship("Projects", back_populates="expense_claimss")

class InvoiceLines(Base):
    """InvoiceLines — 11 columns, 4 FKs."""
    __tablename__ = "invoice_lines"

    # FK: account_id -> accounts.id
    # FK: invoice_id -> invoices.id
    # FK: item_id -> items.id
    # FK: tax_code_id -> tax_codes.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    invoice_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    item_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    unit_price: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    discount_pct: Mapped[Decimal] = mapped_column(Numeric(6, 4))
    tax_code_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    tax_amount: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    line_total: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    account_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)

    # account = relationship("Accounts", back_populates="invoice_liness")
    # invoice = relationship("Invoices", back_populates="invoice_liness")
    # item = relationship("Items", back_populates="invoice_liness")
    # tax_code = relationship("TaxCodes", back_populates="invoice_liness")

class Invoices(Base):
    """Invoices — 23 columns, 4 FKs."""
    __tablename__ = "invoices"

    # FK: company_id -> companies.id
    # FK: journal_entry_id -> journal_entries.id
    # FK: partner_id -> business_partners.id
    # FK: period_id -> fiscal_periods.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    number: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    invoice_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    partner_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    invoice_date: Mapped[date] = mapped_column(Date, nullable=False)
    due_date: Mapped[date] = mapped_column(Date)
    currency: Mapped[str] = mapped_column(NVARCHAR(3), nullable=False)
    fx_rate: Mapped[Decimal] = mapped_column(Numeric(18, 6))
    subtotal: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    discount_amount: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    tax_amount: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    total_amount: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    paid_amount: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    outstanding: Mapped[Decimal] = mapped_column(Numeric(19, 4))
    source_doc_type: Mapped[str] = mapped_column(NVARCHAR(255))
    source_doc_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    period_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    journal_entry_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    notes: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # company = relationship("Companies", back_populates="invoicess")
    # journal_entry = relationship("JournalEntries", back_populates="invoicess")
    # partner = relationship("BusinessPartners", back_populates="invoicess")
    # period = relationship("FiscalPeriods", back_populates="invoicess")

class PaymentAllocations(Base):
    """PaymentAllocations — 7 columns, 2 FKs."""
    __tablename__ = "payment_allocations"

    # FK: invoice_id -> invoices.id
    # FK: payment_id -> payments.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    payment_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    invoice_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    allocated_amount: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    allocation_date: Mapped[date] = mapped_column(Date, nullable=False)
    notes: Mapped[str] = mapped_column(Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # invoice = relationship("Invoices", back_populates="payment_allocationss")
    # payment = relationship("Payments", back_populates="payment_allocationss")

class Payments(Base):
    """Payments — 16 columns, 3 FKs."""
    __tablename__ = "payments"

    # FK: company_id -> companies.id
    # FK: journal_entry_id -> journal_entries.id
    # FK: partner_id -> business_partners.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    number: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    payment_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    partner_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    bank_account_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    payment_date: Mapped[date] = mapped_column(Date, nullable=False)
    currency: Mapped[str] = mapped_column(NVARCHAR(3), nullable=False)
    amount: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    payment_method: Mapped[str] = mapped_column(NVARCHAR(255))
    reference: Mapped[str] = mapped_column(NVARCHAR(255))
    journal_entry_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    notes: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # company = relationship("Companies", back_populates="paymentss")
    # journal_entry = relationship("JournalEntries", back_populates="paymentss")
    # partner = relationship("BusinessPartners", back_populates="paymentss")
