"""
Foundation Module — SQLAlchemy ORM Models
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.520566
One model class per table with full relationship support.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional
from uuid import UUID
import uuid

from sqlalchemy import (
    Column, Integer, BigInteger, SmallInteger,
    Numeric, Float, Boolean,
    String, Text, Unicode, UnicodeText,
    DateTime, Date, Time, DateTime, LargeBinary,
    ForeignKey, ForeignKeyConstraint, UniqueConstraint,
    Index, CheckConstraint, PrimaryKeyConstraint,
    TIMESTAMP, JSON, Enum, VARBINARY
)
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER, MONEY, SMALLMONEY, NVARCHAR, NTEXT, IMAGE
from sqlalchemy.orm import relationship, backref, mapped_column, Mapped
from sqlalchemy.sql import func

from app.core.database_mssql import Base

# Module metadata
__module_code__ = "foundation-ebuild"
__tables__ = 4

class Companies(Base):
    """Companies — 14 columns, 0 FKs."""
    __tablename__ = "companies"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    legal_name: Mapped[str] = mapped_column(NVARCHAR(255))
    tax_number: Mapped[str] = mapped_column(NVARCHAR(255))
    registration_number: Mapped[str] = mapped_column(NVARCHAR(255))
    country_code: Mapped[str] = mapped_column(NVARCHAR(2), nullable=False)
    base_currency: Mapped[str] = mapped_column(NVARCHAR(3), nullable=False)
    fiscal_year_start: Mapped[int] = mapped_column(Integer, nullable=False)
    date_format: Mapped[str] = mapped_column(NVARCHAR(50))
    logo_url: Mapped[str] = mapped_column(Text)
    status: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class OrgUnits(Base):
    """OrgUnits — 10 columns, 4 FKs."""
    __tablename__ = "org_units"

    # FK: company_id -> companies.id
    # FK: gl_account_id -> accounts.id
    # FK: parent_id -> org_units.id
    # FK: manager_id -> employees.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    code: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    unit_type: Mapped[str] = mapped_column(NVARCHAR(255))
    parent_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    manager_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    gl_account_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    is_active: Mapped[bool] = mapped_column(Boolean)
    metadata_: Mapped[str] = mapped_column("metadata", Text)

    # company = relationship("Companies", back_populates="org_unitss")
    # gl_account = relationship("Accounts", back_populates="org_unitss")
    # parent = relationship("OrgUnits", back_populates="org_unitss")
    # manager = relationship("Employees", back_populates="org_unitss")

class Roles(Base):
    """Roles — 7 columns, 1 FKs."""
    __tablename__ = "roles"

    # FK: company_id -> companies.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    description: Mapped[str] = mapped_column(Text)
    permissions: Mapped[str] = mapped_column(Text, nullable=False)
    is_system: Mapped[bool] = mapped_column(Boolean, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # company = relationship("Companies", back_populates="roless")

class Users(Base):
    """Users — 15 columns, 2 FKs."""
    __tablename__ = "users"

    # FK: company_id -> companies.id
    # FK: role_id -> roles.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    external_auth_id: Mapped[str] = mapped_column(NVARCHAR(255))
    username: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    full_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    email: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    phone: Mapped[str] = mapped_column(NVARCHAR(50))
    role_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    locale: Mapped[str] = mapped_column(NVARCHAR(50))
    is_system_account: Mapped[bool] = mapped_column(Boolean)
    last_login_at: Mapped[datetime] = mapped_column(DateTime)
    status: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # company = relationship("Companies", back_populates="userss")
    # role = relationship("Roles", back_populates="userss")
