"""
Foundation Module — FastAPI Sub-App
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.529607
Mounted at /api/v1/fou in Bio-ERP main.py
"""
from __future__ import annotations

from fastapi import FastAPI

from .foundation_router import router as foundation_router

def create_foundation_app() -> FastAPI:
    """Factory function to create the foundation sub-application."""
    app = FastAPI(
        title="Foundation Module",
        description="ERP Foundation module — 4 tables",
        version="3.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json"
    )
    app.include_router(foundation_router)

    @app.get("/health")
    async def health_check():
        return {
            "status": "healthy",
            "module": "foundation",
            "version": "3.0.0",
            "tables": 4,
            "database": "SQL Server 2022"
        }

    @app.get("/")
    async def root():
        return {
            "module": "foundation",
            "version": "3.0.0",
            "endpoints": "/docs"
        }

    return app
