"""
Foundation Module — CRUD Services
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.528893
Full CRUD with audit trail, soft delete, and business validations.
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID
from datetime import datetime
from decimal import Decimal

from sqlalchemy.orm import Session, joinedload
from sqlalchemy import and_, or_, desc, func
from fastapi import HTTPException, status
import uuid

from .foundation_models import *
from .foundation_schemas import *

class CompaniesService:
    """CRUD service for Companies."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: CompaniesCreate, created_by: Optional[UUID] = None) -> CompaniesResponse:
        """Create a new Companies record."""
        db_obj = Companies(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return CompaniesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[CompaniesResponse]:
        """Get Companies by primary key."""
        db_obj = self.db.query(Companies).filter(Companies.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Companies not found")
        return CompaniesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> CompaniesListResponse:
        """List Companies records with pagination and filtering."""
        query = self.db.query(Companies)
        if company_id and hasattr(Companies, "company_id"):
            query = query.filter(Companies.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(Companies, key) and value is not None:
                    query = query.filter(getattr(Companies, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(Companies, order_by, Companies.created_at)))
        else:
            query = query.order_by(getattr(Companies, order_by, Companies.created_at))
        items = query.offset(skip).limit(limit).all()
        return CompaniesListResponse(
            items=[CompaniesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: CompaniesUpdate,
               updated_by: Optional[UUID] = None) -> CompaniesResponse:
        """Update an existing Companies record."""
        db_obj = self.db.query(Companies).filter(Companies.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Companies not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return CompaniesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a Companies record. Soft delete by default."""
        db_obj = self.db.query(Companies).filter(Companies.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Companies not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[CompaniesResponse]:
        """Search Companies by name/code fields."""
        query = self.db.query(Companies)
        if company_id and hasattr(Companies, "company_id"):
            query = query.filter(Companies.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(Companies, f)]
        if search_fields:
            conditions = [getattr(Companies, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [CompaniesResponse.model_validate(i) for i in items]

class OrgUnitsService:
    """CRUD service for OrgUnits."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: OrgUnitsCreate, created_by: Optional[UUID] = None) -> OrgUnitsResponse:
        """Create a new OrgUnits record."""
        db_obj = OrgUnits(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return OrgUnitsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[OrgUnitsResponse]:
        """Get OrgUnits by primary key."""
        db_obj = self.db.query(OrgUnits).filter(OrgUnits.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="OrgUnits not found")
        return OrgUnitsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> OrgUnitsListResponse:
        """List OrgUnits records with pagination and filtering."""
        query = self.db.query(OrgUnits)
        if company_id and hasattr(OrgUnits, "company_id"):
            query = query.filter(OrgUnits.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(OrgUnits, key) and value is not None:
                    query = query.filter(getattr(OrgUnits, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(OrgUnits, order_by, OrgUnits.created_at)))
        else:
            query = query.order_by(getattr(OrgUnits, order_by, OrgUnits.created_at))
        items = query.offset(skip).limit(limit).all()
        return OrgUnitsListResponse(
            items=[OrgUnitsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: OrgUnitsUpdate,
               updated_by: Optional[UUID] = None) -> OrgUnitsResponse:
        """Update an existing OrgUnits record."""
        db_obj = self.db.query(OrgUnits).filter(OrgUnits.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="OrgUnits not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return OrgUnitsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a OrgUnits record. Soft delete by default."""
        db_obj = self.db.query(OrgUnits).filter(OrgUnits.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="OrgUnits not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[OrgUnitsResponse]:
        """Search OrgUnits by name/code fields."""
        query = self.db.query(OrgUnits)
        if company_id and hasattr(OrgUnits, "company_id"):
            query = query.filter(OrgUnits.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(OrgUnits, f)]
        if search_fields:
            conditions = [getattr(OrgUnits, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [OrgUnitsResponse.model_validate(i) for i in items]

class RolesService:
    """CRUD service for Roles."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: RolesCreate, created_by: Optional[UUID] = None) -> RolesResponse:
        """Create a new Roles record."""
        db_obj = Roles(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return RolesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[RolesResponse]:
        """Get Roles by primary key."""
        db_obj = self.db.query(Roles).filter(Roles.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Roles not found")
        return RolesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> RolesListResponse:
        """List Roles records with pagination and filtering."""
        query = self.db.query(Roles)
        if company_id and hasattr(Roles, "company_id"):
            query = query.filter(Roles.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(Roles, key) and value is not None:
                    query = query.filter(getattr(Roles, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(Roles, order_by, Roles.created_at)))
        else:
            query = query.order_by(getattr(Roles, order_by, Roles.created_at))
        items = query.offset(skip).limit(limit).all()
        return RolesListResponse(
            items=[RolesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: RolesUpdate,
               updated_by: Optional[UUID] = None) -> RolesResponse:
        """Update an existing Roles record."""
        db_obj = self.db.query(Roles).filter(Roles.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Roles not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return RolesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a Roles record. Soft delete by default."""
        db_obj = self.db.query(Roles).filter(Roles.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Roles not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[RolesResponse]:
        """Search Roles by name/code fields."""
        query = self.db.query(Roles)
        if company_id and hasattr(Roles, "company_id"):
            query = query.filter(Roles.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(Roles, f)]
        if search_fields:
            conditions = [getattr(Roles, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [RolesResponse.model_validate(i) for i in items]

class UsersService:
    """CRUD service for Users."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: UsersCreate, created_by: Optional[UUID] = None) -> UsersResponse:
        """Create a new Users record."""
        db_obj = Users(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return UsersResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[UsersResponse]:
        """Get Users by primary key."""
        db_obj = self.db.query(Users).filter(Users.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Users not found")
        return UsersResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> UsersListResponse:
        """List Users records with pagination and filtering."""
        query = self.db.query(Users)
        if company_id and hasattr(Users, "company_id"):
            query = query.filter(Users.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(Users, key) and value is not None:
                    query = query.filter(getattr(Users, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(Users, order_by, Users.created_at)))
        else:
            query = query.order_by(getattr(Users, order_by, Users.created_at))
        items = query.offset(skip).limit(limit).all()
        return UsersListResponse(
            items=[UsersResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: UsersUpdate,
               updated_by: Optional[UUID] = None) -> UsersResponse:
        """Update an existing Users record."""
        db_obj = self.db.query(Users).filter(Users.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Users not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return UsersResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a Users record. Soft delete by default."""
        db_obj = self.db.query(Users).filter(Users.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Users not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[UsersResponse]:
        """Search Users by name/code fields."""
        query = self.db.query(Users)
        if company_id and hasattr(Users, "company_id"):
            query = query.filter(Users.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(Users, f)]
        if search_fields:
            conditions = [getattr(Users, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [UsersResponse.model_validate(i) for i in items]
