"""
New P0 Module — SQLAlchemy ORM Models
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.688666
One model class per table with full relationship support.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional
from uuid import UUID
import uuid

from sqlalchemy import (
    Column, Integer, BigInteger, SmallInteger,
    Numeric, Float, Boolean,
    String, Text, Unicode, UnicodeText,
    DateTime, Date, Time, DateTime, LargeBinary,
    ForeignKey, ForeignKeyConstraint, UniqueConstraint,
    Index, CheckConstraint, PrimaryKeyConstraint,
    TIMESTAMP, JSON, Enum, VARBINARY
)
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER, MONEY, SMALLMONEY, NVARCHAR, NTEXT, IMAGE
from sqlalchemy.orm import relationship, backref, mapped_column, Mapped
from sqlalchemy.sql import func

from app.core.database_mssql import Base

# Module metadata
__module_code__ = "new_p0-ebuild"
__tables__ = 24

class AiAnomalies(Base):
    """AiAnomalies — 14 columns, 0 FKs."""
    __tablename__ = "ai_anomalies"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    anomaly_type: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    severity: Mapped[str] = mapped_column(NVARCHAR(20), nullable=False)
    entity_type: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    entity_id: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    description: Mapped[str] = mapped_column(Text)
    anomaly_score: Mapped[Decimal] = mapped_column(Numeric(5, 4))
    detected_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    reviewed_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    reviewed_at: Mapped[datetime] = mapped_column(DateTime)
    status: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class AiConversations(Base):
    """AiConversations — 12 columns, 0 FKs."""
    __tablename__ = "ai_conversations"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    user_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    session_id: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    user_message: Mapped[str] = mapped_column(Text, nullable=False)
    ai_response: Mapped[str] = mapped_column(Text)
    context: Mapped[str] = mapped_column(Text)
    tokens_used: Mapped[int] = mapped_column(Integer)
    latency_ms: Mapped[int] = mapped_column(Integer)
    rating: Mapped[int] = mapped_column(Integer)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class AiEmbeddings(Base):
    """AiEmbeddings — 11 columns, 0 FKs."""
    __tablename__ = "ai_embeddings"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    entity_type: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    entity_id: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    embedding_model: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    embedding: Mapped[str] = mapped_column(Text, nullable=False)
    dimensions: Mapped[int] = mapped_column(Integer)
    chunk_index: Mapped[int] = mapped_column(Integer)
    chunk_text: Mapped[str] = mapped_column(Text)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class AiFeedback(Base):
    """AiFeedback — 10 columns, 0 FKs."""
    __tablename__ = "ai_feedback"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    conversation_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    user_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    feedback_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    feedback_text: Mapped[str] = mapped_column(Text)
    corrected_response: Mapped[str] = mapped_column(Text)
    is_incorporated: Mapped[bool] = mapped_column(Boolean, nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class AiModels(Base):
    """AiModels — 12 columns, 0 FKs."""
    __tablename__ = "ai_models"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    model_code: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    model_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    model_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    version: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    provider: Mapped[str] = mapped_column(NVARCHAR(100))
    endpoint_url: Mapped[str] = mapped_column(NVARCHAR(500))
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False)
    config_json: Mapped[str] = mapped_column(Text)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class AiPredictions(Base):
    """AiPredictions — 13 columns, 0 FKs."""
    __tablename__ = "ai_predictions"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    prediction_type: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    model_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    target_entity: Mapped[str] = mapped_column(NVARCHAR(255))
    target_date: Mapped[date] = mapped_column(Date)
    predicted_value: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    actual_value: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    confidence_score: Mapped[Decimal] = mapped_column(Numeric(5, 4))
    prediction_date: Mapped[datetime] = mapped_column(DateTime)
    features_used: Mapped[str] = mapped_column(Text)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class AiPrompts(Base):
    """AiPrompts — 10 columns, 0 FKs."""
    __tablename__ = "ai_prompts"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    prompt_code: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    prompt_text: Mapped[str] = mapped_column(Text, nullable=False)
    prompt_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    context_module: Mapped[str] = mapped_column(NVARCHAR(100))
    locale: Mapped[str] = mapped_column(NVARCHAR(10), nullable=False)
    variables: Mapped[str] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class AiReconTrainingData(Base):
    """AiReconTrainingData — 16 columns, 1 FKs."""
    __tablename__ = "ai_recon_training_data"

    # FK: company_id -> companies.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    bank_narration: Mapped[str] = mapped_column(Text, nullable=False)
    bank_amount: Mapped[Decimal] = mapped_column(Numeric(20, 4))
    bank_date: Mapped[date] = mapped_column(Date)
    matched_document_type: Mapped[str] = mapped_column(NVARCHAR(32))
    matched_document_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    matched_amount: Mapped[Decimal] = mapped_column(Numeric(20, 4))
    is_correct_match: Mapped[bool] = mapped_column(Boolean)
    corrected_match_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    model_version: Mapped[str] = mapped_column(NVARCHAR(32))
    confidence_score: Mapped[Decimal] = mapped_column(Numeric(5, 2))
    user_feedback: Mapped[str] = mapped_column(NVARCHAR(16))
    feedback_by: Mapped[str] = mapped_column(NVARCHAR(256))
    feedback_date: Mapped[datetime] = mapped_column(DateTime)
    created_at: Mapped[datetime] = mapped_column(DateTime)

    # company = relationship("Companies", back_populates="ai_recon_training_datas")

class AiTrainingData(Base):
    """AiTrainingData — 11 columns, 0 FKs."""
    __tablename__ = "ai_training_data"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    model_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    data_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    input_data: Mapped[str] = mapped_column(Text)
    expected_output: Mapped[str] = mapped_column(Text)
    actual_output: Mapped[str] = mapped_column(Text)
    is_used_for_training: Mapped[bool] = mapped_column(Boolean, nullable=False)
    data_hash: Mapped[str] = mapped_column(NVARCHAR(64))
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class CarbonActivities(Base):
    """CarbonActivities — 12 columns, 0 FKs."""
    __tablename__ = "carbon_activities"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    activity_type: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    activity_date: Mapped[date] = mapped_column(Date, nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    unit: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    scope: Mapped[str] = mapped_column(NVARCHAR(10), nullable=False)
    source_type: Mapped[str] = mapped_column(NVARCHAR(50))
    source_id: Mapped[str] = mapped_column(NVARCHAR(255))
    location: Mapped[str] = mapped_column(NVARCHAR(255))
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class CarbonEmissions(Base):
    """CarbonEmissions — 13 columns, 0 FKs."""
    __tablename__ = "carbon_emissions"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    activity_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    factor_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    scope: Mapped[str] = mapped_column(NVARCHAR(10), nullable=False)
    co2e: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    co2: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    ch4: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    n2o: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    calculation_method: Mapped[str] = mapped_column(NVARCHAR(100))
    calculation_date: Mapped[datetime] = mapped_column(DateTime)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class CarbonFactors(Base):
    """CarbonFactors — 18 columns, 0 FKs."""
    __tablename__ = "carbon_factors"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    factor_code: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    factor_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    category: Mapped[str] = mapped_column(NVARCHAR(100))
    source: Mapped[str] = mapped_column(NVARCHAR(100))
    region: Mapped[str] = mapped_column(NVARCHAR(50))
    co2_factor: Mapped[Decimal] = mapped_column(Numeric(18, 10))
    ch4_factor: Mapped[Decimal] = mapped_column(Numeric(18, 10))
    n2o_factor: Mapped[Decimal] = mapped_column(Numeric(18, 10))
    co2e_factor: Mapped[Decimal] = mapped_column(Numeric(18, 10))
    unit: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    valid_from: Mapped[date] = mapped_column(Date)
    valid_to: Mapped[date] = mapped_column(Date)
    is_ai_matched: Mapped[bool] = mapped_column(Boolean, nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class CarbonReductions(Base):
    """CarbonReductions — 15 columns, 0 FKs."""
    __tablename__ = "carbon_reductions"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    initiative_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    initiative_type: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    description: Mapped[str] = mapped_column(Text)
    estimated_reduction: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    actual_reduction: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    investment_cost: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    roi: Mapped[Decimal] = mapped_column(Numeric(10, 4))
    start_date: Mapped[date] = mapped_column(Date)
    end_date: Mapped[date] = mapped_column(Date)
    status: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class CarbonScenarios(Base):
    """CarbonScenarios — 11 columns, 0 FKs."""
    __tablename__ = "carbon_scenarios"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    scenario_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    scenario_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    base_year: Mapped[int] = mapped_column(Integer, nullable=False)
    target_year: Mapped[int] = mapped_column(Integer, nullable=False)
    parameters: Mapped[str] = mapped_column(Text)
    projected_emissions: Mapped[str] = mapped_column(Text)
    created_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class ComplianceAlerts(Base):
    """ComplianceAlerts — 13 columns, 0 FKs."""
    __tablename__ = "compliance_alerts"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    alert_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    title: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    description: Mapped[str] = mapped_column(Text)
    severity: Mapped[str] = mapped_column(NVARCHAR(20), nullable=False)
    entity_type: Mapped[str] = mapped_column(NVARCHAR(100))
    entity_id: Mapped[str] = mapped_column(NVARCHAR(255))
    is_acknowledged: Mapped[bool] = mapped_column(Boolean, nullable=False)
    acknowledged_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    acknowledged_at: Mapped[datetime] = mapped_column(DateTime)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class ComplianceAssessments(Base):
    """ComplianceAssessments — 16 columns, 0 FKs."""
    __tablename__ = "compliance_assessments"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    assessment_code: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    rule_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    entity_type: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    entity_id: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    assessment_date: Mapped[date] = mapped_column(Date, nullable=False)
    score: Mapped[Decimal] = mapped_column(Numeric(5, 2))
    status: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    findings: Mapped[str] = mapped_column(Text)
    remediation_plan: Mapped[str] = mapped_column(Text)
    assessed_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    next_review_date: Mapped[date] = mapped_column(Date)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class ComplianceDocuments(Base):
    """ComplianceDocuments — 11 columns, 0 FKs."""
    __tablename__ = "compliance_documents"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    assessment_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    document_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    file_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    file_url: Mapped[str] = mapped_column(NVARCHAR(500), nullable=False)
    document_type: Mapped[str] = mapped_column(NVARCHAR(100))
    uploaded_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    expiry_date: Mapped[date] = mapped_column(Date)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class ComplianceRules(Base):
    """ComplianceRules — 14 columns, 0 FKs."""
    __tablename__ = "compliance_rules"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    rule_code: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    rule_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    regulation: Mapped[str] = mapped_column(NVARCHAR(255))
    jurisdiction: Mapped[str] = mapped_column(NVARCHAR(100))
    rule_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    condition_logic: Mapped[str] = mapped_column(Text)
    action: Mapped[str] = mapped_column(Text)
    risk_weight: Mapped[Decimal] = mapped_column(Numeric(5, 2))
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class EsgAuditTrail(Base):
    """EsgAuditTrail — 11 columns, 0 FKs."""
    __tablename__ = "esg_audit_trail"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    entity_type: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    entity_id: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    field_changed: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    old_value: Mapped[str] = mapped_column(Text)
    new_value: Mapped[str] = mapped_column(Text)
    changed_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    change_reason: Mapped[str] = mapped_column(Text)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class EsgFrameworks(Base):
    """EsgFrameworks — 9 columns, 0 FKs."""
    __tablename__ = "esg_frameworks"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    framework_code: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    framework_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    framework_body: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    version: Mapped[str] = mapped_column(NVARCHAR(50))
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class EsgKpis(Base):
    """EsgKpis — 13 columns, 0 FKs."""
    __tablename__ = "esg_kpis"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    framework_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    kpi_code: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    kpi_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    category: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    unit: Mapped[str] = mapped_column(NVARCHAR(50))
    target_value: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    current_value: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    reporting_period: Mapped[str] = mapped_column(NVARCHAR(50))
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class EsgMateriality(Base):
    """EsgMateriality — 11 columns, 0 FKs."""
    __tablename__ = "esg_materiality"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    topic: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    impact_magnitude: Mapped[Decimal] = mapped_column(Numeric(5, 2))
    financial_significance: Mapped[Decimal] = mapped_column(Numeric(5, 2))
    stakeholder_concern: Mapped[Decimal] = mapped_column(Numeric(5, 2))
    assessment_date: Mapped[date] = mapped_column(Date)
    assessed_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    status: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class EsgReports(Base):
    """EsgReports — 13 columns, 0 FKs."""
    __tablename__ = "esg_reports"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    report_code: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    report_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    framework_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    report_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    reporting_period_start: Mapped[date] = mapped_column(Date)
    reporting_period_end: Mapped[date] = mapped_column(Date)
    report_data: Mapped[str] = mapped_column(Text)
    is_published: Mapped[bool] = mapped_column(Boolean, nullable=False)
    published_date: Mapped[date] = mapped_column(Date)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class EsgTargets(Base):
    """EsgTargets — 12 columns, 0 FKs."""
    __tablename__ = "esg_targets"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    kpi_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    target_year: Mapped[int] = mapped_column(Integer, nullable=False)
    baseline_value: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    target_value: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    current_value: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    target_type: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    status: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

