"""
Registry Module — FastAPI Router
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.043607
Mounted at /api/v1/reg
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status, Query, Body
from sqlalchemy.orm import Session

from app.core.database_mssql import get_db
from .registry_schemas import *
from .registry_services import *

router = APIRouter(prefix="/reg", tags=["Registry"])

@router.get("/ebuild_activity_profiless", response_model=EbuildActivityProfilesListResponse)
def list_ebuild_activity_profiless(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all EbuildActivityProfiles records."""
    service = EbuildActivityProfilesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/ebuild_activity_profiless/{id}", response_model=EbuildActivityProfilesResponse)
def get_ebuild_activity_profiles(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get EbuildActivityProfiles by ID."""
    service = EbuildActivityProfilesService(db)
    return service.get(id)

@router.post("/ebuild_activity_profiless", response_model=EbuildActivityProfilesResponse, status_code=status.HTTP_201_CREATED)
def create_ebuild_activity_profiles(
    data: EbuildActivityProfilesCreate,
    db: Session = Depends(get_db)
):
    """Create a new EbuildActivityProfiles."""
    service = EbuildActivityProfilesService(db)
    return service.create(data)

@router.put("/ebuild_activity_profiless/{id}", response_model=EbuildActivityProfilesResponse)
def update_ebuild_activity_profiles(
    id: UUID,
    data: EbuildActivityProfilesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing EbuildActivityProfiles."""
    service = EbuildActivityProfilesService(db)
    return service.update(id, data)

@router.delete("/ebuild_activity_profiless/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_ebuild_activity_profiles(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a EbuildActivityProfiles (soft delete by default)."""
    service = EbuildActivityProfilesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/ebuild_activity_profiless/search", response_model=List[EbuildActivityProfilesResponse])
def search_ebuild_activity_profiless(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search EbuildActivityProfiles by name/code/description."""
    service = EbuildActivityProfilesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/ebuild_cycle_templatess", response_model=EbuildCycleTemplatesListResponse)
def list_ebuild_cycle_templatess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all EbuildCycleTemplates records."""
    service = EbuildCycleTemplatesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/ebuild_cycle_templatess/{id}", response_model=EbuildCycleTemplatesResponse)
def get_ebuild_cycle_templates(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get EbuildCycleTemplates by ID."""
    service = EbuildCycleTemplatesService(db)
    return service.get(id)

@router.post("/ebuild_cycle_templatess", response_model=EbuildCycleTemplatesResponse, status_code=status.HTTP_201_CREATED)
def create_ebuild_cycle_templates(
    data: EbuildCycleTemplatesCreate,
    db: Session = Depends(get_db)
):
    """Create a new EbuildCycleTemplates."""
    service = EbuildCycleTemplatesService(db)
    return service.create(data)

@router.put("/ebuild_cycle_templatess/{id}", response_model=EbuildCycleTemplatesResponse)
def update_ebuild_cycle_templates(
    id: UUID,
    data: EbuildCycleTemplatesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing EbuildCycleTemplates."""
    service = EbuildCycleTemplatesService(db)
    return service.update(id, data)

@router.delete("/ebuild_cycle_templatess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_ebuild_cycle_templates(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a EbuildCycleTemplates (soft delete by default)."""
    service = EbuildCycleTemplatesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/ebuild_cycle_templatess/search", response_model=List[EbuildCycleTemplatesResponse])
def search_ebuild_cycle_templatess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search EbuildCycleTemplates by name/code/description."""
    service = EbuildCycleTemplatesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/ebuild_module_registrys", response_model=EbuildModuleRegistryListResponse)
def list_ebuild_module_registrys(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all EbuildModuleRegistry records."""
    service = EbuildModuleRegistryService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/ebuild_module_registrys/{id}", response_model=EbuildModuleRegistryResponse)
def get_ebuild_module_registry(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get EbuildModuleRegistry by ID."""
    service = EbuildModuleRegistryService(db)
    return service.get(id)

@router.post("/ebuild_module_registrys", response_model=EbuildModuleRegistryResponse, status_code=status.HTTP_201_CREATED)
def create_ebuild_module_registry(
    data: EbuildModuleRegistryCreate,
    db: Session = Depends(get_db)
):
    """Create a new EbuildModuleRegistry."""
    service = EbuildModuleRegistryService(db)
    return service.create(data)

@router.put("/ebuild_module_registrys/{id}", response_model=EbuildModuleRegistryResponse)
def update_ebuild_module_registry(
    id: UUID,
    data: EbuildModuleRegistryUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing EbuildModuleRegistry."""
    service = EbuildModuleRegistryService(db)
    return service.update(id, data)

@router.delete("/ebuild_module_registrys/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_ebuild_module_registry(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a EbuildModuleRegistry (soft delete by default)."""
    service = EbuildModuleRegistryService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/ebuild_module_registrys/search", response_model=List[EbuildModuleRegistryResponse])
def search_ebuild_module_registrys(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search EbuildModuleRegistry by name/code/description."""
    service = EbuildModuleRegistryService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/ebuild_packagess", response_model=EbuildPackagesListResponse)
def list_ebuild_packagess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all EbuildPackages records."""
    service = EbuildPackagesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/ebuild_packagess/{id}", response_model=EbuildPackagesResponse)
def get_ebuild_packages(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get EbuildPackages by ID."""
    service = EbuildPackagesService(db)
    return service.get(id)

@router.post("/ebuild_packagess", response_model=EbuildPackagesResponse, status_code=status.HTTP_201_CREATED)
def create_ebuild_packages(
    data: EbuildPackagesCreate,
    db: Session = Depends(get_db)
):
    """Create a new EbuildPackages."""
    service = EbuildPackagesService(db)
    return service.create(data)

@router.put("/ebuild_packagess/{id}", response_model=EbuildPackagesResponse)
def update_ebuild_packages(
    id: UUID,
    data: EbuildPackagesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing EbuildPackages."""
    service = EbuildPackagesService(db)
    return service.update(id, data)

@router.delete("/ebuild_packagess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_ebuild_packages(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a EbuildPackages (soft delete by default)."""
    service = EbuildPackagesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/ebuild_packagess/search", response_model=List[EbuildPackagesResponse])
def search_ebuild_packagess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search EbuildPackages by name/code/description."""
    service = EbuildPackagesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/dashboard/summary")
def get_registry_dashboard(
    company_id: UUID,
    db: Session = Depends(get_db)
):
    """Get Registry dashboard summary."""
    return {
        "module": "registry",
        "company_id": str(company_id),
        "tables": 4,
        "metrics": {}
    }
