"""
Registry Module — SQLAlchemy ORM Models
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.032697
One model class per table with full relationship support.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional
from uuid import UUID
import uuid

from sqlalchemy import (
    Column, Integer, BigInteger, SmallInteger,
    Numeric, Float, Boolean,
    String, Text, Unicode, UnicodeText,
    DateTime, Date, Time, DateTime, LargeBinary,
    ForeignKey, ForeignKeyConstraint, UniqueConstraint,
    Index, CheckConstraint, PrimaryKeyConstraint,
    TIMESTAMP, JSON, Enum, VARBINARY
)
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER, MONEY, SMALLMONEY, NVARCHAR, NTEXT, IMAGE
from sqlalchemy.orm import relationship, backref, mapped_column, Mapped
from sqlalchemy.sql import func

from app.core.database_mssql import Base

# Module metadata
__module_code__ = "registry-ebuild"
__tables__ = 4

class EbuildActivityProfiles(Base):
    """EbuildActivityProfiles — 20 columns, 0 FKs."""
    __tablename__ = "ebuild_activity_profiles"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    profile_code: Mapped[str] = mapped_column(NVARCHAR(20), nullable=False)
    profile_name: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    profile_name_ar: Mapped[str] = mapped_column(NVARCHAR(100))
    description: Mapped[str] = mapped_column(Text)
    sector_codes: Mapped[str] = mapped_column(Text)
    typical_legal_forms: Mapped[str] = mapped_column(Text)
    typical_size_range: Mapped[str] = mapped_column(NVARCHAR(50))
    capital_structure_type: Mapped[str] = mapped_column(NVARCHAR(50))
    required_modules: Mapped[str] = mapped_column(Text, nullable=False)
    optional_modules: Mapped[str] = mapped_column(Text, nullable=False)
    operational_cycles: Mapped[str] = mapped_column(Text, nullable=False)
    compliance_frameworks: Mapped[str] = mapped_column(Text)
    default_coa_template_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    ebuild_package: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    ebuild_version: Mapped[str] = mapped_column(NVARCHAR(20))
    use_flags: Mapped[str] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean)
    created_at: Mapped[datetime] = mapped_column(DateTime)
    updated_at: Mapped[datetime] = mapped_column(DateTime)


class EbuildCycleTemplates(Base):
    """EbuildCycleTemplates — 15 columns, 0 FKs."""
    __tablename__ = "ebuild_cycle_templates"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    cycle_code: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    cycle_name: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    cycle_name_ar: Mapped[str] = mapped_column(NVARCHAR(100))
    description: Mapped[str] = mapped_column(Text)
    applicable_profiles: Mapped[str] = mapped_column(Text, nullable=False)
    stages: Mapped[str] = mapped_column(Text, nullable=False)
    document_templates: Mapped[str] = mapped_column(Text)
    financial_impact: Mapped[str] = mapped_column(Text)
    approval_workflow: Mapped[str] = mapped_column(Text)
    module_integrations: Mapped[str] = mapped_column(Text)
    ebuild_package: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    use_flags: Mapped[str] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean)
    created_at: Mapped[datetime] = mapped_column(DateTime)


class EbuildModuleRegistry(Base):
    """EbuildModuleRegistry — 21 columns, 0 FKs."""
    __tablename__ = "ebuild_module_registry"

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    module_code: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    module_name: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    module_name_ar: Mapped[str] = mapped_column(NVARCHAR(100))
    description: Mapped[str] = mapped_column(Text)
    current_version: Mapped[str] = mapped_column(NVARCHAR(20))
    min_bio_erp_version: Mapped[str] = mapped_column(NVARCHAR(20))
    hard_dependencies: Mapped[str] = mapped_column(Text)
    soft_dependencies: Mapped[str] = mapped_column(Text)
    conflicts: Mapped[str] = mapped_column(Text)
    available_use_flags: Mapped[str] = mapped_column(Text)
    default_use_flags: Mapped[str] = mapped_column(Text)
    tables_created: Mapped[str] = mapped_column(Text)
    api_prefix: Mapped[str] = mapped_column(NVARCHAR(100))
    neural_links: Mapped[str] = mapped_column(Text)
    applicable_profiles: Mapped[str] = mapped_column(Text)
    is_core: Mapped[bool] = mapped_column(Boolean)
    ebuild_category: Mapped[str] = mapped_column(NVARCHAR(50), nullable=False)
    ebuild_package: Mapped[str] = mapped_column(NVARCHAR(100), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean)
    created_at: Mapped[datetime] = mapped_column(DateTime)


class EbuildPackages(Base):
    """EbuildPackages — 16 columns, 1 FKs."""
    __tablename__ = "ebuild_packages"

    # FK: company_id -> companies.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    package_name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    category: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    version: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    slot: Mapped[str] = mapped_column(NVARCHAR(255))
    description: Mapped[str] = mapped_column(Text)
    license: Mapped[str] = mapped_column(NVARCHAR(255))
    homepage: Mapped[str] = mapped_column(Text)
    use_flags: Mapped[str] = mapped_column(Text)
    keywords: Mapped[str] = mapped_column(Text)
    dependencies: Mapped[str] = mapped_column(Text)
    is_installed: Mapped[bool] = mapped_column(Boolean)
    install_date: Mapped[datetime] = mapped_column(DateTime)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # company = relationship("Companies", back_populates="ebuild_packagess")
