"""
Registry Module — Pydantic v2 Schemas
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.038006
Provides Create, Update, Response, and ListResponse schemas per table.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional, Any, Dict
from uuid import UUID

from pydantic import BaseModel, Field, ConfigDict, model_validator, constr, condecimal

# Common response fields mixin
class AuditFields(BaseModel):
    """Audit trail fields included in all responses."""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    created_by: Optional[UUID] = None
    updated_by: Optional[UUID] = None
    is_active: Optional[bool] = True
    company_id: Optional[UUID] = None

class EbuildActivityProfilesCreate(BaseModel):
    """Schema for creating new EbuildActivityProfiles."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    profile_code: str
    profile_name: str
    profile_name_ar: Optional[str] = None
    description: Optional[str] = None
    sector_codes: Optional[str] = None
    typical_legal_forms: Optional[str] = None
    typical_size_range: Optional[str] = None
    capital_structure_type: Optional[str] = None
    required_modules: str
    optional_modules: str
    operational_cycles: str
    compliance_frameworks: Optional[str] = None
    default_coa_template_id: Optional[UUID] = None
    ebuild_package: str
    ebuild_version: Optional[str] = None
    use_flags: Optional[str] = None
    is_active: Optional[bool] = True

class EbuildActivityProfilesUpdate(BaseModel):
    """Schema for updating existing EbuildActivityProfiles."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    profile_code: Optional[str] = None
    profile_name: Optional[str] = None
    profile_name_ar: Optional[str] = None
    description: Optional[str] = None
    sector_codes: Optional[str] = None
    typical_legal_forms: Optional[str] = None
    typical_size_range: Optional[str] = None
    capital_structure_type: Optional[str] = None
    required_modules: Optional[str] = None
    optional_modules: Optional[str] = None
    operational_cycles: Optional[str] = None
    compliance_frameworks: Optional[str] = None
    default_coa_template_id: Optional[UUID] = None
    ebuild_package: Optional[str] = None
    ebuild_version: Optional[str] = None
    use_flags: Optional[str] = None
    is_active: Optional[bool] = None

class EbuildActivityProfilesResponse(AuditFields):
    """Response schema for EbuildActivityProfiles (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    profile_code: str
    profile_name: str
    profile_name_ar: Optional[str] = None
    description: Optional[str] = None
    sector_codes: Optional[str] = None
    typical_legal_forms: Optional[str] = None
    typical_size_range: Optional[str] = None
    capital_structure_type: Optional[str] = None
    required_modules: str
    optional_modules: str
    operational_cycles: str
    compliance_frameworks: Optional[str] = None
    default_coa_template_id: Optional[UUID] = None
    ebuild_package: str
    ebuild_version: Optional[str] = None
    use_flags: Optional[str] = None
    is_active: Optional[bool] = True
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class EbuildActivityProfilesListResponse(BaseModel):
    """Paginated list response for EbuildActivityProfiles."""
    items: List[EbuildActivityProfilesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class EbuildCycleTemplatesCreate(BaseModel):
    """Schema for creating new EbuildCycleTemplates."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    cycle_code: str
    cycle_name: str
    cycle_name_ar: Optional[str] = None
    description: Optional[str] = None
    applicable_profiles: str
    stages: str
    document_templates: Optional[str] = None
    financial_impact: Optional[str] = None
    approval_workflow: Optional[str] = None
    module_integrations: Optional[str] = None
    ebuild_package: str
    use_flags: Optional[str] = None
    is_active: Optional[bool] = True

class EbuildCycleTemplatesUpdate(BaseModel):
    """Schema for updating existing EbuildCycleTemplates."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    cycle_code: Optional[str] = None
    cycle_name: Optional[str] = None
    cycle_name_ar: Optional[str] = None
    description: Optional[str] = None
    applicable_profiles: Optional[str] = None
    stages: Optional[str] = None
    document_templates: Optional[str] = None
    financial_impact: Optional[str] = None
    approval_workflow: Optional[str] = None
    module_integrations: Optional[str] = None
    ebuild_package: Optional[str] = None
    use_flags: Optional[str] = None
    is_active: Optional[bool] = None

class EbuildCycleTemplatesResponse(AuditFields):
    """Response schema for EbuildCycleTemplates (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    cycle_code: str
    cycle_name: str
    cycle_name_ar: Optional[str] = None
    description: Optional[str] = None
    applicable_profiles: str
    stages: str
    document_templates: Optional[str] = None
    financial_impact: Optional[str] = None
    approval_workflow: Optional[str] = None
    module_integrations: Optional[str] = None
    ebuild_package: str
    use_flags: Optional[str] = None
    is_active: Optional[bool] = True
    created_at: Optional[datetime] = None

class EbuildCycleTemplatesListResponse(BaseModel):
    """Paginated list response for EbuildCycleTemplates."""
    items: List[EbuildCycleTemplatesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class EbuildModuleRegistryCreate(BaseModel):
    """Schema for creating new EbuildModuleRegistry."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    module_code: str
    module_name: str
    module_name_ar: Optional[str] = None
    description: Optional[str] = None
    current_version: Optional[str] = None
    min_bio_erp_version: Optional[str] = None
    hard_dependencies: Optional[str] = None
    soft_dependencies: Optional[str] = None
    conflicts: Optional[str] = None
    available_use_flags: Optional[str] = None
    default_use_flags: Optional[str] = None
    tables_created: Optional[str] = None
    api_prefix: Optional[str] = None
    neural_links: Optional[str] = None
    applicable_profiles: Optional[str] = None
    is_core: Optional[bool] = None
    ebuild_category: str
    ebuild_package: str
    is_active: Optional[bool] = True

class EbuildModuleRegistryUpdate(BaseModel):
    """Schema for updating existing EbuildModuleRegistry."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    module_code: Optional[str] = None
    module_name: Optional[str] = None
    module_name_ar: Optional[str] = None
    description: Optional[str] = None
    current_version: Optional[str] = None
    min_bio_erp_version: Optional[str] = None
    hard_dependencies: Optional[str] = None
    soft_dependencies: Optional[str] = None
    conflicts: Optional[str] = None
    available_use_flags: Optional[str] = None
    default_use_flags: Optional[str] = None
    tables_created: Optional[str] = None
    api_prefix: Optional[str] = None
    neural_links: Optional[str] = None
    applicable_profiles: Optional[str] = None
    is_core: Optional[bool] = None
    ebuild_category: Optional[str] = None
    ebuild_package: Optional[str] = None
    is_active: Optional[bool] = None

class EbuildModuleRegistryResponse(AuditFields):
    """Response schema for EbuildModuleRegistry (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    module_code: str
    module_name: str
    module_name_ar: Optional[str] = None
    description: Optional[str] = None
    current_version: Optional[str] = None
    min_bio_erp_version: Optional[str] = None
    hard_dependencies: Optional[str] = None
    soft_dependencies: Optional[str] = None
    conflicts: Optional[str] = None
    available_use_flags: Optional[str] = None
    default_use_flags: Optional[str] = None
    tables_created: Optional[str] = None
    api_prefix: Optional[str] = None
    neural_links: Optional[str] = None
    applicable_profiles: Optional[str] = None
    is_core: Optional[bool] = None
    ebuild_category: str
    ebuild_package: str
    is_active: Optional[bool] = True
    created_at: Optional[datetime] = None

class EbuildModuleRegistryListResponse(BaseModel):
    """Paginated list response for EbuildModuleRegistry."""
    items: List[EbuildModuleRegistryResponse]
    total: int
    skip: int = 0
    limit: int = 100

class EbuildPackagesCreate(BaseModel):
    """Schema for creating new EbuildPackages."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    package_name: str
    category: str
    version: str
    slot: Optional[str] = None
    description: Optional[str] = None
    license: Optional[str] = None
    homepage: Optional[str] = None
    use_flags: Optional[str] = None
    keywords: Optional[str] = None
    dependencies: Optional[str] = None
    is_installed: Optional[bool] = None
    install_date: Optional[datetime] = None
    metadata: Optional[str] = None

class EbuildPackagesUpdate(BaseModel):
    """Schema for updating existing EbuildPackages."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    package_name: Optional[str] = None
    category: Optional[str] = None
    version: Optional[str] = None
    slot: Optional[str] = None
    description: Optional[str] = None
    license: Optional[str] = None
    homepage: Optional[str] = None
    use_flags: Optional[str] = None
    keywords: Optional[str] = None
    dependencies: Optional[str] = None
    is_installed: Optional[bool] = None
    install_date: Optional[datetime] = None
    metadata: Optional[str] = None

class EbuildPackagesResponse(AuditFields):
    """Response schema for EbuildPackages (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    package_name: str
    category: str
    version: str
    slot: Optional[str] = None
    description: Optional[str] = None
    license: Optional[str] = None
    homepage: Optional[str] = None
    use_flags: Optional[str] = None
    keywords: Optional[str] = None
    dependencies: Optional[str] = None
    is_installed: Optional[bool] = None
    install_date: Optional[datetime] = None
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None

class EbuildPackagesListResponse(BaseModel):
    """Paginated list response for EbuildPackages."""
    items: List[EbuildPackagesResponse]
    total: int
    skip: int = 0
    limit: int = 100
