"""
Registry Module — CRUD Services
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.043321
Full CRUD with audit trail, soft delete, and business validations.
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID
from datetime import datetime
from decimal import Decimal

from sqlalchemy.orm import Session, joinedload
from sqlalchemy import and_, or_, desc, func
from fastapi import HTTPException, status
import uuid

from .registry_models import *
from .registry_schemas import *

class EbuildActivityProfilesService:
    """CRUD service for EbuildActivityProfiles."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: EbuildActivityProfilesCreate, created_by: Optional[UUID] = None) -> EbuildActivityProfilesResponse:
        """Create a new EbuildActivityProfiles record."""
        db_obj = EbuildActivityProfiles(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return EbuildActivityProfilesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[EbuildActivityProfilesResponse]:
        """Get EbuildActivityProfiles by primary key."""
        db_obj = self.db.query(EbuildActivityProfiles).filter(EbuildActivityProfiles.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildActivityProfiles not found")
        return EbuildActivityProfilesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> EbuildActivityProfilesListResponse:
        """List EbuildActivityProfiles records with pagination and filtering."""
        query = self.db.query(EbuildActivityProfiles)
        if company_id and hasattr(EbuildActivityProfiles, "company_id"):
            query = query.filter(EbuildActivityProfiles.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(EbuildActivityProfiles, key) and value is not None:
                    query = query.filter(getattr(EbuildActivityProfiles, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(EbuildActivityProfiles, order_by, EbuildActivityProfiles.created_at)))
        else:
            query = query.order_by(getattr(EbuildActivityProfiles, order_by, EbuildActivityProfiles.created_at))
        items = query.offset(skip).limit(limit).all()
        return EbuildActivityProfilesListResponse(
            items=[EbuildActivityProfilesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: EbuildActivityProfilesUpdate,
               updated_by: Optional[UUID] = None) -> EbuildActivityProfilesResponse:
        """Update an existing EbuildActivityProfiles record."""
        db_obj = self.db.query(EbuildActivityProfiles).filter(EbuildActivityProfiles.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildActivityProfiles not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return EbuildActivityProfilesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a EbuildActivityProfiles record. Soft delete by default."""
        db_obj = self.db.query(EbuildActivityProfiles).filter(EbuildActivityProfiles.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildActivityProfiles not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[EbuildActivityProfilesResponse]:
        """Search EbuildActivityProfiles by name/code fields."""
        query = self.db.query(EbuildActivityProfiles)
        if company_id and hasattr(EbuildActivityProfiles, "company_id"):
            query = query.filter(EbuildActivityProfiles.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(EbuildActivityProfiles, f)]
        if search_fields:
            conditions = [getattr(EbuildActivityProfiles, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [EbuildActivityProfilesResponse.model_validate(i) for i in items]

class EbuildCycleTemplatesService:
    """CRUD service for EbuildCycleTemplates."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: EbuildCycleTemplatesCreate, created_by: Optional[UUID] = None) -> EbuildCycleTemplatesResponse:
        """Create a new EbuildCycleTemplates record."""
        db_obj = EbuildCycleTemplates(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return EbuildCycleTemplatesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[EbuildCycleTemplatesResponse]:
        """Get EbuildCycleTemplates by primary key."""
        db_obj = self.db.query(EbuildCycleTemplates).filter(EbuildCycleTemplates.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildCycleTemplates not found")
        return EbuildCycleTemplatesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> EbuildCycleTemplatesListResponse:
        """List EbuildCycleTemplates records with pagination and filtering."""
        query = self.db.query(EbuildCycleTemplates)
        if company_id and hasattr(EbuildCycleTemplates, "company_id"):
            query = query.filter(EbuildCycleTemplates.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(EbuildCycleTemplates, key) and value is not None:
                    query = query.filter(getattr(EbuildCycleTemplates, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(EbuildCycleTemplates, order_by, EbuildCycleTemplates.created_at)))
        else:
            query = query.order_by(getattr(EbuildCycleTemplates, order_by, EbuildCycleTemplates.created_at))
        items = query.offset(skip).limit(limit).all()
        return EbuildCycleTemplatesListResponse(
            items=[EbuildCycleTemplatesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: EbuildCycleTemplatesUpdate,
               updated_by: Optional[UUID] = None) -> EbuildCycleTemplatesResponse:
        """Update an existing EbuildCycleTemplates record."""
        db_obj = self.db.query(EbuildCycleTemplates).filter(EbuildCycleTemplates.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildCycleTemplates not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return EbuildCycleTemplatesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a EbuildCycleTemplates record. Soft delete by default."""
        db_obj = self.db.query(EbuildCycleTemplates).filter(EbuildCycleTemplates.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildCycleTemplates not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[EbuildCycleTemplatesResponse]:
        """Search EbuildCycleTemplates by name/code fields."""
        query = self.db.query(EbuildCycleTemplates)
        if company_id and hasattr(EbuildCycleTemplates, "company_id"):
            query = query.filter(EbuildCycleTemplates.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(EbuildCycleTemplates, f)]
        if search_fields:
            conditions = [getattr(EbuildCycleTemplates, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [EbuildCycleTemplatesResponse.model_validate(i) for i in items]

class EbuildModuleRegistryService:
    """CRUD service for EbuildModuleRegistry."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: EbuildModuleRegistryCreate, created_by: Optional[UUID] = None) -> EbuildModuleRegistryResponse:
        """Create a new EbuildModuleRegistry record."""
        db_obj = EbuildModuleRegistry(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return EbuildModuleRegistryResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[EbuildModuleRegistryResponse]:
        """Get EbuildModuleRegistry by primary key."""
        db_obj = self.db.query(EbuildModuleRegistry).filter(EbuildModuleRegistry.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildModuleRegistry not found")
        return EbuildModuleRegistryResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> EbuildModuleRegistryListResponse:
        """List EbuildModuleRegistry records with pagination and filtering."""
        query = self.db.query(EbuildModuleRegistry)
        if company_id and hasattr(EbuildModuleRegistry, "company_id"):
            query = query.filter(EbuildModuleRegistry.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(EbuildModuleRegistry, key) and value is not None:
                    query = query.filter(getattr(EbuildModuleRegistry, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(EbuildModuleRegistry, order_by, EbuildModuleRegistry.created_at)))
        else:
            query = query.order_by(getattr(EbuildModuleRegistry, order_by, EbuildModuleRegistry.created_at))
        items = query.offset(skip).limit(limit).all()
        return EbuildModuleRegistryListResponse(
            items=[EbuildModuleRegistryResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: EbuildModuleRegistryUpdate,
               updated_by: Optional[UUID] = None) -> EbuildModuleRegistryResponse:
        """Update an existing EbuildModuleRegistry record."""
        db_obj = self.db.query(EbuildModuleRegistry).filter(EbuildModuleRegistry.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildModuleRegistry not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return EbuildModuleRegistryResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a EbuildModuleRegistry record. Soft delete by default."""
        db_obj = self.db.query(EbuildModuleRegistry).filter(EbuildModuleRegistry.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildModuleRegistry not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[EbuildModuleRegistryResponse]:
        """Search EbuildModuleRegistry by name/code fields."""
        query = self.db.query(EbuildModuleRegistry)
        if company_id and hasattr(EbuildModuleRegistry, "company_id"):
            query = query.filter(EbuildModuleRegistry.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(EbuildModuleRegistry, f)]
        if search_fields:
            conditions = [getattr(EbuildModuleRegistry, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [EbuildModuleRegistryResponse.model_validate(i) for i in items]

class EbuildPackagesService:
    """CRUD service for EbuildPackages."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: EbuildPackagesCreate, created_by: Optional[UUID] = None) -> EbuildPackagesResponse:
        """Create a new EbuildPackages record."""
        db_obj = EbuildPackages(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return EbuildPackagesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[EbuildPackagesResponse]:
        """Get EbuildPackages by primary key."""
        db_obj = self.db.query(EbuildPackages).filter(EbuildPackages.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildPackages not found")
        return EbuildPackagesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> EbuildPackagesListResponse:
        """List EbuildPackages records with pagination and filtering."""
        query = self.db.query(EbuildPackages)
        if company_id and hasattr(EbuildPackages, "company_id"):
            query = query.filter(EbuildPackages.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(EbuildPackages, key) and value is not None:
                    query = query.filter(getattr(EbuildPackages, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(EbuildPackages, order_by, EbuildPackages.created_at)))
        else:
            query = query.order_by(getattr(EbuildPackages, order_by, EbuildPackages.created_at))
        items = query.offset(skip).limit(limit).all()
        return EbuildPackagesListResponse(
            items=[EbuildPackagesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: EbuildPackagesUpdate,
               updated_by: Optional[UUID] = None) -> EbuildPackagesResponse:
        """Update an existing EbuildPackages record."""
        db_obj = self.db.query(EbuildPackages).filter(EbuildPackages.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildPackages not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return EbuildPackagesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a EbuildPackages record. Soft delete by default."""
        db_obj = self.db.query(EbuildPackages).filter(EbuildPackages.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="EbuildPackages not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[EbuildPackagesResponse]:
        """Search EbuildPackages by name/code fields."""
        query = self.db.query(EbuildPackages)
        if company_id and hasattr(EbuildPackages, "company_id"):
            query = query.filter(EbuildPackages.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(EbuildPackages, f)]
        if search_fields:
            conditions = [getattr(EbuildPackages, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [EbuildPackagesResponse.model_validate(i) for i in items]
