"""
Items Module — FastAPI Router
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.643298
Mounted at /api/v1/ite
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status, Query, Body
from sqlalchemy.orm import Session

from app.core.database_mssql import get_db
from .items_schemas import *
from .items_services import *

router = APIRouter(prefix="/ite", tags=["Items"])

@router.get("/hs_codess", response_model=HsCodesListResponse)
def list_hs_codess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all HsCodes records."""
    service = HsCodesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/hs_codess/{id}", response_model=HsCodesResponse)
def get_hs_codes(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get HsCodes by ID."""
    service = HsCodesService(db)
    return service.get(id)

@router.post("/hs_codess", response_model=HsCodesResponse, status_code=status.HTTP_201_CREATED)
def create_hs_codes(
    data: HsCodesCreate,
    db: Session = Depends(get_db)
):
    """Create a new HsCodes."""
    service = HsCodesService(db)
    return service.create(data)

@router.put("/hs_codess/{id}", response_model=HsCodesResponse)
def update_hs_codes(
    id: UUID,
    data: HsCodesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing HsCodes."""
    service = HsCodesService(db)
    return service.update(id, data)

@router.delete("/hs_codess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_hs_codes(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a HsCodes (soft delete by default)."""
    service = HsCodesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/hs_codess/search", response_model=List[HsCodesResponse])
def search_hs_codess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search HsCodes by name/code/description."""
    service = HsCodesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/item_cross_referencess", response_model=ItemCrossReferencesListResponse)
def list_item_cross_referencess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all ItemCrossReferences records."""
    service = ItemCrossReferencesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/item_cross_referencess/{id}", response_model=ItemCrossReferencesResponse)
def get_item_cross_references(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get ItemCrossReferences by ID."""
    service = ItemCrossReferencesService(db)
    return service.get(id)

@router.post("/item_cross_referencess", response_model=ItemCrossReferencesResponse, status_code=status.HTTP_201_CREATED)
def create_item_cross_references(
    data: ItemCrossReferencesCreate,
    db: Session = Depends(get_db)
):
    """Create a new ItemCrossReferences."""
    service = ItemCrossReferencesService(db)
    return service.create(data)

@router.put("/item_cross_referencess/{id}", response_model=ItemCrossReferencesResponse)
def update_item_cross_references(
    id: UUID,
    data: ItemCrossReferencesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing ItemCrossReferences."""
    service = ItemCrossReferencesService(db)
    return service.update(id, data)

@router.delete("/item_cross_referencess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_item_cross_references(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a ItemCrossReferences (soft delete by default)."""
    service = ItemCrossReferencesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/item_cross_referencess/search", response_model=List[ItemCrossReferencesResponse])
def search_item_cross_referencess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search ItemCrossReferences by name/code/description."""
    service = ItemCrossReferencesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/itemss", response_model=ItemsListResponse)
def list_itemss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all Items records."""
    service = ItemsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/itemss/{id}", response_model=ItemsResponse)
def get_items(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get Items by ID."""
    service = ItemsService(db)
    return service.get(id)

@router.post("/itemss", response_model=ItemsResponse, status_code=status.HTTP_201_CREATED)
def create_items(
    data: ItemsCreate,
    db: Session = Depends(get_db)
):
    """Create a new Items."""
    service = ItemsService(db)
    return service.create(data)

@router.put("/itemss/{id}", response_model=ItemsResponse)
def update_items(
    id: UUID,
    data: ItemsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing Items."""
    service = ItemsService(db)
    return service.update(id, data)

@router.delete("/itemss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_items(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a Items (soft delete by default)."""
    service = ItemsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/itemss/search", response_model=List[ItemsResponse])
def search_itemss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search Items by name/code/description."""
    service = ItemsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/price_list_liness", response_model=PriceListLinesListResponse)
def list_price_list_liness(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all PriceListLines records."""
    service = PriceListLinesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/price_list_liness/{id}", response_model=PriceListLinesResponse)
def get_price_list_lines(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get PriceListLines by ID."""
    service = PriceListLinesService(db)
    return service.get(id)

@router.post("/price_list_liness", response_model=PriceListLinesResponse, status_code=status.HTTP_201_CREATED)
def create_price_list_lines(
    data: PriceListLinesCreate,
    db: Session = Depends(get_db)
):
    """Create a new PriceListLines."""
    service = PriceListLinesService(db)
    return service.create(data)

@router.put("/price_list_liness/{id}", response_model=PriceListLinesResponse)
def update_price_list_lines(
    id: UUID,
    data: PriceListLinesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing PriceListLines."""
    service = PriceListLinesService(db)
    return service.update(id, data)

@router.delete("/price_list_liness/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_price_list_lines(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a PriceListLines (soft delete by default)."""
    service = PriceListLinesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/price_list_liness/search", response_model=List[PriceListLinesResponse])
def search_price_list_liness(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search PriceListLines by name/code/description."""
    service = PriceListLinesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/price_listss", response_model=PriceListsListResponse)
def list_price_listss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all PriceLists records."""
    service = PriceListsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/price_listss/{id}", response_model=PriceListsResponse)
def get_price_lists(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get PriceLists by ID."""
    service = PriceListsService(db)
    return service.get(id)

@router.post("/price_listss", response_model=PriceListsResponse, status_code=status.HTTP_201_CREATED)
def create_price_lists(
    data: PriceListsCreate,
    db: Session = Depends(get_db)
):
    """Create a new PriceLists."""
    service = PriceListsService(db)
    return service.create(data)

@router.put("/price_listss/{id}", response_model=PriceListsResponse)
def update_price_lists(
    id: UUID,
    data: PriceListsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing PriceLists."""
    service = PriceListsService(db)
    return service.update(id, data)

@router.delete("/price_listss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_price_lists(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a PriceLists (soft delete by default)."""
    service = PriceListsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/price_listss/search", response_model=List[PriceListsResponse])
def search_price_listss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search PriceLists by name/code/description."""
    service = PriceListsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/unit_of_measuress", response_model=UnitOfMeasuresListResponse)
def list_unit_of_measuress(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all UnitOfMeasures records."""
    service = UnitOfMeasuresService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/unit_of_measuress/{id}", response_model=UnitOfMeasuresResponse)
def get_unit_of_measures(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get UnitOfMeasures by ID."""
    service = UnitOfMeasuresService(db)
    return service.get(id)

@router.post("/unit_of_measuress", response_model=UnitOfMeasuresResponse, status_code=status.HTTP_201_CREATED)
def create_unit_of_measures(
    data: UnitOfMeasuresCreate,
    db: Session = Depends(get_db)
):
    """Create a new UnitOfMeasures."""
    service = UnitOfMeasuresService(db)
    return service.create(data)

@router.put("/unit_of_measuress/{id}", response_model=UnitOfMeasuresResponse)
def update_unit_of_measures(
    id: UUID,
    data: UnitOfMeasuresUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing UnitOfMeasures."""
    service = UnitOfMeasuresService(db)
    return service.update(id, data)

@router.delete("/unit_of_measuress/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_unit_of_measures(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a UnitOfMeasures (soft delete by default)."""
    service = UnitOfMeasuresService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/unit_of_measuress/search", response_model=List[UnitOfMeasuresResponse])
def search_unit_of_measuress(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search UnitOfMeasures by name/code/description."""
    service = UnitOfMeasuresService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/dashboard/summary")
def get_items_dashboard(
    company_id: UUID,
    db: Session = Depends(get_db)
):
    """Get Items dashboard summary."""
    return {
        "module": "items",
        "company_id": str(company_id),
        "tables": 6,
        "metrics": {}
    }
