"""
Items Module — CRUD Services
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.643033
Full CRUD with audit trail, soft delete, and business validations.
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID
from datetime import datetime
from decimal import Decimal

from sqlalchemy.orm import Session, joinedload
from sqlalchemy import and_, or_, desc, func
from fastapi import HTTPException, status
import uuid

from .items_models import *
from .items_schemas import *

class HsCodesService:
    """CRUD service for HsCodes."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: HsCodesCreate, created_by: Optional[UUID] = None) -> HsCodesResponse:
        """Create a new HsCodes record."""
        db_obj = HsCodes(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return HsCodesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[HsCodesResponse]:
        """Get HsCodes by primary key."""
        db_obj = self.db.query(HsCodes).filter(HsCodes.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="HsCodes not found")
        return HsCodesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> HsCodesListResponse:
        """List HsCodes records with pagination and filtering."""
        query = self.db.query(HsCodes)
        if company_id and hasattr(HsCodes, "company_id"):
            query = query.filter(HsCodes.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(HsCodes, key) and value is not None:
                    query = query.filter(getattr(HsCodes, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(HsCodes, order_by, HsCodes.created_at)))
        else:
            query = query.order_by(getattr(HsCodes, order_by, HsCodes.created_at))
        items = query.offset(skip).limit(limit).all()
        return HsCodesListResponse(
            items=[HsCodesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: HsCodesUpdate,
               updated_by: Optional[UUID] = None) -> HsCodesResponse:
        """Update an existing HsCodes record."""
        db_obj = self.db.query(HsCodes).filter(HsCodes.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="HsCodes not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return HsCodesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a HsCodes record. Soft delete by default."""
        db_obj = self.db.query(HsCodes).filter(HsCodes.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="HsCodes not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[HsCodesResponse]:
        """Search HsCodes by name/code fields."""
        query = self.db.query(HsCodes)
        if company_id and hasattr(HsCodes, "company_id"):
            query = query.filter(HsCodes.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(HsCodes, f)]
        if search_fields:
            conditions = [getattr(HsCodes, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [HsCodesResponse.model_validate(i) for i in items]

class ItemCrossReferencesService:
    """CRUD service for ItemCrossReferences."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: ItemCrossReferencesCreate, created_by: Optional[UUID] = None) -> ItemCrossReferencesResponse:
        """Create a new ItemCrossReferences record."""
        db_obj = ItemCrossReferences(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return ItemCrossReferencesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[ItemCrossReferencesResponse]:
        """Get ItemCrossReferences by primary key."""
        db_obj = self.db.query(ItemCrossReferences).filter(ItemCrossReferences.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ItemCrossReferences not found")
        return ItemCrossReferencesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> ItemCrossReferencesListResponse:
        """List ItemCrossReferences records with pagination and filtering."""
        query = self.db.query(ItemCrossReferences)
        if company_id and hasattr(ItemCrossReferences, "company_id"):
            query = query.filter(ItemCrossReferences.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(ItemCrossReferences, key) and value is not None:
                    query = query.filter(getattr(ItemCrossReferences, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(ItemCrossReferences, order_by, ItemCrossReferences.created_at)))
        else:
            query = query.order_by(getattr(ItemCrossReferences, order_by, ItemCrossReferences.created_at))
        items = query.offset(skip).limit(limit).all()
        return ItemCrossReferencesListResponse(
            items=[ItemCrossReferencesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: ItemCrossReferencesUpdate,
               updated_by: Optional[UUID] = None) -> ItemCrossReferencesResponse:
        """Update an existing ItemCrossReferences record."""
        db_obj = self.db.query(ItemCrossReferences).filter(ItemCrossReferences.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ItemCrossReferences not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return ItemCrossReferencesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a ItemCrossReferences record. Soft delete by default."""
        db_obj = self.db.query(ItemCrossReferences).filter(ItemCrossReferences.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ItemCrossReferences not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[ItemCrossReferencesResponse]:
        """Search ItemCrossReferences by name/code fields."""
        query = self.db.query(ItemCrossReferences)
        if company_id and hasattr(ItemCrossReferences, "company_id"):
            query = query.filter(ItemCrossReferences.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(ItemCrossReferences, f)]
        if search_fields:
            conditions = [getattr(ItemCrossReferences, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [ItemCrossReferencesResponse.model_validate(i) for i in items]

class ItemsService:
    """CRUD service for Items."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: ItemsCreate, created_by: Optional[UUID] = None) -> ItemsResponse:
        """Create a new Items record."""
        db_obj = Items(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return ItemsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[ItemsResponse]:
        """Get Items by primary key."""
        db_obj = self.db.query(Items).filter(Items.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Items not found")
        return ItemsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> ItemsListResponse:
        """List Items records with pagination and filtering."""
        query = self.db.query(Items)
        if company_id and hasattr(Items, "company_id"):
            query = query.filter(Items.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(Items, key) and value is not None:
                    query = query.filter(getattr(Items, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(Items, order_by, Items.created_at)))
        else:
            query = query.order_by(getattr(Items, order_by, Items.created_at))
        items = query.offset(skip).limit(limit).all()
        return ItemsListResponse(
            items=[ItemsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: ItemsUpdate,
               updated_by: Optional[UUID] = None) -> ItemsResponse:
        """Update an existing Items record."""
        db_obj = self.db.query(Items).filter(Items.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Items not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return ItemsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a Items record. Soft delete by default."""
        db_obj = self.db.query(Items).filter(Items.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Items not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[ItemsResponse]:
        """Search Items by name/code fields."""
        query = self.db.query(Items)
        if company_id and hasattr(Items, "company_id"):
            query = query.filter(Items.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(Items, f)]
        if search_fields:
            conditions = [getattr(Items, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [ItemsResponse.model_validate(i) for i in items]

class PriceListLinesService:
    """CRUD service for PriceListLines."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: PriceListLinesCreate, created_by: Optional[UUID] = None) -> PriceListLinesResponse:
        """Create a new PriceListLines record."""
        db_obj = PriceListLines(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return PriceListLinesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[PriceListLinesResponse]:
        """Get PriceListLines by primary key."""
        db_obj = self.db.query(PriceListLines).filter(PriceListLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PriceListLines not found")
        return PriceListLinesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> PriceListLinesListResponse:
        """List PriceListLines records with pagination and filtering."""
        query = self.db.query(PriceListLines)
        if company_id and hasattr(PriceListLines, "company_id"):
            query = query.filter(PriceListLines.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(PriceListLines, key) and value is not None:
                    query = query.filter(getattr(PriceListLines, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(PriceListLines, order_by, PriceListLines.created_at)))
        else:
            query = query.order_by(getattr(PriceListLines, order_by, PriceListLines.created_at))
        items = query.offset(skip).limit(limit).all()
        return PriceListLinesListResponse(
            items=[PriceListLinesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: PriceListLinesUpdate,
               updated_by: Optional[UUID] = None) -> PriceListLinesResponse:
        """Update an existing PriceListLines record."""
        db_obj = self.db.query(PriceListLines).filter(PriceListLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PriceListLines not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return PriceListLinesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a PriceListLines record. Soft delete by default."""
        db_obj = self.db.query(PriceListLines).filter(PriceListLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PriceListLines not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[PriceListLinesResponse]:
        """Search PriceListLines by name/code fields."""
        query = self.db.query(PriceListLines)
        if company_id and hasattr(PriceListLines, "company_id"):
            query = query.filter(PriceListLines.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(PriceListLines, f)]
        if search_fields:
            conditions = [getattr(PriceListLines, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [PriceListLinesResponse.model_validate(i) for i in items]

class PriceListsService:
    """CRUD service for PriceLists."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: PriceListsCreate, created_by: Optional[UUID] = None) -> PriceListsResponse:
        """Create a new PriceLists record."""
        db_obj = PriceLists(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return PriceListsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[PriceListsResponse]:
        """Get PriceLists by primary key."""
        db_obj = self.db.query(PriceLists).filter(PriceLists.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PriceLists not found")
        return PriceListsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> PriceListsListResponse:
        """List PriceLists records with pagination and filtering."""
        query = self.db.query(PriceLists)
        if company_id and hasattr(PriceLists, "company_id"):
            query = query.filter(PriceLists.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(PriceLists, key) and value is not None:
                    query = query.filter(getattr(PriceLists, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(PriceLists, order_by, PriceLists.created_at)))
        else:
            query = query.order_by(getattr(PriceLists, order_by, PriceLists.created_at))
        items = query.offset(skip).limit(limit).all()
        return PriceListsListResponse(
            items=[PriceListsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: PriceListsUpdate,
               updated_by: Optional[UUID] = None) -> PriceListsResponse:
        """Update an existing PriceLists record."""
        db_obj = self.db.query(PriceLists).filter(PriceLists.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PriceLists not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return PriceListsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a PriceLists record. Soft delete by default."""
        db_obj = self.db.query(PriceLists).filter(PriceLists.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="PriceLists not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[PriceListsResponse]:
        """Search PriceLists by name/code fields."""
        query = self.db.query(PriceLists)
        if company_id and hasattr(PriceLists, "company_id"):
            query = query.filter(PriceLists.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(PriceLists, f)]
        if search_fields:
            conditions = [getattr(PriceLists, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [PriceListsResponse.model_validate(i) for i in items]

class UnitOfMeasuresService:
    """CRUD service for UnitOfMeasures."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: UnitOfMeasuresCreate, created_by: Optional[UUID] = None) -> UnitOfMeasuresResponse:
        """Create a new UnitOfMeasures record."""
        db_obj = UnitOfMeasures(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return UnitOfMeasuresResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[UnitOfMeasuresResponse]:
        """Get UnitOfMeasures by primary key."""
        db_obj = self.db.query(UnitOfMeasures).filter(UnitOfMeasures.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="UnitOfMeasures not found")
        return UnitOfMeasuresResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> UnitOfMeasuresListResponse:
        """List UnitOfMeasures records with pagination and filtering."""
        query = self.db.query(UnitOfMeasures)
        if company_id and hasattr(UnitOfMeasures, "company_id"):
            query = query.filter(UnitOfMeasures.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(UnitOfMeasures, key) and value is not None:
                    query = query.filter(getattr(UnitOfMeasures, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(UnitOfMeasures, order_by, UnitOfMeasures.created_at)))
        else:
            query = query.order_by(getattr(UnitOfMeasures, order_by, UnitOfMeasures.created_at))
        items = query.offset(skip).limit(limit).all()
        return UnitOfMeasuresListResponse(
            items=[UnitOfMeasuresResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: UnitOfMeasuresUpdate,
               updated_by: Optional[UUID] = None) -> UnitOfMeasuresResponse:
        """Update an existing UnitOfMeasures record."""
        db_obj = self.db.query(UnitOfMeasures).filter(UnitOfMeasures.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="UnitOfMeasures not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return UnitOfMeasuresResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a UnitOfMeasures record. Soft delete by default."""
        db_obj = self.db.query(UnitOfMeasures).filter(UnitOfMeasures.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="UnitOfMeasures not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[UnitOfMeasuresResponse]:
        """Search UnitOfMeasures by name/code fields."""
        query = self.db.query(UnitOfMeasures)
        if company_id and hasattr(UnitOfMeasures, "company_id"):
            query = query.filter(UnitOfMeasures.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(UnitOfMeasures, f)]
        if search_fields:
            conditions = [getattr(UnitOfMeasures, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [UnitOfMeasuresResponse.model_validate(i) for i in items]
