"""
Items Module — Pydantic v2 Schemas
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.638933
Provides Create, Update, Response, and ListResponse schemas per table.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional, Any, Dict
from uuid import UUID

from pydantic import BaseModel, Field, ConfigDict, model_validator, constr, condecimal

# Common response fields mixin
class AuditFields(BaseModel):
    """Audit trail fields included in all responses."""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    created_by: Optional[UUID] = None
    updated_by: Optional[UUID] = None
    is_active: Optional[bool] = True
    company_id: Optional[UUID] = None

class HsCodesCreate(BaseModel):
    """Schema for creating new HsCodes."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    hs_code: str
    hs_code_2: str
    hs_code_4: Optional[str] = None
    hs_code_6: Optional[str] = None
    description: str
    description_ar: Optional[str] = None
    category: Optional[str] = None
    parent_id: Optional[UUID] = None
    import_duty_rate: Optional[Decimal] = None
    vat_rate: Optional[Decimal] = None
    excise_rate: Optional[Decimal] = None
    country_code: Optional[str] = None
    requires_license: Optional[bool] = None
    is_active: Optional[bool] = True

class HsCodesUpdate(BaseModel):
    """Schema for updating existing HsCodes."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    hs_code: Optional[str] = None
    hs_code_2: Optional[str] = None
    hs_code_4: Optional[str] = None
    hs_code_6: Optional[str] = None
    description: Optional[str] = None
    description_ar: Optional[str] = None
    category: Optional[str] = None
    parent_id: Optional[UUID] = None
    import_duty_rate: Optional[Decimal] = None
    vat_rate: Optional[Decimal] = None
    excise_rate: Optional[Decimal] = None
    country_code: Optional[str] = None
    requires_license: Optional[bool] = None
    is_active: Optional[bool] = None

class HsCodesResponse(AuditFields):
    """Response schema for HsCodes (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    hs_code: str
    hs_code_2: str
    hs_code_4: Optional[str] = None
    hs_code_6: Optional[str] = None
    description: str
    description_ar: Optional[str] = None
    category: Optional[str] = None
    parent_id: Optional[UUID] = None
    import_duty_rate: Optional[Decimal] = None
    vat_rate: Optional[Decimal] = None
    excise_rate: Optional[Decimal] = None
    country_code: Optional[str] = None
    requires_license: Optional[bool] = None
    is_active: Optional[bool] = True
    created_at: Optional[datetime] = None

class HsCodesListResponse(BaseModel):
    """Paginated list response for HsCodes."""
    items: List[HsCodesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class ItemCrossReferencesCreate(BaseModel):
    """Schema for creating new ItemCrossReferences."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    item_id: UUID
    partner_id: Optional[UUID] = None
    partner_item_code: str
    partner_item_name: Optional[str] = None
    is_active: Optional[bool] = True

class ItemCrossReferencesUpdate(BaseModel):
    """Schema for updating existing ItemCrossReferences."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    item_id: Optional[UUID] = None
    partner_id: Optional[UUID] = None
    partner_item_code: Optional[str] = None
    partner_item_name: Optional[str] = None
    is_active: Optional[bool] = None

class ItemCrossReferencesResponse(AuditFields):
    """Response schema for ItemCrossReferences (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    item_id: UUID
    partner_id: Optional[UUID] = None
    partner_item_code: str
    partner_item_name: Optional[str] = None
    is_active: Optional[bool] = True

class ItemCrossReferencesListResponse(BaseModel):
    """Paginated list response for ItemCrossReferences."""
    items: List[ItemCrossReferencesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class ItemsCreate(BaseModel):
    """Schema for creating new Items."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    code: str
    name: str
    name_ar: Optional[str] = None
    description: Optional[str] = None
    item_type: str
    uom_id: Optional[UUID] = None
    purchase_uom_id: Optional[UUID] = None
    sales_uom_id: Optional[UUID] = None
    purchase_account_id: Optional[UUID] = None
    sales_account_id: Optional[UUID] = None
    inventory_account_id: Optional[UUID] = None
    cost_of_goods_sold_account_id: Optional[UUID] = None
    standard_cost: Optional[Decimal] = None
    list_price: Optional[Decimal] = None
    is_tracked: bool
    is_serialised: bool
    is_batch_tracked: bool
    hs_code: Optional[str] = None
    weight_kg: Optional[Decimal] = None
    volume_m3: Optional[Decimal] = None
    barcode: Optional[str] = None
    image_url: Optional[str] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None

class ItemsUpdate(BaseModel):
    """Schema for updating existing Items."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    code: Optional[str] = None
    name: Optional[str] = None
    name_ar: Optional[str] = None
    description: Optional[str] = None
    item_type: Optional[str] = None
    uom_id: Optional[UUID] = None
    purchase_uom_id: Optional[UUID] = None
    sales_uom_id: Optional[UUID] = None
    purchase_account_id: Optional[UUID] = None
    sales_account_id: Optional[UUID] = None
    inventory_account_id: Optional[UUID] = None
    cost_of_goods_sold_account_id: Optional[UUID] = None
    standard_cost: Optional[Decimal] = None
    list_price: Optional[Decimal] = None
    is_tracked: Optional[bool] = None
    is_serialised: Optional[bool] = None
    is_batch_tracked: Optional[bool] = None
    hs_code: Optional[str] = None
    weight_kg: Optional[Decimal] = None
    volume_m3: Optional[Decimal] = None
    barcode: Optional[str] = None
    image_url: Optional[str] = None
    is_active: Optional[bool] = None
    metadata: Optional[str] = None

class ItemsResponse(AuditFields):
    """Response schema for Items (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    code: str
    name: str
    name_ar: Optional[str] = None
    description: Optional[str] = None
    item_type: str
    uom_id: Optional[UUID] = None
    purchase_uom_id: Optional[UUID] = None
    sales_uom_id: Optional[UUID] = None
    purchase_account_id: Optional[UUID] = None
    sales_account_id: Optional[UUID] = None
    inventory_account_id: Optional[UUID] = None
    cost_of_goods_sold_account_id: Optional[UUID] = None
    standard_cost: Optional[Decimal] = None
    list_price: Optional[Decimal] = None
    is_tracked: bool
    is_serialised: bool
    is_batch_tracked: bool
    hs_code: Optional[str] = None
    weight_kg: Optional[Decimal] = None
    volume_m3: Optional[Decimal] = None
    barcode: Optional[str] = None
    image_url: Optional[str] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None

class ItemsListResponse(BaseModel):
    """Paginated list response for Items."""
    items: List[ItemsResponse]
    total: int
    skip: int = 0
    limit: int = 100

class PriceListLinesCreate(BaseModel):
    """Schema for creating new PriceListLines."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    price_list_id: UUID
    item_id: UUID
    min_qty: Optional[Decimal] = None
    max_qty: Optional[Decimal] = None
    price: Decimal
    discount_pct: Optional[Decimal] = None
    is_promotional: Optional[bool] = None

class PriceListLinesUpdate(BaseModel):
    """Schema for updating existing PriceListLines."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    price_list_id: Optional[UUID] = None
    item_id: Optional[UUID] = None
    min_qty: Optional[Decimal] = None
    max_qty: Optional[Decimal] = None
    price: Optional[Decimal] = None
    discount_pct: Optional[Decimal] = None
    is_promotional: Optional[bool] = None

class PriceListLinesResponse(AuditFields):
    """Response schema for PriceListLines (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    price_list_id: UUID
    item_id: UUID
    min_qty: Optional[Decimal] = None
    max_qty: Optional[Decimal] = None
    price: Decimal
    discount_pct: Optional[Decimal] = None
    is_promotional: Optional[bool] = None

class PriceListLinesListResponse(BaseModel):
    """Paginated list response for PriceListLines."""
    items: List[PriceListLinesResponse]
    total: int
    skip: int = 0
    limit: int = 100

class PriceListsCreate(BaseModel):
    """Schema for creating new PriceLists."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    name: str
    currency: str
    valid_from: Optional[date] = None
    valid_to: Optional[date] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None

class PriceListsUpdate(BaseModel):
    """Schema for updating existing PriceLists."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    name: Optional[str] = None
    currency: Optional[str] = None
    valid_from: Optional[date] = None
    valid_to: Optional[date] = None
    is_active: Optional[bool] = None
    metadata: Optional[str] = None

class PriceListsResponse(AuditFields):
    """Response schema for PriceLists (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    name: str
    currency: str
    valid_from: Optional[date] = None
    valid_to: Optional[date] = None
    is_active: Optional[bool] = True
    metadata: Optional[str] = None
    created_at: Optional[datetime] = None

class PriceListsListResponse(BaseModel):
    """Paginated list response for PriceLists."""
    items: List[PriceListsResponse]
    total: int
    skip: int = 0
    limit: int = 100

class UnitOfMeasuresCreate(BaseModel):
    """Schema for creating new UnitOfMeasures."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    company_id: Optional[UUID] = None
    code: str
    name: str
    name_ar: Optional[str] = None
    uom_type: Optional[str] = None
    is_active: Optional[bool] = True

class UnitOfMeasuresUpdate(BaseModel):
    """Schema for updating existing UnitOfMeasures."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    code: Optional[str] = None
    name: Optional[str] = None
    name_ar: Optional[str] = None
    uom_type: Optional[str] = None
    is_active: Optional[bool] = None

class UnitOfMeasuresResponse(AuditFields):
    """Response schema for UnitOfMeasures (includes all fields)."""
    model_config = ConfigDict(from_attributes=True, protected_namespaces=())

    id: UUID
    company_id: Optional[UUID] = None
    code: str
    name: str
    name_ar: Optional[str] = None
    uom_type: Optional[str] = None
    is_active: Optional[bool] = True

class UnitOfMeasuresListResponse(BaseModel):
    """Paginated list response for UnitOfMeasures."""
    items: List[UnitOfMeasuresResponse]
    total: int
    skip: int = 0
    limit: int = 100
