"""
Financial Module — CRUD Services
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.497083
Full CRUD with audit trail, soft delete, and business validations.
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID
from datetime import datetime
from decimal import Decimal

from sqlalchemy.orm import Session, joinedload
from sqlalchemy import and_, or_, desc, func
from fastapi import HTTPException, status
import uuid

from .financial_models import *
from .financial_schemas import *

class AccountsService:
    """CRUD service for Accounts."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: AccountsCreate, created_by: Optional[UUID] = None) -> AccountsResponse:
        """Create a new Accounts record."""
        db_obj = Accounts(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return AccountsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[AccountsResponse]:
        """Get Accounts by primary key."""
        db_obj = self.db.query(Accounts).filter(Accounts.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Accounts not found")
        return AccountsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> AccountsListResponse:
        """List Accounts records with pagination and filtering."""
        query = self.db.query(Accounts)
        if company_id and hasattr(Accounts, "company_id"):
            query = query.filter(Accounts.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(Accounts, key) and value is not None:
                    query = query.filter(getattr(Accounts, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(Accounts, order_by, Accounts.created_at)))
        else:
            query = query.order_by(getattr(Accounts, order_by, Accounts.created_at))
        items = query.offset(skip).limit(limit).all()
        return AccountsListResponse(
            items=[AccountsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: AccountsUpdate,
               updated_by: Optional[UUID] = None) -> AccountsResponse:
        """Update an existing Accounts record."""
        db_obj = self.db.query(Accounts).filter(Accounts.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Accounts not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return AccountsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a Accounts record. Soft delete by default."""
        db_obj = self.db.query(Accounts).filter(Accounts.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Accounts not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[AccountsResponse]:
        """Search Accounts by name/code fields."""
        query = self.db.query(Accounts)
        if company_id and hasattr(Accounts, "company_id"):
            query = query.filter(Accounts.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(Accounts, f)]
        if search_fields:
            conditions = [getattr(Accounts, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [AccountsResponse.model_validate(i) for i in items]

class CurrenciesService:
    """CRUD service for Currencies."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: CurrenciesCreate, created_by: Optional[UUID] = None) -> CurrenciesResponse:
        """Create a new Currencies record."""
        db_obj = Currencies(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "code") and getattr(db_obj, "code") is None:
            setattr(db_obj, "code", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return CurrenciesResponse.model_validate(db_obj)

    def get(self, code: str) -> Optional[CurrenciesResponse]:
        """Get Currencies by primary key."""
        db_obj = self.db.query(Currencies).filter(Currencies.code == code).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Currencies not found")
        return CurrenciesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> CurrenciesListResponse:
        """List Currencies records with pagination and filtering."""
        query = self.db.query(Currencies)
        if company_id and hasattr(Currencies, "company_id"):
            query = query.filter(Currencies.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(Currencies, key) and value is not None:
                    query = query.filter(getattr(Currencies, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(Currencies, order_by, Currencies.created_at)))
        else:
            query = query.order_by(getattr(Currencies, order_by, Currencies.created_at))
        items = query.offset(skip).limit(limit).all()
        return CurrenciesListResponse(
            items=[CurrenciesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, code: str, data: CurrenciesUpdate,
               updated_by: Optional[UUID] = None) -> CurrenciesResponse:
        """Update an existing Currencies record."""
        db_obj = self.db.query(Currencies).filter(Currencies.code == code).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Currencies not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return CurrenciesResponse.model_validate(db_obj)

    def delete(self, code: str, hard_delete: bool = False) -> bool:
        """Delete a Currencies record. Soft delete by default."""
        db_obj = self.db.query(Currencies).filter(Currencies.code == code).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Currencies not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[CurrenciesResponse]:
        """Search Currencies by name/code fields."""
        query = self.db.query(Currencies)
        if company_id and hasattr(Currencies, "company_id"):
            query = query.filter(Currencies.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(Currencies, f)]
        if search_fields:
            conditions = [getattr(Currencies, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [CurrenciesResponse.model_validate(i) for i in items]

class ExchangeRatesService:
    """CRUD service for ExchangeRates."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: ExchangeRatesCreate, created_by: Optional[UUID] = None) -> ExchangeRatesResponse:
        """Create a new ExchangeRates record."""
        db_obj = ExchangeRates(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return ExchangeRatesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[ExchangeRatesResponse]:
        """Get ExchangeRates by primary key."""
        db_obj = self.db.query(ExchangeRates).filter(ExchangeRates.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ExchangeRates not found")
        return ExchangeRatesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> ExchangeRatesListResponse:
        """List ExchangeRates records with pagination and filtering."""
        query = self.db.query(ExchangeRates)
        if company_id and hasattr(ExchangeRates, "company_id"):
            query = query.filter(ExchangeRates.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(ExchangeRates, key) and value is not None:
                    query = query.filter(getattr(ExchangeRates, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(ExchangeRates, order_by, ExchangeRates.created_at)))
        else:
            query = query.order_by(getattr(ExchangeRates, order_by, ExchangeRates.created_at))
        items = query.offset(skip).limit(limit).all()
        return ExchangeRatesListResponse(
            items=[ExchangeRatesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: ExchangeRatesUpdate,
               updated_by: Optional[UUID] = None) -> ExchangeRatesResponse:
        """Update an existing ExchangeRates record."""
        db_obj = self.db.query(ExchangeRates).filter(ExchangeRates.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ExchangeRates not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return ExchangeRatesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a ExchangeRates record. Soft delete by default."""
        db_obj = self.db.query(ExchangeRates).filter(ExchangeRates.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ExchangeRates not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[ExchangeRatesResponse]:
        """Search ExchangeRates by name/code fields."""
        query = self.db.query(ExchangeRates)
        if company_id and hasattr(ExchangeRates, "company_id"):
            query = query.filter(ExchangeRates.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(ExchangeRates, f)]
        if search_fields:
            conditions = [getattr(ExchangeRates, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [ExchangeRatesResponse.model_validate(i) for i in items]

class FiscalPeriodsService:
    """CRUD service for FiscalPeriods."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: FiscalPeriodsCreate, created_by: Optional[UUID] = None) -> FiscalPeriodsResponse:
        """Create a new FiscalPeriods record."""
        db_obj = FiscalPeriods(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return FiscalPeriodsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[FiscalPeriodsResponse]:
        """Get FiscalPeriods by primary key."""
        db_obj = self.db.query(FiscalPeriods).filter(FiscalPeriods.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="FiscalPeriods not found")
        return FiscalPeriodsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> FiscalPeriodsListResponse:
        """List FiscalPeriods records with pagination and filtering."""
        query = self.db.query(FiscalPeriods)
        if company_id and hasattr(FiscalPeriods, "company_id"):
            query = query.filter(FiscalPeriods.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(FiscalPeriods, key) and value is not None:
                    query = query.filter(getattr(FiscalPeriods, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(FiscalPeriods, order_by, FiscalPeriods.created_at)))
        else:
            query = query.order_by(getattr(FiscalPeriods, order_by, FiscalPeriods.created_at))
        items = query.offset(skip).limit(limit).all()
        return FiscalPeriodsListResponse(
            items=[FiscalPeriodsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: FiscalPeriodsUpdate,
               updated_by: Optional[UUID] = None) -> FiscalPeriodsResponse:
        """Update an existing FiscalPeriods record."""
        db_obj = self.db.query(FiscalPeriods).filter(FiscalPeriods.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="FiscalPeriods not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return FiscalPeriodsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a FiscalPeriods record. Soft delete by default."""
        db_obj = self.db.query(FiscalPeriods).filter(FiscalPeriods.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="FiscalPeriods not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[FiscalPeriodsResponse]:
        """Search FiscalPeriods by name/code fields."""
        query = self.db.query(FiscalPeriods)
        if company_id and hasattr(FiscalPeriods, "company_id"):
            query = query.filter(FiscalPeriods.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(FiscalPeriods, f)]
        if search_fields:
            conditions = [getattr(FiscalPeriods, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [FiscalPeriodsResponse.model_validate(i) for i in items]

class JournalEntriesService:
    """CRUD service for JournalEntries."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: JournalEntriesCreate, created_by: Optional[UUID] = None) -> JournalEntriesResponse:
        """Create a new JournalEntries record."""
        db_obj = JournalEntries(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return JournalEntriesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[JournalEntriesResponse]:
        """Get JournalEntries by primary key."""
        db_obj = self.db.query(JournalEntries).filter(JournalEntries.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="JournalEntries not found")
        return JournalEntriesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> JournalEntriesListResponse:
        """List JournalEntries records with pagination and filtering."""
        query = self.db.query(JournalEntries)
        if company_id and hasattr(JournalEntries, "company_id"):
            query = query.filter(JournalEntries.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(JournalEntries, key) and value is not None:
                    query = query.filter(getattr(JournalEntries, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(JournalEntries, order_by, JournalEntries.created_at)))
        else:
            query = query.order_by(getattr(JournalEntries, order_by, JournalEntries.created_at))
        items = query.offset(skip).limit(limit).all()
        return JournalEntriesListResponse(
            items=[JournalEntriesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: JournalEntriesUpdate,
               updated_by: Optional[UUID] = None) -> JournalEntriesResponse:
        """Update an existing JournalEntries record."""
        db_obj = self.db.query(JournalEntries).filter(JournalEntries.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="JournalEntries not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return JournalEntriesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a JournalEntries record. Soft delete by default."""
        db_obj = self.db.query(JournalEntries).filter(JournalEntries.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="JournalEntries not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[JournalEntriesResponse]:
        """Search JournalEntries by name/code fields."""
        query = self.db.query(JournalEntries)
        if company_id and hasattr(JournalEntries, "company_id"):
            query = query.filter(JournalEntries.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(JournalEntries, f)]
        if search_fields:
            conditions = [getattr(JournalEntries, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [JournalEntriesResponse.model_validate(i) for i in items]

class JournalLinesService:
    """CRUD service for JournalLines."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: JournalLinesCreate, created_by: Optional[UUID] = None) -> JournalLinesResponse:
        """Create a new JournalLines record."""
        db_obj = JournalLines(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return JournalLinesResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[JournalLinesResponse]:
        """Get JournalLines by primary key."""
        db_obj = self.db.query(JournalLines).filter(JournalLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="JournalLines not found")
        return JournalLinesResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> JournalLinesListResponse:
        """List JournalLines records with pagination and filtering."""
        query = self.db.query(JournalLines)
        if company_id and hasattr(JournalLines, "company_id"):
            query = query.filter(JournalLines.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(JournalLines, key) and value is not None:
                    query = query.filter(getattr(JournalLines, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(JournalLines, order_by, JournalLines.created_at)))
        else:
            query = query.order_by(getattr(JournalLines, order_by, JournalLines.created_at))
        items = query.offset(skip).limit(limit).all()
        return JournalLinesListResponse(
            items=[JournalLinesResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: JournalLinesUpdate,
               updated_by: Optional[UUID] = None) -> JournalLinesResponse:
        """Update an existing JournalLines record."""
        db_obj = self.db.query(JournalLines).filter(JournalLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="JournalLines not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return JournalLinesResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a JournalLines record. Soft delete by default."""
        db_obj = self.db.query(JournalLines).filter(JournalLines.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="JournalLines not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[JournalLinesResponse]:
        """Search JournalLines by name/code fields."""
        query = self.db.query(JournalLines)
        if company_id and hasattr(JournalLines, "company_id"):
            query = query.filter(JournalLines.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(JournalLines, f)]
        if search_fields:
            conditions = [getattr(JournalLines, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [JournalLinesResponse.model_validate(i) for i in items]
