"""
Project Mgmt Module — SQLAlchemy ORM Models
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.011230
One model class per table with full relationship support.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional
from uuid import UUID
import uuid

from sqlalchemy import (
    Column, Integer, BigInteger, SmallInteger,
    Numeric, Float, Boolean,
    String, Text, Unicode, UnicodeText,
    DateTime, Date, Time, DateTime, LargeBinary,
    ForeignKey, ForeignKeyConstraint, UniqueConstraint,
    Index, CheckConstraint, PrimaryKeyConstraint,
    TIMESTAMP, JSON, Enum, VARBINARY
)
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER, MONEY, SMALLMONEY, NVARCHAR, NTEXT, IMAGE
from sqlalchemy.orm import relationship, backref, mapped_column, Mapped
from sqlalchemy.sql import func

from app.core.database_mssql import Base

# Module metadata
__module_code__ = "project_mgmt-ebuild"
__tables__ = 2

class ProjectTasks(Base):
    """ProjectTasks — 17 columns, 3 FKs."""
    __tablename__ = "project_tasks"

    # FK: assignee_id -> employees.id
    # FK: parent_task_id -> project_tasks.id
    # FK: project_id -> projects.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    project_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    parent_task_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    description: Mapped[str] = mapped_column(Text)
    assignee_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    planned_hours: Mapped[Decimal] = mapped_column(Numeric(8, 2))
    actual_hours: Mapped[Decimal] = mapped_column(Numeric(8, 2))
    planned_cost: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    actual_cost: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    start_date: Mapped[date] = mapped_column(Date)
    end_date: Mapped[date] = mapped_column(Date)
    completion_pct: Mapped[Decimal] = mapped_column(Numeric(5, 2))
    status: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    sequence: Mapped[int] = mapped_column(Integer)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # assignee = relationship("Employees", back_populates="project_taskss")
    # parent_task = relationship("ProjectTasks", back_populates="project_taskss")
    # project = relationship("Projects", back_populates="project_taskss")

class Projects(Base):
    """Projects — 13 columns, 3 FKs."""
    __tablename__ = "projects"

    # FK: company_id -> companies.id
    # FK: customer_id -> business_partners.id
    # FK: project_manager_id -> employees.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    code: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    customer_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    project_manager_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    start_date: Mapped[date] = mapped_column(Date)
    end_date: Mapped[date] = mapped_column(Date)
    budget: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    currency: Mapped[str] = mapped_column(NVARCHAR(3))
    status: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # company = relationship("Companies", back_populates="projectss")
    # customer = relationship("BusinessPartners", back_populates="projectss")
    # project_manager = relationship("Employees", back_populates="projectss")
