"""
Project Mgmt Module — FastAPI Router
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.017810
Mounted at /api/v1/prj
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status, Query, Body
from sqlalchemy.orm import Session

from app.core.database_mssql import get_db
from .project_mgmt_schemas import *
from .project_mgmt_services import *

router = APIRouter(prefix="/prj", tags=["Project Mgmt"])

@router.get("/project_taskss", response_model=ProjectTasksListResponse)
def list_project_taskss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all ProjectTasks records."""
    service = ProjectTasksService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/project_taskss/{id}", response_model=ProjectTasksResponse)
def get_project_tasks(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get ProjectTasks by ID."""
    service = ProjectTasksService(db)
    return service.get(id)

@router.post("/project_taskss", response_model=ProjectTasksResponse, status_code=status.HTTP_201_CREATED)
def create_project_tasks(
    data: ProjectTasksCreate,
    db: Session = Depends(get_db)
):
    """Create a new ProjectTasks."""
    service = ProjectTasksService(db)
    return service.create(data)

@router.put("/project_taskss/{id}", response_model=ProjectTasksResponse)
def update_project_tasks(
    id: UUID,
    data: ProjectTasksUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing ProjectTasks."""
    service = ProjectTasksService(db)
    return service.update(id, data)

@router.delete("/project_taskss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_project_tasks(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a ProjectTasks (soft delete by default)."""
    service = ProjectTasksService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/project_taskss/search", response_model=List[ProjectTasksResponse])
def search_project_taskss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search ProjectTasks by name/code/description."""
    service = ProjectTasksService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/projectss", response_model=ProjectsListResponse)
def list_projectss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all Projects records."""
    service = ProjectsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/projectss/{id}", response_model=ProjectsResponse)
def get_projects(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get Projects by ID."""
    service = ProjectsService(db)
    return service.get(id)

@router.post("/projectss", response_model=ProjectsResponse, status_code=status.HTTP_201_CREATED)
def create_projects(
    data: ProjectsCreate,
    db: Session = Depends(get_db)
):
    """Create a new Projects."""
    service = ProjectsService(db)
    return service.create(data)

@router.put("/projectss/{id}", response_model=ProjectsResponse)
def update_projects(
    id: UUID,
    data: ProjectsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing Projects."""
    service = ProjectsService(db)
    return service.update(id, data)

@router.delete("/projectss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_projects(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a Projects (soft delete by default)."""
    service = ProjectsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/projectss/search", response_model=List[ProjectsResponse])
def search_projectss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search Projects by name/code/description."""
    service = ProjectsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/dashboard/summary")
def get_project_mgmt_dashboard(
    company_id: UUID,
    db: Session = Depends(get_db)
):
    """Get Project Mgmt dashboard summary."""
    return {
        "module": "project_mgmt",
        "company_id": str(company_id),
        "tables": 2,
        "metrics": {}
    }
