"""
Project Mgmt Module — FastAPI Sub-App
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.018025
Mounted at /api/v1/prj in Bio-ERP main.py
"""
from __future__ import annotations

from fastapi import FastAPI

from .project_mgmt_router import router as project_mgmt_router

def create_project_mgmt_app() -> FastAPI:
    """Factory function to create the project_mgmt sub-application."""
    app = FastAPI(
        title="Project Mgmt Module",
        description="ERP Project Mgmt module — 2 tables",
        version="3.0.0",
        docs_url="/docs",
        redoc_url="/redoc",
        openapi_url="/openapi.json"
    )
    app.include_router(project_mgmt_router)

    @app.get("/health")
    async def health_check():
        return {
            "status": "healthy",
            "module": "project_mgmt",
            "version": "3.0.0",
            "tables": 2,
            "database": "SQL Server 2022"
        }

    @app.get("/")
    async def root():
        return {
            "module": "project_mgmt",
            "version": "3.0.0",
            "endpoints": "/docs"
        }

    return app
