"""
Project Mgmt Module — CRUD Services
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:41.017642
Full CRUD with audit trail, soft delete, and business validations.
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID
from datetime import datetime
from decimal import Decimal

from sqlalchemy.orm import Session, joinedload
from sqlalchemy import and_, or_, desc, func
from fastapi import HTTPException, status
import uuid

from .project_mgmt_models import *
from .project_mgmt_schemas import *

class ProjectTasksService:
    """CRUD service for ProjectTasks."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: ProjectTasksCreate, created_by: Optional[UUID] = None) -> ProjectTasksResponse:
        """Create a new ProjectTasks record."""
        db_obj = ProjectTasks(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return ProjectTasksResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[ProjectTasksResponse]:
        """Get ProjectTasks by primary key."""
        db_obj = self.db.query(ProjectTasks).filter(ProjectTasks.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ProjectTasks not found")
        return ProjectTasksResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> ProjectTasksListResponse:
        """List ProjectTasks records with pagination and filtering."""
        query = self.db.query(ProjectTasks)
        if company_id and hasattr(ProjectTasks, "company_id"):
            query = query.filter(ProjectTasks.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(ProjectTasks, key) and value is not None:
                    query = query.filter(getattr(ProjectTasks, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(ProjectTasks, order_by, ProjectTasks.created_at)))
        else:
            query = query.order_by(getattr(ProjectTasks, order_by, ProjectTasks.created_at))
        items = query.offset(skip).limit(limit).all()
        return ProjectTasksListResponse(
            items=[ProjectTasksResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: ProjectTasksUpdate,
               updated_by: Optional[UUID] = None) -> ProjectTasksResponse:
        """Update an existing ProjectTasks record."""
        db_obj = self.db.query(ProjectTasks).filter(ProjectTasks.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ProjectTasks not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return ProjectTasksResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a ProjectTasks record. Soft delete by default."""
        db_obj = self.db.query(ProjectTasks).filter(ProjectTasks.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="ProjectTasks not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[ProjectTasksResponse]:
        """Search ProjectTasks by name/code fields."""
        query = self.db.query(ProjectTasks)
        if company_id and hasattr(ProjectTasks, "company_id"):
            query = query.filter(ProjectTasks.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(ProjectTasks, f)]
        if search_fields:
            conditions = [getattr(ProjectTasks, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [ProjectTasksResponse.model_validate(i) for i in items]

class ProjectsService:
    """CRUD service for Projects."""

    def __init__(self, db: Session):
        self.db = db

    def create(self, data: ProjectsCreate, created_by: Optional[UUID] = None) -> ProjectsResponse:
        """Create a new Projects record."""
        db_obj = Projects(**data.model_dump(exclude_unset=True))
        if hasattr(db_obj, "id") and getattr(db_obj, "id") is None:
            setattr(db_obj, "id", uuid.uuid4())
        if created_by and hasattr(db_obj, "created_by"):
            db_obj.created_by = created_by
        self.db.add(db_obj)
        self.db.commit()
        self.db.refresh(db_obj)
        return ProjectsResponse.model_validate(db_obj)

    def get(self, id: UUID) -> Optional[ProjectsResponse]:
        """Get Projects by primary key."""
        db_obj = self.db.query(Projects).filter(Projects.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Projects not found")
        return ProjectsResponse.model_validate(db_obj)

    def list(self, company_id: Optional[UUID] = None, skip: int = 0, limit: int = 100,
             order_by: str = "created_at", order_desc: bool = True,
             filters: Optional[Dict[str, Any]] = None) -> ProjectsListResponse:
        """List Projects records with pagination and filtering."""
        query = self.db.query(Projects)
        if company_id and hasattr(Projects, "company_id"):
            query = query.filter(Projects.company_id == company_id)
        if filters:
            for key, value in filters.items():
                if hasattr(Projects, key) and value is not None:
                    query = query.filter(getattr(Projects, key) == value)
        total = query.count()
        if order_desc:
            query = query.order_by(desc(getattr(Projects, order_by, Projects.created_at)))
        else:
            query = query.order_by(getattr(Projects, order_by, Projects.created_at))
        items = query.offset(skip).limit(limit).all()
        return ProjectsListResponse(
            items=[ProjectsResponse.model_validate(i) for i in items],
            total=total, skip=skip, limit=limit)

    def update(self, id: UUID, data: ProjectsUpdate,
               updated_by: Optional[UUID] = None) -> ProjectsResponse:
        """Update an existing Projects record."""
        db_obj = self.db.query(Projects).filter(Projects.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Projects not found")
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            if hasattr(db_obj, field) and value is not None:
                setattr(db_obj, field, value)
        if updated_by and hasattr(db_obj, "updated_by"):
            db_obj.updated_by = updated_by
        if hasattr(db_obj, "updated_at"):
            db_obj.updated_at = datetime.utcnow()
        self.db.commit()
        self.db.refresh(db_obj)
        return ProjectsResponse.model_validate(db_obj)

    def delete(self, id: UUID, hard_delete: bool = False) -> bool:
        """Delete a Projects record. Soft delete by default."""
        db_obj = self.db.query(Projects).filter(Projects.id == id).first()
        if not db_obj:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Projects not found")
        if not hard_delete and hasattr(db_obj, "is_active"):
            db_obj.is_active = False
            self.db.commit()
            return True
        self.db.delete(db_obj)
        self.db.commit()
        return True

    def search(self, query_str: str, company_id: Optional[UUID] = None,
               limit: int = 20) -> List[ProjectsResponse]:
        """Search Projects by name/code fields."""
        query = self.db.query(Projects)
        if company_id and hasattr(Projects, "company_id"):
            query = query.filter(Projects.company_id == company_id)
        search_fields = [f for f in ["name", "code", "description", "email", "phone"]
                         if hasattr(Projects, f)]
        if search_fields:
            conditions = [getattr(Projects, f).ilike("%" + query_str + "%") for f in search_fields]
            query = query.filter(or_(*conditions))
        items = query.limit(limit).all()
        return [ProjectsResponse.model_validate(i) for i in items]
