"""
Inventory Module — FastAPI Router
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.627755
Mounted at /api/v1/inv
"""
from __future__ import annotations

from typing import List, Optional, Dict, Any
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status, Query, Body
from sqlalchemy.orm import Session

from app.core.database_mssql import get_db
from .inventory_schemas import *
from .inventory_services import *

router = APIRouter(prefix="/inv", tags=["Inventory"])

@router.get("/cycle_countss", response_model=CycleCountsListResponse)
def list_cycle_countss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all CycleCounts records."""
    service = CycleCountsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/cycle_countss/{id}", response_model=CycleCountsResponse)
def get_cycle_counts(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get CycleCounts by ID."""
    service = CycleCountsService(db)
    return service.get(id)

@router.post("/cycle_countss", response_model=CycleCountsResponse, status_code=status.HTTP_201_CREATED)
def create_cycle_counts(
    data: CycleCountsCreate,
    db: Session = Depends(get_db)
):
    """Create a new CycleCounts."""
    service = CycleCountsService(db)
    return service.create(data)

@router.put("/cycle_countss/{id}", response_model=CycleCountsResponse)
def update_cycle_counts(
    id: UUID,
    data: CycleCountsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing CycleCounts."""
    service = CycleCountsService(db)
    return service.update(id, data)

@router.delete("/cycle_countss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_cycle_counts(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a CycleCounts (soft delete by default)."""
    service = CycleCountsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/cycle_countss/search", response_model=List[CycleCountsResponse])
def search_cycle_countss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search CycleCounts by name/code/description."""
    service = CycleCountsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/stock_balancess", response_model=StockBalancesListResponse)
def list_stock_balancess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all StockBalances records."""
    service = StockBalancesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/stock_balancess/{id}", response_model=StockBalancesResponse)
def get_stock_balances(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get StockBalances by ID."""
    service = StockBalancesService(db)
    return service.get(id)

@router.post("/stock_balancess", response_model=StockBalancesResponse, status_code=status.HTTP_201_CREATED)
def create_stock_balances(
    data: StockBalancesCreate,
    db: Session = Depends(get_db)
):
    """Create a new StockBalances."""
    service = StockBalancesService(db)
    return service.create(data)

@router.put("/stock_balancess/{id}", response_model=StockBalancesResponse)
def update_stock_balances(
    id: UUID,
    data: StockBalancesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing StockBalances."""
    service = StockBalancesService(db)
    return service.update(id, data)

@router.delete("/stock_balancess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_stock_balances(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a StockBalances (soft delete by default)."""
    service = StockBalancesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/stock_balancess/search", response_model=List[StockBalancesResponse])
def search_stock_balancess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search StockBalances by name/code/description."""
    service = StockBalancesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/stock_movementss", response_model=StockMovementsListResponse)
def list_stock_movementss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all StockMovements records."""
    service = StockMovementsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/stock_movementss/{id}", response_model=StockMovementsResponse)
def get_stock_movements(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get StockMovements by ID."""
    service = StockMovementsService(db)
    return service.get(id)

@router.post("/stock_movementss", response_model=StockMovementsResponse, status_code=status.HTTP_201_CREATED)
def create_stock_movements(
    data: StockMovementsCreate,
    db: Session = Depends(get_db)
):
    """Create a new StockMovements."""
    service = StockMovementsService(db)
    return service.create(data)

@router.put("/stock_movementss/{id}", response_model=StockMovementsResponse)
def update_stock_movements(
    id: UUID,
    data: StockMovementsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing StockMovements."""
    service = StockMovementsService(db)
    return service.update(id, data)

@router.delete("/stock_movementss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_stock_movements(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a StockMovements (soft delete by default)."""
    service = StockMovementsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/stock_movementss/search", response_model=List[StockMovementsResponse])
def search_stock_movementss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search StockMovements by name/code/description."""
    service = StockMovementsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/warehouse_locationss", response_model=WarehouseLocationsListResponse)
def list_warehouse_locationss(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all WarehouseLocations records."""
    service = WarehouseLocationsService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/warehouse_locationss/{id}", response_model=WarehouseLocationsResponse)
def get_warehouse_locations(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get WarehouseLocations by ID."""
    service = WarehouseLocationsService(db)
    return service.get(id)

@router.post("/warehouse_locationss", response_model=WarehouseLocationsResponse, status_code=status.HTTP_201_CREATED)
def create_warehouse_locations(
    data: WarehouseLocationsCreate,
    db: Session = Depends(get_db)
):
    """Create a new WarehouseLocations."""
    service = WarehouseLocationsService(db)
    return service.create(data)

@router.put("/warehouse_locationss/{id}", response_model=WarehouseLocationsResponse)
def update_warehouse_locations(
    id: UUID,
    data: WarehouseLocationsUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing WarehouseLocations."""
    service = WarehouseLocationsService(db)
    return service.update(id, data)

@router.delete("/warehouse_locationss/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_warehouse_locations(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a WarehouseLocations (soft delete by default)."""
    service = WarehouseLocationsService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/warehouse_locationss/search", response_model=List[WarehouseLocationsResponse])
def search_warehouse_locationss(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search WarehouseLocations by name/code/description."""
    service = WarehouseLocationsService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/warehousess", response_model=WarehousesListResponse)
def list_warehousess(
    company_id: Optional[UUID] = None,
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    db: Session = Depends(get_db)
):
    """List all Warehouses records."""
    service = WarehousesService(db)
    return service.list(company_id=company_id, skip=skip, limit=limit)

@router.get("/warehousess/{id}", response_model=WarehousesResponse)
def get_warehouses(
    id: UUID,
    db: Session = Depends(get_db)
):
    """Get Warehouses by ID."""
    service = WarehousesService(db)
    return service.get(id)

@router.post("/warehousess", response_model=WarehousesResponse, status_code=status.HTTP_201_CREATED)
def create_warehouses(
    data: WarehousesCreate,
    db: Session = Depends(get_db)
):
    """Create a new Warehouses."""
    service = WarehousesService(db)
    return service.create(data)

@router.put("/warehousess/{id}", response_model=WarehousesResponse)
def update_warehouses(
    id: UUID,
    data: WarehousesUpdate,
    db: Session = Depends(get_db)
):
    """Update an existing Warehouses."""
    service = WarehousesService(db)
    return service.update(id, data)

@router.delete("/warehousess/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_warehouses(
    id: UUID,
    hard_delete: bool = Query(False, description="Permanently delete instead of soft delete"),
    db: Session = Depends(get_db)
):
    """Delete a Warehouses (soft delete by default)."""
    service = WarehousesService(db)
    service.delete(id, hard_delete=hard_delete)
    return None

@router.get("/warehousess/search", response_model=List[WarehousesResponse])
def search_warehousess(
    q: str = Query(..., min_length=1, description="Search query"),
    company_id: Optional[UUID] = None,
    limit: int = Query(20, ge=1, le=100),
    db: Session = Depends(get_db)
):
    """Search Warehouses by name/code/description."""
    service = WarehousesService(db)
    return service.search(q, company_id=company_id, limit=limit)

@router.get("/dashboard/summary")
def get_inventory_dashboard(
    company_id: UUID,
    db: Session = Depends(get_db)
):
    """Get Inventory dashboard summary."""
    return {
        "module": "inventory",
        "company_id": str(company_id),
        "tables": 5,
        "metrics": {}
    }
