"""
Inventory Module — SQLAlchemy ORM Models
Auto-generated by erp_organ_generator.py on 2026-06-15T23:19:40.611980
One model class per table with full relationship support.
"""
from __future__ import annotations

from decimal import Decimal
from datetime import datetime, date, time
from typing import List, Optional
from uuid import UUID
import uuid

from sqlalchemy import (
    Column, Integer, BigInteger, SmallInteger,
    Numeric, Float, Boolean,
    String, Text, Unicode, UnicodeText,
    DateTime, Date, Time, DateTime, LargeBinary,
    ForeignKey, ForeignKeyConstraint, UniqueConstraint,
    Index, CheckConstraint, PrimaryKeyConstraint,
    TIMESTAMP, JSON, Enum, VARBINARY
)
from sqlalchemy.dialects.mssql import UNIQUEIDENTIFIER, MONEY, SMALLMONEY, NVARCHAR, NTEXT, IMAGE
from sqlalchemy.orm import relationship, backref, mapped_column, Mapped
from sqlalchemy.sql import func

from app.core.database_mssql import Base

# Module metadata
__module_code__ = "inventory-ebuild"
__tables__ = 5

class CycleCounts(Base):
    """CycleCounts — 13 columns, 5 FKs."""
    __tablename__ = "cycle_counts"

    # FK: adjustment_movement_id -> stock_movements.id
    # FK: company_id -> companies.id
    # FK: counted_by -> users.id
    # FK: item_id -> items.id
    # FK: location_id -> warehouse_locations.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    location_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    item_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    counted_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    system_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    variance: Mapped[Decimal] = mapped_column(Numeric(19, 4))
    counted_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    counted_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    is_adjusted: Mapped[bool] = mapped_column(Boolean)
    adjustment_movement_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    notes: Mapped[str] = mapped_column(Text)
    metadata_: Mapped[str] = mapped_column("metadata", Text)

    # adjustment_movement = relationship("StockMovements", back_populates="cycle_countss")
    # company = relationship("Companies", back_populates="cycle_countss")
    # counted_by = relationship("Users", back_populates="cycle_countss")
    # item = relationship("Items", back_populates="cycle_countss")
    # location = relationship("WarehouseLocations", back_populates="cycle_countss")

class StockBalances(Base):
    """StockBalances — 14 columns, 3 FKs."""
    __tablename__ = "stock_balances"

    # FK: company_id -> companies.id
    # FK: item_id -> items.id
    # FK: location_id -> warehouse_locations.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    item_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    location_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    lot_number: Mapped[str] = mapped_column(NVARCHAR(255))
    serial_number: Mapped[str] = mapped_column(NVARCHAR(255))
    lot_number_nn: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    serial_number_nn: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    reserved_qty: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    available_qty: Mapped[Decimal] = mapped_column(Numeric(19, 4))
    unit_cost: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    last_movement_at: Mapped[datetime] = mapped_column(DateTime)
    metadata_: Mapped[str] = mapped_column("metadata", Text)

    # company = relationship("Companies", back_populates="stock_balancess")
    # item = relationship("Items", back_populates="stock_balancess")
    # location = relationship("WarehouseLocations", back_populates="stock_balancess")

class StockMovements(Base):
    """StockMovements — 18 columns, 6 FKs."""
    __tablename__ = "stock_movements"

    # FK: company_id -> companies.id
    # FK: from_location_id -> warehouse_locations.id
    # FK: item_id -> items.id
    # FK: journal_entry_id -> journal_entries.id
    # FK: moved_by -> users.id
    # FK: to_location_id -> warehouse_locations.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    movement_type: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    item_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    from_location_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    to_location_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    lot_number: Mapped[str] = mapped_column(NVARCHAR(255))
    serial_number: Mapped[str] = mapped_column(NVARCHAR(255))
    quantity: Mapped[Decimal] = mapped_column(Numeric(18, 4), nullable=False)
    unit_cost: Mapped[Decimal] = mapped_column(Numeric(18, 4))
    source_doc_type: Mapped[str] = mapped_column(NVARCHAR(255))
    source_doc_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    moved_by: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    movement_date: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    journal_entry_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    notes: Mapped[str] = mapped_column(Text)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # company = relationship("Companies", back_populates="stock_movementss")
    # from_location = relationship("WarehouseLocations", back_populates="stock_movementss")
    # item = relationship("Items", back_populates="stock_movementss")
    # journal_entry = relationship("JournalEntries", back_populates="stock_movementss")
    # moved_by = relationship("Users", back_populates="stock_movementss")
    # to_location = relationship("WarehouseLocations", back_populates="stock_movementss")

class WarehouseLocations(Base):
    """WarehouseLocations — 11 columns, 2 FKs."""
    __tablename__ = "warehouse_locations"

    # FK: parent_id -> warehouse_locations.id
    # FK: warehouse_id -> warehouses.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    warehouse_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    code: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    name: Mapped[str] = mapped_column(NVARCHAR(255))
    parent_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    location_type: Mapped[str] = mapped_column(NVARCHAR(255))
    is_pickable: Mapped[bool] = mapped_column(Boolean)
    is_storable: Mapped[bool] = mapped_column(Boolean)
    max_weight_kg: Mapped[Decimal] = mapped_column(Numeric(10, 2))
    max_volume_m3: Mapped[Decimal] = mapped_column(Numeric(10, 2))
    metadata_: Mapped[str] = mapped_column("metadata", Text)

    # parent = relationship("WarehouseLocations", back_populates="warehouse_locationss")
    # warehouse = relationship("Warehouses", back_populates="warehouse_locationss")

class Warehouses(Base):
    """Warehouses — 9 columns, 2 FKs."""
    __tablename__ = "warehouses"

    # FK: address_id -> partner_addresses.id
    # FK: company_id -> companies.id

    id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, primary_key=True, nullable=False)
    company_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, nullable=False, default=uuid.uuid4)
    code: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    name: Mapped[str] = mapped_column(NVARCHAR(255), nullable=False)
    address_id: Mapped[UUID] = mapped_column(UNIQUEIDENTIFIER, default=uuid.uuid4)
    is_virtual: Mapped[bool] = mapped_column(Boolean)
    is_active: Mapped[bool] = mapped_column(Boolean)
    metadata_: Mapped[str] = mapped_column("metadata", Text)
    created_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)

    # address = relationship("PartnerAddresses", back_populates="warehousess")
    # company = relationship("Companies", back_populates="warehousess")
